
#ーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーー
#
#  00  11                  1            1                  11  00  |
#  1100  0000 1000          1          1          0001 0000  0011  |
#    0000000       1          0      0          1      00000000    |
#    1000 0    11    110      1      1      011    11    0 0001    |
#   1100 0    1001      100     1  1     001      1001    0 0011   |
#    10000   100001  111   101  1  1  101   111  100001   00001    |
#     0000 0  10010 1        0   00   0        1 01001  0 0000     |
#      000     11000 1          0110          1 00011     000      |
#      000000     0 1 111    00 1  1 00   111 1 0     000000       |
#       00000            111  00111100  111            00000       |
#       00   0        000      011110      000        0   00       |
#         0000  000000       0 0 11 0 0       000000  0000         |
#             1 000     00    11 11 11    00     000 1             |
#               00           01  11  10           00               |
#              100  1000100 001  11   100 0100001  001             |
#                100   101                  101   001              |
#                 0     1                    1     0               |
#                       1                    1                     |
#
#ーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーー

# コマンド短縮
import:
    java.util.Arrays
    org.bukkit.Sound
command /m:
    trigger:
        stop
command /mm <string> <number>:
    trigger:
        stop
command /gm <string> [<player>]:
    trigger:
        stop
on command:
    cancel event
    (ops and console) contain sender
    set {_a::*} to full command split at " "
    switch command:
        case "r":
            execute player command "/skript reload scripts"
        case "a":
            execute player command "/r" # AdminMenu(player,1)
            # set gamemode of player to creative if player's gamemode is spectator
        case "mm":
            stop all sounds for player
            player.getWorld().playSound(player.getLocation(),lower case {_a::2},1,{_a::3} parsed as number)
        case "gm":
            switch {_a::2}:
                case "0" -> execute server command "/gamemode survival %{_a::3} if {_a::3} is set else player%"
                case "1" -> execute server command "/gamemode creative %{_a::3} if {_a::3} is set else player%"
                case "2" -> execute server command "/gamemode adventure %{_a::3} if {_a::3} is set else player%"
                case "3" -> execute server command "/gamemode spectator %{_a::3} if {_a::3} is set else player%"
        case "m":
            set {_a} to Arrays.asList(Sound.values())
            send "&8&o - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -" to player
            loop 7 times:
                set {_r} to {_a}.get(random integer between 0 and ({_a}.size() - 1))
                send formatted "&8&o  &8&o<cmd:/mm %{_r}% 0><&7&o0&8&o><reset> &8&o<cmd:/mm %{_r}% 1><&7&o1&8&o><reset> &8&o<cmd:/mm %{_r}% 2><&7&o2&8&o><reset> &8&o%{_r}%" to player
            send formatted "&8&o  &8&o<cmd:/m><&7&o   roll    &8&o><reset>" to player
            send "&8&o - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -" to player
        default:
            uncancel event

# ライブラリ関数
function Loc(e0:location,dy:number=0) :: string:
    return "%x of {_e0}% %{_dy} + y of {_e0}% %z of {_e0}%"
function Has(es:objects,e0:object) :: boolean:
    loop {_es::*}:
        return true if loop-value is {_e0}
    return false










# function Ready(p:player,s:timespan,t:string="OFF") :: boolean:
#     if {_t} is "RESET":
#         set the cooldown of enchanted book for {_p} to {_s}
#         if {game_cheat} is true:
#             set the cooldown of enchanted book for {_p} to 2 second
#             {_s} > 2 second
#         return true
#     else:
#         if any:
#             cooldown of enchanted book for {_p} > 0 tick
#             {_p}'s gamemode is spectator
#             {game} isn't set
#         then:
#             return false
#         Ready({_p},{_s},"RESET") is true
#         make {_p} swing their main hand
#         return true
# function Own(e:entity,s:string,t:string="MAINHAND") :: boolean:
#     if {_t} is "MAINHAND":
#         return true if {_s} is string tag "skill" of custom nbt of {_e}'s tool
#     else if {_t} is "INVENTORY":
#         loop items in {_e}'s inventory:
#             return true if {_s} is string tag "skill" of custom nbt of loop-item
#     return false








# # 特殊アクション
# on sneak toggle:
#     player is on ground
#     player is sprinting
#     player isn't sneaking
#     player's gamemode isn't spectator
#     player doesn't have potion effect oozing
#     player doesn't have potion effect weakness
#     set {_p} to vector in horizontal direction of player
#     loop 18 times:
#         # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
#         wait 1 tick
#         while size of {停止::*} > 0:
#             wait a tick
#         if any:
#             {game} isn't set
#             player isn't sneaking
#             player isn't on ground
#             gamemode of player is spectator
#         then:
#             stop loop
#         # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
#         apply potion of oozing tier 255 without particles whilst hiding icon to player for 0.5 seconds replacing existing effect
#         execute console command "/playsound minecraft:block.cave_vines.pick_berries master @a %Loc(player)% 0.3 0.8"
#         make 1 of block particle using (type of block under player) at player
#         push player {_p} * 0.8 / loop-counter
#         player.setRiptiding(true)
#     player.setRiptiding(false)
# on sneak toggle:
#     player is on ground
#     player isn't sneaking
#     player isn't sprinting
#     player's gamemode isn't spectator
#     player doesn't have potion effect oozing
#     player doesn't have potion effect weakness
#     set {_p} to vector in horizontal direction of player
#     loop living entities in radius 2.3 around player sorted by distance from player:
#         set {_e} to vector in horizontal direction of loop-entity
#         set {_d} to vector between player and loop-entity
#         gamemode of loop-entity isn't spectator
#         loop-entity isn't player
#         {_p} dot {_e} > 0
#         {_p} dot {_d} > 0
#         set {_a} to loop-entity
#         stop loop
#     {_a} is an entity
#     loop 600 times:
#         # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
#         wait 1 tick
#         while size of {停止::*} > 0:
#             wait a tick
#         if any:
#             {_a} is dead
#             {game} isn't set
#             gamemode of {_a} is spectator
#             gamemode of player is spectator
#             distance between player and {_a} is more than 2.3
#         then:
#             stop loop
#         # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
#         apply potion of weakness tier 255 without particles whilst hiding icon to player for 1 seconds replacing existing effect
#         apply potion of weakness tier 255 without particles whilst hiding icon to {_a} for 1 seconds replacing existing effect
#         execute console command "/playsound minecraft:item.lead.tied master @a %Loc(player)% 0.6 1.3" if loop-counter is 1
#         execute console command "/particle crit %Loc({_a},1)% 0 0 0 0.3 1 force @a"
#         teleport {_a} at location 0.7 meter horizontal in front of player
#         if player isn't sneaking:
#             execute console command "/playsound minecraft:entity.witch.throw master @a %Loc(player)% 0.4 0.8"
#             remove weakness from player
#             knockback {_a} forwards
#             stop

# # 管理者メニュー
# function AdminMenu(p:player,n:integer=1):
#     set {_ui} to chest inventory with 6 row named "管理者メニュー (%{_n}%/%ceil(size of {skill::*}/36)%)"
#     execute console command "/playsound minecraft:item.book.page_turn master %{_p}% ~ ~ ~ 0.3 1.6 0.3"
#     loop 9 times:
#         set slot (loop-number +44) of {_ui} to iron bars named "&0" without entire tooltip
#         set slot (loop-number -1) of {_ui} to iron bars named "&0" without entire tooltip
#     loop 36 times:
#         set slot (loop-number +8) of {_ui} to {skill::%loop-number + ({_n} -1)*36%}
#     set slot 45 of {_ui} to soul lantern named "&rプレイヤーとして参加"
#     set slot 50 of {_ui} to command block minecart named "&rゲームを再読込"
#     set slot 45 of {_ui} to lantern named "&rプレイヤーから離脱" if {play::*} contain {_p}
#     set slot 48 of {_ui} to sculk sensor named "&rチートを有効化" if {game_cheat} is not true
#     set slot 48 of {_ui} to calibrated sculk sensor named "&rチートを無効化" if {game_cheat} is true
#     set slot 46 of {_ui} to music disc stal named "&rノーマルモードへ変更" if {game_suddendeath} is true
#     set slot 46 of {_ui} to music disc chirp named "&rサドンデスモードへ変更" if {game_suddendeath} isn't set
#     set slot 46 of {_ui} to music disc 11 named "&rサドンデスモードに固定" without entire tooltip if {game_suddendeath} is false
#     set slot 7 of {_ui} to (size of {map::*} +1) of filled map named "&rマップをランダム選択" with nbt from "{""components"":{""minecraft:map_color"":%random integer between 0 and 16777215%,""minecraft:max_stack_size"":99}}"
#     set slot 49 of {_ui} to player head named "&rゲームを終了" with nbt from "{""minecraft:profile"":{id:[I;276560226,289299024,-1648091673,1766957495],name:"""",properties:[{name:""textures"",value:""eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNzlhYTMyYWI3NTY2MDIzYTZkMmU2MjdiNDg4OTRlZGU5NWU2ZjYyYjhlMWI1NDQ1NzMwNGUwYmQxMTFiMTZmZCJ9fX0=""}]}}" if {game} is set
#     set slot 49 of {_ui} to player head named "&rゲームを開始" with nbt from "{""minecraft:profile"":{id:[I;1846823252,1344232203,-2116385834,1342708963],name:"""",properties:[{name:""textures"",value:""eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYjkzYTIwZGI5ZjFmMDA4MzhjMWRlNjhhZWI5NjA1YzAyZjcxYTU2OTg4ODA5YzVjMDE4MTdjZGJjZGUwYjZiMSJ9fX0=""}]}}" if {game} isn't set
#     set slot 52 of {_ui} to arrow named "&0" without entire tooltip
#     set slot 53 of {_ui} to arrow named "&0" without entire tooltip
#     set slot 52 of {_ui} to spectral arrow named "&r前のページ" if {_n} > 1
#     set slot 53 of {_ui} to spectral arrow named "&r次のページ" if {_n} < ceil(size of {skill::*}/36)
#     open {_ui} to {_p}
# on inventory close:
#     stop if {play::*} contain player
#     name of player's current inventory start with "管理者メニュー"
#     wait a tick
#     stop if {play::*} contain player
#     name of player's current inventory doesn't start with "管理者メニュー"
#     set gamemode of player to spectator
# on inventory click:
#     name of player's inventory start with "管理者メニュー"
#     event.getRawSlot() is between 0 and 53
#     cancel event
#     execute console command "/playsound minecraft:block.tripwire.click_off master %player% ~ ~ ~ 0.3 1.6 0.3"
#     set {_n::*} to player's inventory's name parsed as "管理者メニュー \(%integer%/%integer%\)"
#     if item is spectral arrow:
#         AdminMenu(player,{_n::1} -1) if clicked slot is 52
#         AdminMenu(player,{_n::1} +1) if clicked slot is 53
#     else if clicked slot is 50:
#         close player's inventory
#         execute player command "/r"
#     else if clicked slot is 49:
#         close player's inventory
#         execute player command "/s"
#     else if clicked slot is 48:
#         if {game_cheat} is set:
#             clear {game_cheat}
#         else:
#             set {game_cheat} to true
#             loop players:
#                 set cooldown of enchanted book for loop-player to 0 tick
#         AdminMenu(player,{_n::1})
#     else if clicked slot is 46:
#         if {game_suddendeath} isn't set:
#             set {game_suddendeath} to true
#         else if {game_suddendeath} is true:
#             clear {game_suddendeath}
#         AdminMenu(player,{_n::1})
#         loop 40 times:
#             wait a tick
#             stop if {game} isn't set
#             stop if {game_suddendeath} isn't true
#         set {game_suddendeath} to false
#         execute console command "/playsound minecraft:entity.elder_guardian.death master @a ~ ~ ~ 0.3 0 0.3"
#         send title "&4サドンデスモード" with subtitle "&8生存者全員が瀕死になります" to all players
#         execute console command "/effect give @a blindness 1 1 true"
#         set max health of all players to 1
#         set health of all players to 1
#         loop players:
#             close loop-player's inventory
#             apply glowing 1 without any particles without a potion icon to loop-player for 999 days        
#     else if clicked slot is 45:
#         close player's inventory
#         if {play::*} contain player:
#             Reset(player)
#         else:
#             close player's inventory
#             Reset(player,"play")
#     else if clicked slot is 7:
#         ShuffledMap(true)
#         AdminMenu(player,{_n::1})
#     else if clicked slot is between 9 and 45:
#         give item to player if item isn't structure void

# #ーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーー

# #ーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーー

# # 特殊ダメージ処理
# on damage of entity:
#     {game} is set
#     {運命::*} contain victim
#     if victim's health <= final damage:
#         set {_運命::*} to {運命::*}
#         clear {運命::*}
#         loop {_運命::*}:
#             loop-value isn't victim
#             kill loop-value if Own(loop-value,"背信","INVENTORY") is false
#             execute console command "/playsound minecraft:entity.wither.spawn master @a %Loc(loop-value)% 0.1 0 0.1"
#             execute console command "/playsound minecraft:block.trial_spawner.detect_player master @a %Loc(loop-value)% 0.4 0.6 0.4"
#     else:
#         loop {運命::*}:
#             loop-value isn't victim
#             set loop-value's health to victim's health if Own(loop-value,"背信","INVENTORY") is false

# # ダメージパイプライン
# on damage of player:
#     # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
#     if any:
#         {game} isn't set
#         size of {停止::*} > 0
#         {不死::*} contain victim
#         gamemode of victim is creative
#         gamemode of victim is spectator
#     then:
#         cancel event
#     # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
#     switch "%damage cause%":
#         case "suffocation":
#             cancel event if Own(victim,"貫通","INVENTORY") is true
#         case "starvation":
#             cancel event if Own(victim,"貪食","INVENTORY") is true
#         case "lightning":
#             cancel event if Own(victim,"稲妻","INVENTORY") is true
#         case "fall":
#             cancel event if Own(victim,"軽量","INVENTORY") is true
#     # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
#     # 能力による処理
#     if Own(victim,"経過","INVENTORY") is true:
#         stop if event is cancelled
#         Ready(victim, 100 seconds) is true
#         execute console command "/playsound minecraft:entity.player.hurt_sweet_berry_bush master %victim% %Loc(victim)% 0.4 1"
#         execute console command "/playsound minecraft:entity.silverfish.hurt master %victim% %Loc(victim)% 0.3 1.5"
#         execute console command "/effect give %victim% minecraft:blindness 1 10 true"
#         apply potion of invisibility tier 100 without particles to victim for 3 tick
#         apply potion of resistance tier 100 without particles to victim for 3 tick
#         apply potion of swiftness tier 100 without particles to victim for 3 tick
#         cancel event
#         stop
#     # 死亡判定
#     stop if event is cancelled
#     victim's health <= final damage:
#         if all:
#             victim isn't burning
#             Ready(victim, 80 seconds) is true
#             Own(victim,"不死","INVENTORY") is true
#         then:
#             DeathEffect(victim,"true")
#         else:
#             DeathEffect(victim,"false")
#         set damage to 0

# function DeathEffect(e:player,t:string):
#     set {_l} to {_e}'s location
#     loop blocks in radius 2 around {_l}:
#         block at location of loop-block is air
#         block under loop-block isn't air or redstone wire
#         set the loop-block to redstone wire if chance of 50%
#     execute console command "/effect give %{_e}% minecraft:blindness 1 255 true"
#     execute console command "/playsound minecraft:entity.generic.hurt master @a %Loc({_e})% 0.4 0.8"
#     execute console command "/playsound minecraft:entity.ender_dragon.hurt master @a %Loc({_e})% 0.4 0.9"
#     execute console command "/particle minecraft:landing_lava %Loc({_e},0.5)% 0.8 0.8 0.8 0.1 100 force @a"
#     execute console command "/particle minecraft:item{item:""redstone""} %Loc({_e},0.5)% 0 0 0 0.3 100 force @a"
#     if {_t} is "false":
#         Reset({_e},"spec")
#         drop 1 of {_e}'s skull at {_l}
#         loop items in {_e}'s inventory:
#             loop-item's name isn't "&0"
#             wait 1 tick
#             while size of {停止::*} > 0:
#                 wait a tick
#             stop if {game} isn't set
#             drop loop-item at {_l}
#             subtract loop-item from {_e}'s inventory
#             execute console command "/playsound minecraft:entity.item.pickup master @a %Loc({_l})% 0.3 %random number between 1 and 2%"
#     else:
#         drop 1 of {_e}'s skull named "&0" at {_l}
#         add last dropped item to {_不死::*}
#         set gamemode of {_e} to spectator
#         loop items in {_e}'s inventory:
#             loop-item's name isn't "&0"
#             wait 1 tick
#             while size of {停止::*} > 0:
#                 wait a tick
#             stop if {game} isn't set
#             drop loop-item named "&0" at {_l}
#             add last dropped item to {_不死::*}
#             execute console command "/playsound minecraft:entity.item.pickup master @a %Loc({_l})% 0.3 %random number between 1 and 2%"
#         #
#         send title "&4░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░" with subtitle "&4░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░" to {_e}
#         execute console command "/playsound minecraft:entity.skeleton_horse.ambient_water master %{_e}% ~ ~ ~ 0.5 0.8 0.5"
#         execute console command "/playsound minecraft:entity.squid.hurt master %{_e}% ~ ~ ~ 0.5 0 0.5"
#         execute console command "/effect give %{_e}% darkness 5 5 true"
#         add {_e} to {不死::*}
#         unequip {_e}'s armor
#         loop 180 times:
#             # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
#             wait 1 tick
#             while size of {停止::*} > 0:
#                 wait a tick
#             if any:
#                 {game} isn't set
#                 {spec::*} contain player
#             then:
#                 stop loop
#             Ready({_e}, 80 seconds, "RESET")
#             # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
#             if loop-counter = 100:
#                 Reset({_e},"play")
#                 teleport {_e} at {_l}
#                 set {_e}'s health to 0.5
#                 loop 20 times:
#                     spawn 1 of armor stand at {_l}
#                     set {_a} to last spawned armor stand
#                     add nbt from "{Small:1b,Invisible:1b,Invulnerable:1b}" to nbt of {_a}
#                     set helmet of {_a} to nether quartz ore, red glazed terracotta block, crimson nylium, netherrack block, nether wart block, redstone block or crimson hyphae#, living fire coral block or huge red mushroom block
#                     add {_a} to {_不死::*}
#             if loop-counter > 100:
#                 teleport {_不死} at {_e}
#                 loop {_不死::*}:
#                     push loop-value-2 (vector between loop-value-2 and {_e}'s head) at speed 0.5 if chance of 50%
#                 execute console command "/effect give %{_e}% minecraft:regeneration 1 100 true" if mod(loop-counter,6) is 1
#                 execute console command "/playsound block.lava.pop master @a %Loc({_e})% 0.3 %random number between 0 and 1%"
#                 execute console command "/playsound minecraft:item.bucket.fill_lava master @a %Loc({_e})% 0.5 0" if chance of 10%
#             if loop-counter = 140:
#                 spawn 1 of skeleton at {_e}
#                 set {_不死} to last spawned skeleton
#                 clear {_不死}'s tool
#                 unequip {_不死}'s armor
#                 add nbt from "{NoAI:1b,Invulnerable:1b}" to nbt of {_不死}
#             apply potion of invisibility tier 10 without particles to {_e} for 2 tick
#         execute console command "/particle dust{color:[1.0,0.1,0.1],scale:3} %Loc({_e})% 1 1 1 0.16 100 force @a"
#         execute console command "/playsound minecraft:entity.generic.splash master @a %Loc({_e})% 0.6 1.5"
#         execute console command "/effect clear %{_e}% minecraft:regeneration"
#         execute console command "/effect clear %{_e}% minecraft:invisibility"
#         teleport {_不死} at location(0,-999,0)
#         remove {_e} from {不死::*}
#         kill {_不死::*}
#         kill {_不死}
# #     if attacker is (bee or spider or cavespider or silverfish):
# #         Own(victim,"蟲","INVENTORY") is true
# #         cancel event
# #     if attacker's helmet is zombie head:
# #         Own(victim,"屍術","INVENTORY") is true
# #         cancel event
# #     if attacker is zombie:
# #         Own(victim,"屍術","INVENTORY") is true
# #         cancel event
#         #    else if {予言_%victim%} is "fall":
#         #        set {_damage} to 99999

# #ーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーー

# # スキル一覧
# on load:
#     wait a tick
#     clear {skill::*}
#     add "背信|常時　>>あらゆるシンボルの影響を無視　|常時　>>あらゆる状態異常がはやく解消　" to {_s::*}
#     add "軽量|右クリ>>前方にむかって大きくジャンプ　|常時　>>落下のダメージを受けなくなる　" to {_s::*}
#     add "貫通|右クリ>>うすい壁面や天井をすり抜ける　|常時　>>窒息のダメージを受けなくなる　" to {_s::*}
#     add "停止|右クリ>>しばらく時の流れを静止させる　|常時　>>時が止まっても自由にうごける　" to {_s::*}
#     add   "黒|右クリ>>しばらく周囲の物体を引寄せる　|常時　>>異常な重力場は不規則にうごく　" to {_s::*}
#     # add "爆破|破壊　>>壊したブロックを爆弾に変える|右クリ>>爆弾にしたブロックを点火する" to {_s::*}

    


#     # add "不死|所持　>>死亡するとその地点で復活する|所持　>>仮死状態でアイテムを保持する" to {_s::*}
#     # add "小人|右クリ>>身体が縮小したり戻ったりする|所持　>>体力と最大体力の比率はおなじ" to {_s::*}
#     # add "稲妻|右クリ>>前方にむかって破壊光線を放つ|所持　>>電圧のダメージを受けなくなる" to {_s::*}
#     # add "魅了|右クリ>>目が離せない芸術品を召喚する|所持　>>生物によっては思考が停止する" to {_s::*}
#     # # add "牙|右クリ>>巨大な鰐になって地中をうごく" to {_s::*}
#     # add "耳|シフト>>音だけで正確に居場所がわかる" to {_s::*}
#     # add "彗星|右クリ>>爆撃地点をきめて隕石をおとす" to {_s::*}
#     # # add "迷彩|右クリ>>しばらく透明化しすがたを消す|被ダメ>>ステルス状態が強制解除される" to {_s::*}
#     # add "禁忌|右クリ>>読むとソレに追われる紙をだす|所持　>>その呪われる紙を拾わなくなる" to {_s::*}
#     # add "消滅|右クリ>>しばらく周囲の全てを飲みこむ|所持　>>発動中は周囲の様子がみえない" to {_s::*}
#     # # add "巻戻|右クリ>>しばらく前の時間をやりなおす|所持　>>落下のダメージを受けなくなる" to {_s::*}
#     # # add "腫瘍|右クリ>>生物の体内で刃物をつくりだす|所持　>>最も近い生物にだけ発動される" to {_s::*}
#     # add "大盾|シフト>>ブロックで装甲を形成する" to {_s::*}
#     # add "経過|右クリ>>しばらく認識されず無敵化|所有　>>次のダメージを自動で躱す" to {_s::*}
#     # add "双対|シフト>>目先にいる物体を捕捉する|右クリ>>補足した物体と位置を交換" to {_s::*}
#     # # add "屍術|右クリ>>ゾンビをつくりだして使役する|所持　>>死骸があればプレイヤーを蘇生" to {_s::*}
#     # add "重力|右クリ>>前方にいる物体をキャッチする|左クリ>>キャッチした物体をふっとばす" to {_s::*} #  80s 15回 弓と同じ
#     loop {_s::*}:
#         set {_a::*} to loop-value split at "|"
#         set {_a} to enchanted_book named "<#FFF6EE>%{_a::1}%のシンボル"
#         set string tag "skill" of custom nbt of {_a} to {_a::1}
#         loop (size of {_a::*} -1) times:
#             set {_b::*} to {_a::%loop-iteration-2 + 1%} split at ">>"
#             set line (loop-iteration-2) of {_a}'s lore to "<#DC9F95>%{_b::1}% <#664B4F>>> &8%{_b::2}%"
#         add {_a} to {skill::*}

# # 管理者メニュー、ゲーム処理、特殊ダメージ処理、DeathEffect(true)、巻戻のシンボルは後回し
# # 意味のある最小単位ならwait 1 tick、バッファとしての値ならwait a tick
# # {spec::*}は参加判定のみ、ターゲット判別とスキル条件はspectatorにしろ
# # loopは 秒数 * 20 times
# # entity sectionは活用してこう　%{_a::3} if {_a::3} is set else sender%

# # アクティブスキル
# on right click with enchanted_book:
#     stop if {game} isn't set
#     stop if size of {停止::*} > 0
#     stop if {_p}'s gamemode is spectator

#     if true is Own(player,"軽量"):
#         Ready(player, 25 seconds) is true
#         #
#         set velocity of player to vector(0,0.1,0)
#         push player forwards at speed 1.33
#         execute console command "/particle minecraft:cloud %Loc(player)% 0 0 0 0.2 3 force @a"
#         execute console command "/particle minecraft:cloud %Loc(player)% 0 0 0 0.03 3 force @a"
#         execute console command "/playsound minecraft:ui.toast.out master @a %Loc(player)% 2 1"
#         execute console command "/playsound minecraft:entity.ender_dragon.flap master @a %Loc(player)% 0.3 2"

#     else if true is Own(player,"貫通"):
#         set {_loc} to location 1.2 meter in front of player's head
#         set {_loc} to location 0.5 meter under {_loc} if player is sneaking
#         block at {_loc} isn't passable
#         loop 10 times:
#             set {_loc} to location 0.3 meter in front of {_loc}
#             block at {_loc} is passable
#             block under {_loc} is passable
#             Ready(player, 15 seconds) is true
#             #
#             teleport player at location 0.99 meter under {_loc}
#             execute console command "/particle crit %Loc(player)% 0.5 0.5 0.5 0.1 10 force @a"
#             execute console command "/playsound minecraft:item.armor.equip_netherite master @a %Loc(player)% 0.3 0"
#             execute console command "/playsound minecraft:entity.player.hurt_freeze master @a %Loc(player)% 0.4 0.6"
#             stop

#     else if true is Own(player,"停止"):
#         Ready(player, 100 seconds) is true
#         #
#         add player to {停止::*}
#         hide player from all players
#         set server frozen state to true
#         add all players where [gamemode of input is spectator] to {停止::*}
#         add all players where [Own(input,"背信","INVENTORY") is true] to {停止::*}
#         execute console command "/playsound minecraft:entity.wither.death master @a %Loc(player)% 0.2 0 0.1"
#         execute console command "/playsound minecraft:item.mace.smash_ground_heavy master @a %Loc(player)% 0.6 0 0.4"
#         apply potion of blindness tier 255 without particles whilst hiding icon to all players for 1 second replacing existing effect
#         loop 4 * 20 times:
#             # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
#             wait a tick
#             if any:
#                 {game} isn't set
#                 player's gamemode is spectator
#             then:
#                 stop loop
#             Ready(player, 100 seconds,"RESET")
#             # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
#             close inventory of all players
#             apply potion of darkness tier 255 without particles whilst hiding icon to all players where [{停止::*} contain input] for 0.3 second replacing existing effect
#             apply potion of blindness tier 255 without particles whilst hiding icon to all players where [{停止::*} don't contain input] for 2 second replacing existing effect
#             if loop-iteration = 4 * 20:
#                 reveal player from all players
#                 set server frozen state to false
#                 execute console command "/playsound minecraft:block.vault.break master @a %Loc(player)% 0.3 0 0.2"
#                 execute console command "/playsound minecraft:item.crossbow.quick_charge_3 master @a %Loc(player)% 0.6 0 0.4"
#                 apply potion of blindness tier 255 without particles whilst hiding icon to all players for 0.3 second replacing existing effect
#         clear {停止::*}


#     else if true is Own(player,"黒"):
#         Ready(player, 80 seconds) is true
#         #
#         make player shoot allay at speed 2:
#             set {_超球::1} to entity
#             make entity silent
#             make entity invisible
#             make entity invulnerable
#             set scale attribute of entity to 3
#         spawn text display at {_超球::1}:
#             set {_超球::2} to entity
#             set opacity of the entity to -200
#             set entity's display text to "&0❍"
#             set display billboard of entity to center
#             set display scale of entity to vector(0.06,0.06,0.06)
#             set display text background color of entity to bukkitColor(0,100,0,50)
#         execute console command "/playsound minecraft:entity.horse.ambient master @a %Loc({_超球::1})% 0.6 0 0.2"
#         loop 20 * 20 times:
#             # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
#             wait a tick
#             while size of {停止::*} > 0:
#                 wait a tick
#             if any:
#                 {game} isn't set
#                 player's gamemode is spectator
#             then:
#                 stop loop
#             Ready(player, 80 seconds,"RESET")
#             # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
#             execute console command "/playsound minecraft:ambient.crimson_forest.mood master @a %Loc({_超球::1})% 0.2 2" if chance of 10%
#             teleport {_超球::2} at {_超球::1}
#             if loop-iteration > 19 * 20:
#                 set display scale of {_超球::2} to display scale of {_超球::2} * 0.9
#             else if loop-iteration < 1 * 20:
#                 set display scale of {_超球::2} to display scale of {_超球::2} * 1.3
#             else:
#                 loop all entities in radius 7 around {_超球::1}:
#                     gamemode of loop-entity isn't spectator
#                     Own(loop-entity,"背信","INVENTORY") is false
#                     push loop-entity towards {_超球::1} at speed 0.1
#                 loop all blocks in radius 10 around {_超球::1} where [input isn't air]:
#                     chance of 0.03%
#                     block above loop-block is air
#                     le spawn falling (blockdata of loop-block) at loop-block
#                     push last spawned entity vector(0,random number between 0.01 and 0.3,0)
#                     set gravity of last spawned entity to false
#                     set block at location of loop-block to air
#         teleport {_超球::*} at location(0,-999,0)
#         kill {_超球::*}













        # execute console command "/playsound minecraft:block.iron_door.open master @a[name=!%player%] %Loc({爆破::%player%})% 0.8 1.6"
        # execute console command "/playsound minecraft:entity.creeper.primed master @a %Loc({爆破::%player%})% 0.5 1.3"
        # execute console command "/playsound minecraft:block.iron_door.open master %player% %Loc(player)% 0.6 2"
        # set {_爆破} to {爆破::%player%}
        # loop 1 * 20 times:
        #     # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
        #     wait a tick
        #     while size of {停止::*} > 0:
        #         wait a tick
        #     if any:
        #         {game} isn't set
        #         player's gamemode is spectator
        #         block at {_爆破} isn't {爆破::%player%}
        #     then:
        #         stop
        #     Ready(player, 80 seconds,"RESET")
        #     # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
        #     execute console command "/particle minecraft:dripping_lava %Loc({_爆破})% 1 1 1 0.05 3 force @a"
        #     execute console command "/particle dust{color:[0.77,0.0,0.0],scale:2} %Loc({_爆破})% 1 1 1 1 2 force @a"
        #     if loop-iteration = 1 * 20:
        #         execute console command "/particle minecraft:lava %Loc({_爆破})% 1.5 1.5 1.5 0 20 force @a"
        #         loop 3 times:
        #             execute console command "/summon tnt %Loc({_爆破})% {fuse:0s}"





    # else if true is Own(player,"爆破"):
    #     Ready(player, 80 seconds) is true
    #     #
    #     execute console command "/playsound minecraft:block.iron_door.open master @a[name=!%player%] %Loc({爆破::%player%})% 0.8 1.6"
    #     execute console command "/playsound minecraft:entity.creeper.primed master @a %Loc({爆破::%player%})% 0.5 1.3"
    #     execute console command "/playsound minecraft:block.iron_door.open master %player% %Loc(player)% 0.6 2"
    #     set {_爆破} to {爆破::%player%}
    #     loop 1 * 20 times:
    #         # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    #         wait a tick
    #         while size of {停止::*} > 0:
    #             wait a tick
    #         if any:
    #             {game} isn't set
    #             player's gamemode is spectator
    #             block at {_爆破} isn't {爆破::%player%}
    #         then:
    #             stop
    #         Ready(player, 80 seconds,"RESET")
    #         # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    #         execute console command "/particle minecraft:dripping_lava %Loc({_爆破})% 1 1 1 0.05 3 force @a"
    #         execute console command "/particle dust{color:[0.77,0.0,0.0],scale:2} %Loc({_爆破})% 1 1 1 1 2 force @a"
    #         if loop-iteration = 1 * 20:
    #             execute console command "/particle minecraft:lava %Loc({_爆破})% 1.5 1.5 1.5 0 20 force @a"
    #             loop 3 times:
    #                 execute console command "/summon tnt %Loc({_爆破})% {fuse:0s}"
    #             clear {爆破::%player%}


    # else if true is Own(player,"重力"):
    #     # loop living entities:
    #     #     loop-entity isn't player
    #     #     loop-entity's gamemode isn't spectator
    #     #     Own(loop-entity,"背信","INVENTORY") is false
    #     set {_重力} to target entity ignoring blocks with ray size 2
    #     {_重力} is an entity 
    #     Ready(player, 80 seconds) is true
    #     apply potion of levitation tier 255 without particles whilst hiding icon to {_重力} for 5.3 second replacing existing effect
    #     #
        
# #             distance between player and loop-entity < 100
# #             add loop-entity to {_t::*}
# #         set {_t} to Look({_t::*},player)
# #         {_t} is set
# #         player is ready for 40 seconds
# #         apply potion of levitation tier 3 to {_t} for 2 seconds
# #         execute console command "/particle minecraft:sonic_boom %Loc({_t})% 0 0 0 1 1 force @a"
# #         execute console command "/playsound minecraft:entity.breeze.inhale master @a %Loc({_t})% 0.3 0"
# #         execute console command "/playsound minecraft:block.sculk.charge master @a %Loc(player)% 1 0.7"
# #         execute console command "/playsound minecraft:block.soul_sand.break master @a %Loc(player)% 0.3 0"
# #         loop 1.7*20 times:
# #             # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# #             wait a tick
# #             if any:
# #                 {game} isn't set
# #                 Has({play::*},player) is false
# #                 {_t} is dead
# #             then:
# #                 stop
# #             while size of {停止::*} > 0:
# #                 wait a tick
# #             cooldown of player to 40 second
# #             # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# #         set velocity of {_t} to vector(0,0,0)
# #         push {_t} in direction of player at speed 1.2
# #         execute console command "/particle minecraft:gust %Loc({_t})% 0 0 0 1 1 force @a"
# #         execute console command "/particle minecraft:warped_spore %Loc({_t})% 0 0 0 1 32 force @a"
# #         execute console command "/playsound minecraft:entity.breeze.shoot master @a %Loc({_t})% 1 0.7"
# #         push {_t} upwards at speed 0.05
# #         loop 1*20 times:
# #             # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# #             wait a tick
# #             if any:
# #                 {game} isn't set
# #                 Has({play::*},player) is false
# #                 {_t} is dead
# #             then:
# #                 stop
# #             while size of {停止::*} > 0:
# #                 wait a tick
# #             cooldown of player to 40 second
# #             # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# # #            set {_abs} to vector length of velocity of {_t}
# # #            set {_max} to {_abs} if {_max} < {_abs}
# #         set velocity of {_t} to vector(0,0,0)
# #         push {_t} in direction of player at speed 1.2
# #         execute console command "/particle minecraft:gust %Loc({_t})% 0 0 0 1 1 force @a"
# #         execute console command "/particle minecraft:warped_spore %Loc({_t})% 0 0 0 1 32 force @a"
# #         execute console command "/playsound minecraft:entity.breeze.shoot master @a %Loc({_t})% 1 0.7"
# #         push {_t} upwards at speed 0.05

    #     add player to {重力::*}
    #     set {_重力} to vector in direction of player * 0.4
    #     add all players where [gamemode of input is spectator] to {重力::*}
    #     add all players where [Own(input,"背信","INVENTORY") is true] to {重力::*}
    #     # execute console command "/playsound minecraft:entity.wither.death master @a %Loc(player)% 0.2 0 0.1"
    #     # execute console command "/playsound minecraft:item.mace.smash_ground_heavy master @a %Loc(player)% 0.6 0 0.4"
    #     apply potion of blindness tier 255 without particles whilst hiding icon to all players for 1 second replacing existing effect
    #     loop 10 * 20 times:
    #         # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    #         wait a tick
    #         while size of {停止::*} > 0:
    #             wait a tick
    #         if any:
    #             {game} isn't set
    #             player's gamemode is spectator
    #         then:
    #             stop
    #         Ready(player, 100 seconds,"RESET")
    #         # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    #         push all entities {_重力} * 0.21
    #         execute console command "/particle minecraft:white_smoke %Loc(random element out of all entities)% %x of {_重力}% %y of {_重力}% %z of {_重力}% 1 0 force @a"
    #         execute console command "/particle minecraft:white_ash %Loc(player)% 20 20 20 0 100 force @a"
    #         # apply potion of darkness tier 255 without particles whilst hiding icon to all players where [{停止::*} contain input] for 0.3 second replacing existing effect
    #         # apply potion of blindness tier 255 without particles whilst hiding icon to all players where [{停止::*} don't contain input] for 2 second replacing existing effect
    #         if loop-iteration = 10 * 20:
    #             clear {重力::*}
    #             # execute console command "/playsound minecraft:block.vault.break master @a %Loc(player)% 0.3 0 0.2"
    #             # execute console command "/playsound minecraft:item.crossbow.quick_charge_3 master @a %Loc(player)% 0.6 0 0.4"
    #             apply potion of blindness tier 255 without particles whilst hiding icon to all players for 0.3 second replacing existing effect

#     else if Own(player,"稲妻") is true:
#         Ready(player, 60 seconds) is true
#         # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
#         set {_dir} to vector in direction of player
#         set {_loc} to location of player's head
#         loop 130 times:
#             # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
#             wait 1 tick
#             while size of {停止::*} > 0:
#                 wait a tick
#             if any:
#                 {game} isn't set
#                 {spec::*} contain player
#                 gamemode of player is spectator
#             then:
#                 stop loop
#             Ready(player, 60 seconds,"RESET")
#             # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
#             if loop-counter < 100:
#                 execute console command "/playsound minecraft:block.nether_sprouts.fall master @a %Loc({_loc})% 0.3 %loop-counter /50% 0.2"
#                 execute console command "/particle minecraft:sonic_boom %Loc({_loc})% 0 0 0 0 1 force @a" if chance of (loop-counter)*0.01
#                 execute console command "/playsound minecraft:entity.breeze.idle_air master @a %Loc({_loc})% 0.3 %loop-counter/50% 0.2"
#                 execute console command "/playsound minecraft:entity.breeze.charge master @a %Loc({_loc})% 0.2 %loop-counter/50% 0.2"
#             else if loop-counter = 100:
#                 execute console command "/playsound minecraft:entity.warden.sonic_boom master @a %Loc({_loc})% 0.9 0 0.5"
#                 execute console command "/playsound minecraft:item.trident.thunder master @a %Loc({_loc})% 0.6 1.2 0.7"
#                 loop 4 times:
#                     add 1 to {_n}
#                     spawn block display at {_loc}:
#                         rotate entity around z axis by ({_n}*90) degrees
#                         set display block data of entity to light_blue_stained_glass
#                         set display brightness of entity to displayBrightness(10,10)
#                         set display view range of entity to 999
#                         add entity to {_a::*}
#             else:
#                 set {_xy} to (131 - loop-counter)/12
#                 rotate {_a::*} around z axis by (40) degrees
#                 set display scale of {_a::*} to vector({_xy},{_xy},1000)
#                 execute console command "/particle minecraft:flash %Loc({_loc})% 0.3 0.3 0.3 0 1 force @a"
#                 loop living entities:
#                     Own(loop-entity,"背信","INVENTORY") isn't true
#                     loop-entity's gamemode isn't spectator
#                     set {_rel} to vector between {_loc} and loop-entity's head
#                     ({_rel} cross {_dir})'s vector length < 3
#                     {_rel} dot {_dir} > 0
#                     strike lightning at the loop-entity
#         execute console command "/playsound minecraft:block.beacon.deactivate master @a %Loc({_loc})% 0.6 0.7 0.1"
#         kill {_a::*}


#     else if Own(player,"小人") is true:
#         Ready(player, 15 seconds) is true
#         # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
#         set {_shrink} to true if {小人::*} don't contain player
#         loop 50 times:
#             # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
#             wait 1 tick
#             while size of {停止::*} > 0:
#                 wait a tick
#             if any:
#                 {game} isn't set
#                 {spec::*} contain player
#                 gamemode of player is spectator
#             then:
#                 stop loop
#             Ready(player, 15 seconds,"RESET")
#             # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
#             if {_shrink} is true:
#                 if loop-counter = 1:
#                     add player to {小人::*}
#                     set scale attribute of player to 1
#                     set block interaction range attribute of player to 2.5
#                     set entity interaction range attribute of player to 2.5
#                     set health of player to health of player *(4/10)
#                     set max health of player to max health of player *(4/10)
#                     execute console command "/playsound minecraft:entity.turtle.egg_hatch master @a %Loc(player)% 0.3 0"
#                     apply infinite potion of jump boost tier 2 without particles whilst hiding icon to player replacing existing effect
#                 set scale attribute of player to (1 - (0.0145 * loop-counter))
#             else:
#                 if loop-counter = 1:
#                     remove player from {小人::*}
#                     set scale attribute of player to 0.25
#                     set entity interaction range attribute of player to 3
#                     set block interaction range attribute of player to 4.5
#                     set max health of player to max health of player *(10/4)
#                     set health of player to health of player *(10/4)
#                     execute console command "/playsound minecraft:entity.turtle.egg_hatch master @a %Loc(player)% 0.3 0.8"
#                     remove jump boost from player
#                 set scale attribute of player to (0.02 * loop-counter)

#     else if Own(player,"魅了") is true:
#         Ready(player, 80 seconds) is true
#         # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
#         spawn ender eye at location 2 meter in front of player's head
#         set {_e} to location 0.7 meter above last spawned ender eye
#         execute console command "/playsound minecraft:music_disc.5 master @a %Loc({_e})% 0.4 2"
#         execute console command "/playsound minecraft:entity.creaking.twitch master @a %Loc({_e})% 0.5 0.7"
#         execute console command "/playsound minecraft:entity.skeleton.converted_to_stray master @a %Loc({_e})% 0.5 0"
#         execute console command "/particle block_marker{block_state:{Name:nether_portal}} %Loc({_e})% 0 0 0 0 1 force @a"
#         loop 200 times:
#             # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
#             wait 1 tick
#             while size of {停止::*} > 0:
#                 wait a tick
#             if any:
#                 {game} isn't set
#                 {spec::*} contain player
#                 gamemode of player is spectator
#             then:
#                 stop loop
#             Ready(player, 80 seconds,"RESET")
#             # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
#             loop living entities:
#                 loop-entity isn't player
#                 loop-entity has line of sight to {_e}
#                 loop-entity's gamemode isn't spectator
#                 Own(loop-entity,"背信","INVENTORY") isn't true
#                 apply potion of weakness tier 3 without particles whilst hiding icon to loop-value-2 for 0.3 seconds replacing existing effect
#                 apply potion of slowness tier 3 without particles whilst hiding icon to loop-value-2 for 0.3 seconds replacing existing effect
#                 if loop-entity is a player:
#                     (vector in direction of loop-entity) dot (vector between loop-entity and {_e}) > 0
#                     set {_loc} to location 10 meter in front of loop-entity
#                     set {_loc} to {_loc} offset by (vector between {_loc} and (location 1.5 meter under {_e}))/8
#                     apply potion of blindness tier 255 without particles whilst hiding icon to loop-value-2 for 0.3 seconds replacing existing effect
#                     force loop-entity look at location of {_loc}
#                 else:
#                     force loop-entity look at location of {_e}
#             if loop-counter < 10*20 - 4*20:
#                 execute console command "/particle block_marker{block_state:{Name:black_concrete}} %Loc({_e})% 0.3 0.4 0.3 0 1 force @a"
#         execute console command "/stopsound @a master minecraft:music_disc.5"



#     else if Own(player,"迷彩") is true:
#         Ready(player, 25 seconds) is true
#         # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
#         set {_hp} to health of player
#         execute console command "/playsound minecraft:item.armor.equip_leather master @a %Loc(player)% 1 2"
#         # 
#         loop 300 times:
#             # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
#             wait 1 tick
#             while size of {停止::*} > 0:
#                 wait a tick
#             if any:
#                 {game} isn't set
#                 {spec::*} contain player
#                 gamemode of player is spectator
#             then:
#                 stop loop
#             Ready(player, 25 seconds,"RESET")
#             # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
#             set arrows stuck in player to 0
#             create debug marker at player with color white with alpha 2 with text "" for all players for 1 seconds
#             create debug marker at player's head with color white with alpha 2 with text "" for all players for 1 seconds

#         execute console command "/playsound minecraft:block.beacon.deactivate master @a %Loc({_loc})% 0.6 0.7 0.1"
#         kill {_a::*}
#     #     
#     #     if {_health} > health of player:
#     #         stop loop
#     #     else if {_health} < health of player:
#     #         set {_health} to health of player
#     #     execute console command "/particle minecraft:ash %Loc(player)% 3 3 3 0 1 force @a"
#     #     execute console command "/effect give %player% minecraft:invisibility 1 1 true"
#     # execute console command "/effect clear %player% minecraft:invisibility"
#     # execute console command "/playsound minecraft:block.rooted_dirt.fall master @a %Loc(player)% 1 2"
#     # set {_l} to location 0.9 meter above player
#     # stop if {game} isn't set
#     # loop 10 times:
#     #     spawn text display at {_l}:
#     #         add display to {_迷彩::*}
#     #         set display' display text to "　"
#     #         make display visible through blocks
#     #         set display billboard of display to center
#     #         set display scale of display to vector(3,3,3)
#     #         set transformation translation of display to random vector * 2
#     # wait a tick
#     # kill {_迷彩::*}





#     if Own(player,"消滅") is true:
#         Ready(player, 100 seconds) is true
#         set {_gm} to player's gamemode
#         execute console command "/playsound minecraft:entity.blaze.shoot master @a %Loc(player)% 0.5 0"
#         loop 69 times:
#             # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
#             wait 1 tick
#             while size of {停止::*} > 0:
#                 wait a tick
#             if any:
#                 {game} isn't set
#                 {spec::*} contain player
#             then:
#                 stop
#             Ready(player, 100 seconds, "RESET")
#             # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
#             if loop-counter < 20:
#                 execute console command "/effect give %player% minecraft:slowness 2 3 true"
#                 execute console command "/particle ash %Loc(player)% 1.5 1.5 1.5 1 20 force @a"
#             else if loop-counter < 40:
#                 execute console command "/effect give %player% minecraft:darkness 2 3 true"
#                 execute console command "/playsound minecraft:entity.hoglin.angry master @a %Loc(player)% 0.2 0"
#             else:
#                 execute console command "/effect give %player% minecraft:blindness 1 3 true"
#                 execute console command "/particle minecraft:explosion %Loc(player)% 0 0 0 1 1 force @a"
#                 execute console command "/particle minecraft:squid_ink %Loc(player)% 1 1 1 0 10 force @a"
#                 execute console command "/playsound minecraft:entity.ender_dragon.hurt master @a %Loc(player)% 0.3 0.5"
#                 set player's gamemode to spectator
#                 set player's fly speed to 0.22
#                 loop blocks in radius 2.1 around player:
#                     set loop-block to air
#                 loop entities in radius 2.3 around player:
#                     loop-entity's gamemode isn't spectator
#                     Own(loop-entity,"消滅","INVENTORY") isn't true
#                     Own(loop-entity,"背信","INVENTORY") isn't true
#                     clear all items in loop-entity's inventory
#                     teleport loop-entity at location(0,-999,0)
#                     damage loop-entity by 999 hearts
#         set player's gamemode to {_gm}
#         set player's fly speed to 0.1

#     if Own(player,"禁忌") is true:
#         Ready(player, 100 seconds) is true
#         drop 1 of paper named "&4" at player's head
#         set {_a} to last dropped item
#         push {_a} towards (location 2 meter in front of player's head) at speed 0.2
#         execute console command "/particle minecraft:enchant %Loc(player)% 0.6 0.6 0.6 2 60 force @a"
#         execute console command "/playsound minecraft:entity.allay.ambient_without_item master @a %Loc({_a})% 1 2"

# # falling sand と push towards の二つがエラってる
#     # if Own(player,"彗星") is true:
#     #     Ready(player, 120 seconds) is true
#     #     set {_gm} to gamemode of player
#     #     set {_loc} to location of player
#     #     set gamemode of player to spectator
#     #     set flight state of player to false
#     #     teleport player at location(x-loc of player,300,z-loc of player,world of player,yaw of player,90)
#     #     execute console command "/playsound minecraft:entity.wither.death master @a %Loc(player)% 0.2 0.6"
#     #     spawn 1 of armor stand at player:
#     #         add nbt from "{Invulnerable:1b}" to nbt of entity
#     #         hide entity from all players
#     #         set {_彗星} to entity
#     #     loop 160 times:
#     #         # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
#     #         wait 1 tick
#     #         while size of {停止::*} > 0:
#     #             wait a tick
#     #         if any:
#     #             {game} isn't set
#     #             {spec::*} contain player
#     #         then:
#     #             stop loop
#     #         Ready(player, 100 seconds, "RESET")
#     #         # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
#     #         if {_彗星} is on ground:
#     #             set {_bomb} to true
#     #             stop loop
#     #         execute console command "/playsound minecraft:entity.phantom.ambient master @a %Loc(player)% 0.5 0 0.2" if chance of 30%
#     #         execute console command "/particle minecraft:campfire_cosy_smoke %Loc(player)% 0 0 0 0.05 2 force @a"
#     #         execute console command "/particle minecraft:explosion %Loc(player)% 0 0 0 1 1 force @a"
#     #         execute console command "/particle minecraft:lava %Loc(player)% 0 1 0 0 2 force @a"
#     #         set {_v} to vector in horizontal direction of player
#     #         execute console command "/tp %player% %Loc({_彗星})%"
#     #         push {_彗星} {_v} at speed (161 - loop-counter)/3000
#     #     set fall distance of player to 0
#     #     set gamemode of player to {_gm}
#     #     teleport player at {_loc}
#     #     if {_bomb} is true:
#     #         loop blocks in radius 3 around {_彗星}:
#     #             spawn undroppable falling block of (loop-block) at (loop-block)
#     #             push last spawned entity upwards at speed (random number between 0.6 and 1)
#     #             push last spawned entity direction from {_彗星} to last spawned entity at speed (random number between 0.2 and 0.6)
#     #         create an explosion of force 13 at {_彗星}
#     #         execute console command "/particle minecraft:lava %Loc({_彗星})% 2 2 2 0.5 40 force @a"
#     #         execute console command "/particle minecraft:explosion %Loc({_彗星})% 0 0 0 10 30 force @a"
#     #         execute console command "/particle minecraft:large_smoke %Loc({_彗星})% 3 3 3 0.5 80 force @a"
#     #         execute console command "/particle minecraft:campfire_cosy_smoke %Loc({_彗星})% 2 3 2 0.05 50 force @a"
#     #         execute console command "/particle minecraft:campfire_cosy_smoke %Loc({_彗星})% 8 9 8 0.05 20 force @a"
#     #         execute console command "/particle minecraft:campfire_cosy_smoke %Loc({_彗星})% 6 7 6 0.05 50 force @a"
#     #         execute console command "/particle minecraft:campfire_cosy_smoke %Loc({_彗星})% 4 5 4 0.05 70 force @a"
#     #         execute console command "/particle minecraft:campfire_cosy_smoke %Loc({_彗星})% 10 10 10 0.05 90 force @a"
#     #         loop 4 times:
#     #             execute console command "/playsound minecraft:entity.lightning_bolt.impact master @a %Loc({_彗星})% 0.3 %loop-counter-2 *0.5% 0.1"

#     if Own(player,"腫瘍") is true:

#         loop reversed living entities sorted by distance from player:
#             Own(loop-entity,"背信","INVENTORY") isn't true
#             distance between loop-entity and player < 10
#             loop-entity's gamemode isn't spectator
#             loop-entity is not player
#             set {_t} to loop-entity
#         stop if {_t} is not set
#         Ready(player, 120 seconds) is true
#         set max health of {_t} to max health of {_t} -2
#         loop blocks in radius 2 around {_t}:
#             block at location of loop-block is air
#             block under loop-block isn't air or redstone wire
#             set the loop-block to redstone wire if chance of 30%
#         execute console command "/effect give %{_t}% minecraft:blindness 1 255 true"
#         execute console command "/playsound minecraft:entity.camel.eat master @a %Loc({_t})% 1 0"
#         execute console command "/playsound minecraft:block.piston.contract master @a %Loc({_t})% 0.5 0"
#         execute console command "/particle minecraft:landing_lava %Loc({_t},0.5)% 0.8 0.8 0.8 0.1 20 force @a"
#         execute console command "/particle minecraft:item{item:""redstone""} %Loc({_t},0.5)% 0 0 0 0.1 30 force @a"
#         damage {_t} by 2 hearts

# # スライディングとか、いろいろ！！！ね？あえて無関係なここにかいてる、あと殻、フリーズエフェクトとか、ダウンロードフォルダみてね

#     if Own(player,"巻戻") is true:


#         Ready(player, 100 seconds)
#     #     execute console command "/effect give %player% minecraft:blindness 1 10 true"
#         set {_map} to a new cuboid region from location(-300,-64,-300) to location(300,319,300)

#         save {_map} as a schematic named "makimodoshi":
#             copy entities: false
#             copy biomes: false
#             # mask: mask from "stone,red_wool,blue_wool"
#             # origin: location of (first element out of all players)
#             remove entities: false
#             overwrite: true

#         loop 35 times:
#             send "%36 - loop-counter%" to ops
#             wait a second


#         paste schematic named "makimodoshi" at location(-70,100,-70):
#             paste entities: false
#             paste biomes: true
#             ignore air: false            
#     #     loop all players:
#     #         if {play::*} contain loop-player:
#     #             add loop-player to {_play::*}
#     #             set {_play_hp::%loop-player%} to health of loop-player
#     #             set {_play_lc::%loop-player%} to location of loop-player
#     #             set {_play_fd::%loop-player%} to food level of loop-player
#     #             loop 100 times:
#     #                 set {_play_iv_%loop-value-1%_%loop-counter-2%} to (slot loop-counter-2 of loop-value-1's inventory)
#     #         else:
#     #             add loop-player to {_spec::*}
#     #     loop 10*20 times:
#     #         # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
#     #         wait a tick
#     #         if any:
#     #             {game} isn't set
#     #             {spec::*} contain player
#     #         then:
#     #             stop
#     #         Ready(player, 100 seconds, "RESET")
#     #         # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
#     #     execute console command "/playsound minecraft:block.trial_spawner.about_to_spawn_item master @a ~ ~ ~ 0.6 0.5 0.4"
#     #     execute console command "/playsound minecraft:music_disc.creator_music_box master @a ~ ~ ~ 0.6 0.1 0.2"
#     #     execute console command "/playsound minecraft:music_disc.creator_music_box master @a ~ ~ ~ 0.6 0.4 0.2"
#     #     execute console command "/playsound minecraft:music_disc.creator_music_box master @a ~ ~ ~ 0.6 0.8 0.2"
#     #     execute console command "/effect give @a minecraft:darkness 10 1 true"
#     #     set {巻戻} to now
#     #     loop 3*20 times:
#     #         # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
#     #         wait a tick
#     #         if any:
#     #             {game} isn't set
#     #             {spec::*} contain player
    #         then:
    #             stop
    #         Ready(player, 100 seconds, "RESET")
    #         # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

    #     loop entities:
    #         delete loop-entity if loop-entity isn't a player
    #     loop {_spec::*}:
    #         Reset(loop-value,"spec")
    #         clear loop-value-1's inventory
    #     loop {_play::*}:
    #         Reset(loop-value,"play")
    #         teleport loop-value at {_play_lc::%loop-value%}
    #         set health of loop-value to {_play_hp::%loop-value%}
    #         set food level of loop-value to {_play_fd::%loop-value%} 
    #         loop 100 times:
    #             set (slot loop-counter-2 of loop-value-1's inventory) to {_play_iv_%loop-value-1%_%loop-counter-2%}

    #     #データ消去
    #     execute console command "/effect clear %player% minecraft:darkness"
    #     execute console command "/effect give %player% minecraft:blindness 1 10 true"
    #     execute console command "/stopsound @a master minecraft:music_disc.creator_music_box"
    #     execute console command "/playsound minecraft:block.trial_spawner.detect_player master @a ~ ~ ~ 0.6 0 0.4"

# Every 10 second in "world":
#     set {巻戻::6::*} to {巻戻::5::*}


#     set {_map} to a new cuboid region from location(-300,-64,-300) to location(300,319,300)
#     save {region} as a schematic named "old_1" and overwrite existing


# delete schematic "old_1"

#             # paste schematic named "%{selected_map::1}%" at location(-70,100,-70):
#             #     paste entities: true
#             #     paste biomes: true
#             #     ignore air: true


# /playsound minecraft:entity.skeleton.converted_to_stray



        # loop 160 times:
        #     # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
        #     wait 1 tick
        #     while size of {停止::*} > 0:
        #         wait a tick
        #     if any:
        #         {game} isn't set
        #         {spec::*} contain player
        #     then:
        #         stop loop
        #     Ready(player, 100 seconds, "RESET")
        #     # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
        #     if {_彗星} is on ground:







#     if Own(player,"牙") is true:
#         Ready(player, 100 seconds) is true
#         execute console command "/particle minecraft:block{block_state:""dirt""} %Loc(player)% 0 1 0 0 20 force @a"
#         execute console command "/particle minecraft:block{block_state:""dirt""} %Loc(player)% 1 0 1 0 40 force @a"
#         execute console command "/playsound minecraft:entity.hoglin.converted_to_zombified master @a %Loc(player)% 0.6 0"
#         spawn horse at player:
#             add nbt from "{Silent:1b,Invulnerable:1b}" to nbt of entity
#             set scale attribute of entity to 1.1
#             hide entity from all players
#             set {_牙} to entity
#         set {_gm} to gamemode of player
#         set player's gamemode to spectator
#         loop 300 times:
#             # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
#             wait 1 tick
#             while size of {停止::*} > 0:
#                 wait a tick
#             if any:
#                 {game} isn't set
#                 {spec::*} contain player
#             then:
#                 stop loop
#             Ready(player, 100 seconds, "RESET")
#             # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
#             set {_b} to type of block under player
#             make 2 of block particle using ({_b}) at player
#             set {_dir} to vector in horizontal direction of player * 0.3
#             set y of {_dir} to -1.1
#             set velocity of {_牙} to {_dir}
#             execute console command "/tp %player% %Loc({_牙},0.2)%"
#             if loop-counter is 300:
#                 set player's gamemode to {_gm}
#                 push player upwards at speed 0.6
#                 play sound "ENTITY_RAVAGER_ROAR" seed 1 with volume 0.5 with pitch 1.5 for all players
#                 execute console command "/particle minecraft:block_crumble{block_state:""dirt""} %Loc(player)% 0.5 1 0.5 0 40 force @a"
#                 execute console command "/playsound minecraft:entity.creaking.attack master @a %Loc(player)% 0.5 0"
#             execute console command "/playsound minecraft:block.copper.break master @a %Loc(player)% 0.4 0"
#         kill {_牙}




#         # spawn 3 of experience orb at player's head
#         # execute console command "/playsound minecraft:entity.player.levelup master @a %Loc(player)% 0.2 2"

#     else if Own(player,"双対") is true:
#         player is sneaking
#         player is on ground
#         {双対::%player%} is set
#         Ready(player, 50 seconds)
#         set {_t} to {双対::%player%}
#         set {_loc} to location of {_t}
#         teleport {_t} at player
#         set pitch of {_loc} to pitch of player
#         set yaw of {_loc} to yaw of player
#         teleport player at {_loc}
#         execute console command "/effect give %{_t}% minecraft:blindness 1 1 true"
#         execute console command "/effect give %player% minecraft:blindness 1 1 true"
#         execute console command "/particle minecraft:flash %Loc({_t})  % 0 0 0 1 1 force @a"
#         execute console command "/particle minecraft:flash %Loc({_loc})% 0 0 0 1 1 force @a"
#         execute console command "/playsound minecraft:block.vault.eject_item master @a %Loc({_t})% 0.3 2"
#         execute console command "/playsound minecraft:block.vault.eject_item master @a %Loc({_loc})% 0.4 2"
#         execute console command "/particle minecraft:sculk_charge_pop %Loc({_t})  % 0 0 0 0.2 40 force @a"
#         execute console command "/particle minecraft:sculk_charge_pop %Loc({_loc})% 0 0 0 0.2 40 force @a"

# 

#     if Own(player,"経過") is true:
#         Ready(player, 100 seconds)
#         hide player from all players
#         # execute console command "/tick rate 10"
#         execute console command "/effect give %player% minecraft:blindness 1 10 true"
#         execute console command "/playsound minecraft:block.conduit.deactivate master %player% %Loc(player)% 0.3 2"
#         execute console command "/playsound minecraft:block.respawn_anchor.deplete master %player% %Loc(player)% 0.6 0"
#         set {_gamemode} to gamemode of player
#         set gamemode of player to spectator
#         add player to {経過::*}
#         loop 7*20 times:
#             # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
#             wait 1 tick
#             while size of {停止::*} > 0:
#                 wait a tick
#             if any:
#                 {game} isn't set
#                 player's gamemode isn't spectator
#             then:
#                 stop
#             Ready(player, 100 seconds, "RESET")
#             # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
#             execute console command "/effect give %player% minecraft:darkness 2 10 true"
#             execute console command "/effect give %player% minecraft:nausea 2 255 true" if mod(loop-counter,20) is 1
#             execute console command "/effect give %player% minecraft:night_vision 1 255 true" if mod(loop-counter,20) is 1
#             execute console command "/playsound minecraft:block.sculk.place master %player% ~ ~ ~ 0.4 0 0.4" if mod(loop-counter,10) is 1
#             set player's fly speed to 0.03
#         remove player from {経過::*}
#         reveal player from all players
#         set gamemode of player to {_gamemode}
#         # execute console command "/tick rate 20"
#         execute console command "/effect clear %player% minecraft:darkness"
#         execute console command "/effect give %player% minecraft:blindness 1 10 true"
#         execute console command "/playsound minecraft:entity.silverfish.hurt master %player% %Loc(player)% 0.3 1.5"
#         execute console command "/playsound minecraft:entity.player.hurt_sweet_berry_bush master %player% %Loc(player)% 0.4 1"


# # on sneak toggle:
#         # player.showDemoScreen()

#         # if player is sneaking:
#         #     set camera of player to entity with id (entity id of player)
#         # else:
#         #     set camera of player to entity with id (entity id of target)
#         # set skin of player to skin of "zombie"
#         # make player spin for 1 seconds

#         # fake multi block set (all blocks in radius 10 of player where [input is not air]) as dirt for player
#         # change vision of {_e} to enderman
#         # make target entity glow red for player
        

#         # change vision of player to enderman
#         # spawn fake falling block at %location% for %players% with id %number% with [block] %blockdata%
#         # fake player's health to 10
#         # fake item cooldown of %itemtype% for %players% for %integer% ticks
#         # fake %livingentity/number%['s] equipment slot %string% to %itemtype% for %players%
#         # set blocks from {_l1} to {_l2} to dirt fast
#         # replace [blocks] %blockdata% (from|within) %location% and %location% to %blockdata% fast
        
# # HAND
# # OFF_HAND
# # HEAD
# # CHEST
# # LEGS
# # FEET
#         # fake name of %player% to %string% with skin named %string% for %players%
#         # (send|make) %players% see %entities% as ghost [packet]



# #         size of {停止::*} > 0
        
        
        

# # #                     Has({play::*},player) is false
# # #                 then:
# # #                     stop
# # #                 while size of {停止::*} > 0:
# # #                     wait a tick
# # #                 cooldown of player to 15 second
# # #                 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# # #                 set scale attribute of player to (1 - (0.015 * loop-counter))
# # #         execute console command "/playsound minecraft:block.enchantment_table.use master @a %Loc(player)% 0.3 0"

# # #             execute console command "/particle minecraft:enchant %Loc(player)% 2 2 2 0.1 1 force @a"
# # #         
# # function Cloak(p:player):
# #     send "a" to ops

# # #     if Own(player,"河豚") is true:
# # #         player is ready for 50 seconds
# # #         loop 15 times:
# # #             # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# # #             wait a tick
# # #             if any:
# # #                 {game} isn't set
# # #                 Has({play::*},player) is false
# # #             then:
# # #                 stop
# # #             cooldown of player to 50 second
# # #             # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# # #             spawn a puffer fish at location 0.5 meters under location 1 meters in front of head of player
# # #             push last spawned puffer fish to the right at speed (random number between -1 and 1)
# # #             push last spawned puffer fish forwards at speed (random number between 0.5 and 1.5)
# #             push last spawned puffer fish upwards at speed (random number between -0.1 and 0.1)
# #             push player forward at speed -0.02

# #     if Own(player,"運命") is true:
# #         loop entities:
# #             loop-entity isn't player
# #             loop-entity is a mob or a player
# #             loop-entity's gamemode isn't spectator
# #             Own(loop-entity,"背信","INVENTORY") is false
# #             distance between player and loop-entity < 100
# #             add loop-entity to {_t::*}
# #         set {_t} to Look({_t::*},player)
# #         {_t} is set
# #         cooldown of enchanted book for player <= 0 tick
# #         if Has({運命::*},{_t}) is true:
# #             execute console command "/particle minecraft:witch %Loc({_t}'s head)% 0.2 0.2 0.2 0 10 force %player%"
# #             execute console command "/playsound minecraft:block.large_amethyst_bud.break master %player% %Loc(player)% 0.3 2"
# #             set cooldown of enchanted book for player to 1 second
# #             stop
# #         player is ready for 150 seconds
# #         execute console command "/effect give %player% blindness 1 1 true"
# #         execute console command "/effect give %player% ight_vision 1 1 true"
# #         execute console command "/particle minecraft:flash %Loc({_t})% 0 0 0 0 5 force %player%"
# #         #execute console command "/particle minecraft:elder_guardian %Loc({_t})% 1 1 1 0 10 force %player%"
# #         execute console command "/playsound minecraft:block.bell.use master %player% %Loc(player)% 0.1 0.3"
# #         execute console command "/playsound minecraft:block.bell.use master %player% %Loc(player)% 0.1 0.1"
# #         execute console command "/particle minecraft:sculk_soul %Loc({_t})% 0.2 0.6 0.2 0 30 force %player%"
# #         add {_t} to {運命::*}
# #         if size of {運命::*} > 3:
# #             set {運命::1} to {運命::2}
# #             set {運命::2} to {運命::3}
# #             set {運命::3} to {運命::4}
# #             clear {運命::4}
# #         set {_max} to 1
# #         loop {運命::*}:
# #             set {_max} to loop-value's health if loop-value's health > {_max}
# #             execute console command "/particle minecraft:damage_indicator %Loc(loop-value's head)% 0.2 0.2 0.2 0 4 force @a"
# #         loop {運命::*}:
# #             set loop-value's max health to {_max} if loop-value's max health < {_max}
# #             set loop-value's health to {_max}


# #     if Own(player,"相棒") is true:
# #         player is ready for 15 seconds
# #         execute console command "/particle minecraft:squid_ink %Loc({相棒_%player%})% 0.7 0.7 0.7 0 60 force @a"
# #         execute console command "/playsound minecraft:entity.skeleton_horse.death master @a %Loc(player)% 0.3 0.6"
# #         execute console command "/playsound minecraft:entity.wither.shoot master @a %Loc(player)% 0.3 1"
# #         teleport {相棒_%player%} at location(0,-100,0)
# #         make player dismount
# #         kill {相棒_%player%}
# #         spawn a skeleton horse at player
# #         set {相棒_%player%} to last spawned skeleton horse
# #         apply potion of swiftness tier 1 to {相棒_%player%} for 999 days
# #         equip {相棒_%player%} with saddle of curse of vanishing 1
# #         set max health of {相棒_%player%} to 1
# #         set health of {相棒_%player%} to 1
# #         make player ride {相棒_%player%}
# #         tame {相棒_%player%} to player
# #         wait 4 tick
# #         stop if {game} isn't set
# #         push {相棒_%player%} upwards at speed 0.2
# #         push {相棒_%player%} forwards at speed 1.3
# #         execute console command "/particle minecraft:squid_ink %Loc({相棒_%player%})% 0.7 0.7 0.7 0 60 force @a"


# #     if Own(player,"重力") is true:
# #         player is ready for 100 seconds
# #         #execute console command "/particle minecraft:witch %Loc(player,0.5)% 0 0 0 1 10 force @a"
# #         execute console command "/playsound minecraft:entity.illusioner.prepare_blindness master @a ~ ~ ~ 1 0 0.4"
# #         execute console command "/playsound minecraft:entity.elder_guardian.curse master @a ~ ~ ~ 1 0 0.2"
# #         if pitch of player < 0:
# #             set {_g} to 0.24#-0.01
# #             execute console command "/playsound minecraft:block.portal.ambient master @a ~ ~ ~ 1 0 0.5"
# #         else:
# #             set {_g} to -0.9#1
# #             execute console command "/playsound minecraft:block.anvil.land master @a ~ ~ ~ 1 0 0.4"
# #         loop 120 times:
# #             # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# #             wait a tick
# #             stop if {game} isn't set
# #             while size of {停止::*} > 0:
# #                 wait a tick
# #             cooldown of player to 100 second
# #             # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# #             loop entities:
# #                 loop-entity isn't player
# #                 gamemode of loop-entity isn't spectator
# #                 Own(loop-entity,"背信","INVENTORY") is false
# #                 set y of velocity of loop-entity to {_g}
# #                 #set gravity attribute of loop-entity to {_g}
# #                 apply slowness 10 without any particles without a potion icon to loop-entity for 1 seconds replacing the existing effect if {_g} < 1
# #             execute console command "/worldborder warning distance 10000"
# #         execute console command "/worldborder warning distance 200"
# #         loop entities:
# #             set gravity attribute of loop-entity to 0.08
# #     if Own(player,"雨") is true:
# #         "world" isn't thundering
# #         player is ready for 60 seconds
# #         strike lightning at location(0,1000,0)
# #         execute console command "/playsound minecraft:block.end_portal.spawn master @a ~ ~ ~ 0.3 0 0.3"
# #         loop 30*20 times:
# #             # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# #             wait a tick
# #             stop if {game} isn't set
# #             while size of {停止::*} > 0:
# #                 wait a tick
# #             cooldown of player to 60 second
# #             # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# #             execute console command "/weather thunder"
# #             if loop-counter > 40:
# #                 loop entities:
# #                     loop-entity is in rain
# #                     #loop-entity isn't player
# #                     loop-entity is a player or mob
# #                     loop-entity's gamemode isn't spectator
# #                     Own(loop-entity,"背信","INVENTORY") is false
# #                     apply poison 5 without any particles without a potion icon to loop-entity for 0.5 seconds replacing the existing effect
# #             else if loop-counter < 2:
# #                 strike lightning at location(0,1000,0)
# #         execute console command "/weather clear"
# #     if Own(player,"蟲") is true:
# #         player is ready for 30 seconds
# #         set {_loc} to player's location
# #         execute console command "/particle minecraft:wax_on %Loc({_loc})% 0 0 0 10 50"
# #         loop 20 times:
# #             # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# #             wait a tick
# #             stop if {game} isn't set
# #             while size of {停止::*} > 0:
# #                 wait a tick
# #             # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# #             spawn 1 of (bee or spider or cavespider or silverfish) at {_loc}
# #             set max health of last spawned entity to (random number between 0.1 and 2)
# #             set scale attribute of last spawned entity to (random number between 0.5 and 0.7)
# #             set movement speed attribute of last spawned entity to (random number between 0.2 and 0.6)
# #             execute console command "/playsound minecraft:block.moss.break master @a %Loc({_loc})% 1 0" if chance of 30%
# #             execute console command "/playsound minecraft:item.bucket.empty_fish master @a %Loc({_loc})% 0.4 0" if chance of 30%
# #             execute console command "/playsound minecraft:block.suspicious_gravel.hit master @a %Loc({_loc})% 0.2 0" if chance of 30%
# #             execute console command "/particle minecraft:block{block_state:{Name:""dirt"",Properties:{}}} %Loc({_loc})% 0.2 0 0.2 0.15 20"
# #             execute console command "/particle minecraft:block{block_state:{Name:""dirt_path"",Properties:{}}} %Loc({_loc})% 0.1 1 0.1 0.2 10"
# #             execute console command "/particle minecraft:block{block_state:{Name:""birch_wood"",Properties:{}}} %Loc({_loc})% 0.05 0.1 0.05 0.1 10"
# #             add last spawned entity to {蟲::*}
# #         loop 30*20 times:
# #             # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# #             wait a tick
# #             stop if {game} isn't set
# #             while size of {停止::*} > 0:
# #                 wait a tick
# #             # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# #         loop 20 times:
# #             # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# #             wait 10 tick
# #             stop if {game} isn't set
# #             while size of {停止::*} > 0:
# #                 wait a tick
# #             # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# #             set {_蟲} to random entity out of {蟲::*}
# #             execute console command "/particle minecraft:trial_omen %Loc({_蟲})% 0 0 0 0 1 force @a"
# #             subtract {_蟲} from {蟲::*}
# #             kill {_蟲}
# #     if Own(player,"追跡") is true:
# #         player is ready for 20 seconds        
# #         execute console command "/playsound minecraft:entity.goat.milk master @a %Loc(player)% 0.3 0"
# #         loop 26*20 times:
# #             # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# #             wait a tick
# #             if any:
# #                 {game} isn't set
# #                 Has({play::*},player) is false
# #             then:
# #                 stop
# #             while size of {停止::*} > 0:
# #                 wait a tick
# #             cooldown of player to 20 second
# #             # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# #             loop-counter < 26*20 - 4*20
# #             mod(loop-counter,4) is 0
# #             loop entities:
# #                 loop-entity isn't player
# #                 loop-entity is on ground
# #                 loop-entity is a player or a mob
# #                 gamemode of loop-entity isn't spectator
# #                 add "%Loc(loop-entity)%|70" to {_footstep::*}
# #             set {_footstep2::*} to {_footstep::*}
# #             loop {_footstep2::*}:
# #                 remove loop-value-2 from {_footstep::*}
# #                 set {_f::*} to loop-value-2 split at "|"
# #                 set {_f} to {_f::2} parsed as number
# #                 add "%{_f::1}%|%{_f} - 1%" to {_footstep::*} if {_f} > 0
# #                 execute console command "/particle block_marker{block_state:{Name:tripwire}} %{_f::1}% 0.3 0.3 0.3 0 1 force %player%"
# #     if Own(player,"予言") is true:
# #         set {_check} to false
# #         loop players:
# #             Has({play::*},loop-player) is true
# #             Own(loop-player,"背信","INVENTORY") is false
# #             {予言_%loop-player%} isn't set
# #             set {_check} to true
# #         {_check} is true
# #         player is ready for 100 seconds     
# #         set {_gm} to gamemode of player
# #         set {_loc} to location of player
# #         #execute console command "/playsound minecraft:entity.goat.milk master @a %Loc(player)% 0.3 0"
# #         set gamemode of player to spectator
# #         teleport player at location(0,-100,0)
# #         execute console command "/playsound minecraft:item.goat_horn.sound.5 master %player% 0 -100 0 0.3 0.7"
# #         execute console command "/playsound minecraft:item.goat_horn.sound.6 master %player% 0 -100 0 0.2 0.1"
# #         execute console command "/playsound minecraft:music.overworld.frozen_peaks master %player% 0 -100 0 0.3 2"
# #         set {_p} to "可哀想だね！" or "哀れだね！" or "悲劇的だね！" or "世界は残酷だね！" or "世界は非情だね！" or "助かるのかな？" or "あーあ、残念だ！" or "主役おめでとう！" or "痛そうだね！"
# #         set {_予言::*} to {play::*}
# #         set {_t} to random player out of {_予言::*}
# #         set {予言_%{_t}%} to "animal" or "swim" or "eat" or "fall" or "murder" or "pickup" or "heart"
# #         set {_r} to "食べ物を喉に詰まらせて死んじゃった！" if {予言_%{_t}%} is "eat" #
# #         set {_r} to "高い所から足を滑らせて転落死しちゃった！" if {予言_%{_t}%} is "fall" #
# #         set {_r} to "なんの前触れもなく心臓麻痺で死んじゃった！" if {予言_%{_t}%} is "heart" #
# #         set {_r} to "動物さんと戯れてたら運悪く殺されちゃった！" if {予言_%{_t}%} is "animal" #
# #         set {_r} to "うっかり溺れてパニックになって水死しちゃった！" if {予言_%{_t}%} is "swim" #
# #         set {_r} to "物を拾おうとしてサソリに噛まれて死んじゃった！" if {予言_%{_t}%} is "pickup" #
# #         set {_r} to "近くを通りがかった人間が発狂して殺しちゃった！" if {予言_%{_t}%} is "murder" #
# #         loop 20*20 times:
# #             # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# #             wait a tick
# #             if any:
# #                 {game} isn't set
# #                 Has({play::*},player) is false
# #             then:
# #                 stop
# #             while size of {停止::*} > 0:
# #                 wait a tick
# #             cooldown of player to 100 second
# #             # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# #             teleport player at location(0,-100,0,"world",0,90)
# #             if loop-counter is 1:
# #                 clear {_pages::*}
# #                 add Loprip_NewComponentBuilder() to {_pages::*}
# #                 Loprip_addComponent({_pages::*}, "%nl%%nl%　&rやあみんな！%nl%%nl%　モンスターストーリーの%nl%　時間がやってきたよ！")
# #                 execute console command "/playsound minecraft:item.book.page_turn master %player% 0 -100 0 0.6 1"
# #                 set {_book} to Loprip_WriteToBook({_pages::*})
# #             else if loop-counter is 5*20:
# #                 clear {_pages::*}
# #                 add Loprip_NewComponentBuilder() to {_pages::*}
# #                 Loprip_addComponent({_pages::*}, "%nl%%nl%&r今日の主役は%nl%&4%{_t}%&rだ！%nl%%nl%えーっと、%nl%%nl%%nl%この物語のあらすじは……")
# #                 execute console command "/playsound minecraft:item.book.page_turn master %player% 0 -100 0 0.6 1"
# #                 set {_book} to Loprip_WriteToBook({_pages::*})
# #             else if loop-counter is 10*20:
# #                 clear {_pages::*}
# #                 add Loprip_NewComponentBuilder() to {_pages::*}
# #                 Loprip_addComponent({_pages::*}, "%nl%%nl%&4%{_t}%&rは%nl%%nl%&4%{_r}%&r%nl%%nl%&rだってさ！%nl%%nl%%{_p}%")
# #                 execute console command "/playsound minecraft:item.book.page_turn master %player% 0 -100 0 0.6 1"
# #                 set {_book} to Loprip_WriteToBook({_pages::*})
# #             else if loop-counter is 15*20:
# #                 clear {_pages::*}
# #                 add Loprip_NewComponentBuilder() to {_pages::*}
# #                 Loprip_addComponent({_pages::*}, "%nl%%nl%&rそれじゃあみんな、%nl%さようなら～！")
# #                 execute console command "/playsound minecraft:item.book.page_turn master %player% 0 -100 0 0.6 1"
# #                 set {_book} to Loprip_WriteToBook({_pages::*})
# #             open book {_book} to player
# #         execute console command "/stopsound %player% master"
# #         close player's inventory
# #         set fall distance of player to 0
# #         set gamemode of player to {_gm}
# #         teleport player at {_loc}
# #         kill {_t} if {予言_%{_t}%} is "heart"
# #         while Has({play::*},{_t}) is true:
# #             # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# #             wait a tick
# #             stop if {game} isn't set                
# #             while size of {停止::*} > 0:
# #                 wait a tick
# #             # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# #             if {予言_%{_t}%} is "swim":
# #                 kill {_t} if {_t} is in water
# #             else if {予言_%{_t}%} is "murder":
# #                 loop players:
# #                     loop-player isn't {_t}
# #                     gamemode of loop-player isn't spectator
# #                     kill {_t} if distance between {_t} and loop-player < 4
# #             else if {予言_%{_t}%} is "animal":
# #                 loop mobs:
# #                     kill {_t} if distance between {_t} and loop-entity < 4

# #     if Own(player,"夢") is true:
# #         player's inventory has enough space for 1 of enchanted book
# #         player is ready for 150 seconds
# #         add {skill::*} to {_skill::*}
# #         remove {banned::*} from {_skill::*}
# #         give 1 of (random element out of {_skill::*}) to player
# #         execute console command "/playsound minecraft:block.portal.travel master @a %Loc(player)% 0.1 2"
# #         execute console command "/playsound minecraft:entity.illusioner.cast_spell master @a %Loc(player)% 0.3 1.3"

# #     if Own(player,"屍術") is true:
# #         player is ready for 100 seconds
# #         execute console command "/particle minecraft:scrape %Loc(player's head)% 0.5 0.5 0.5 0 40 force @a"
# #         #execute console command "/particle minecraft:happy_villager %Loc(player's head)% 0.3 0.3 0.3 1 30 force @a"
# #         execute console command "/playsound minecraft:entity.zombie_villager.converted master @a %Loc(player)% 0.3 2"
# #         execute console command "/playsound minecraft:entity.player.levelup master @a %Loc(player)% 0.3 2"
# #         show resurrection by totem on player
# #         loop items in player's inventory:
# #             loop-item is player head
# #             set {_a::*} to name of loop-item split at "&r"
# #             set {_a::*} to {_a::1} split at "の死骸"
# #             loop players: #{spec::*}
# #                 loop-value-2's name is {_a::1}
# #                 Has({play::*},loop-value-2) is false
# #                 remove loop-item from player's inventory
# #                 #生存者が該当するとき
# #                 teleport loop-player at player
# #                 reset loop-player to "play"
# #                 set gamemode of loop-player to survival
# #                 show resurrection by totem on loop-player
# #                 execute console command "/team join player %loop-player%"
# #                 stop
# #         loop players: #生存者が該当しないとき
# #             set {_p} to loop-player
# #             Has({play::*},loop-player) is false
# #             teleport loop-player at player
# #             helmet of loop-player isn't zombie head
# #             reset loop-player
# #             set gamemode of loop-player to survival
# #             loop players:
# #                 loop-player-1 is loop-player-2
# #                 show resurrection by totem on loop-player-2
# #                 execute console command "/team join player %loop-player-2%"
# #                 set helmet of loop-player-2 to zombie head of curse of binding 1
# #             stop
# #         spawn 1 of zombie at player
# #         #だれもいないとき
# #     if Own(player,"封印") is true:
# #         loop entities:
# #             loop-entity is a player
# #             loop-entity isn't player
# #             loop-entity's gamemode isn't spectator
# #             Own(loop-entity,"背信","INVENTORY") is false
# #             distance between player and loop-entity < 100
# #             add loop-entity to {_t::*}
# #         set {_t} to Look({_t::*},player)
# #         {_t} is set
# #         player is ready for 30 seconds
# #         set cooldown of enchanted book for {_t} to 30 second
# #         execute console command "/particle minecraft:block{block_state:{Name:""iron_block"",Properties:{}}} %Loc({_t})% 0 0.4 0 0.15 22"
# #         execute console command "/playsound minecraft:block.vault.close_shutter master @a %Loc({_t})% 0.3 2"















# # # Every 1 tick:
# # #     {game} is set
# # #     size of {停止::*} !> 0
# # #     loop players:
# # #         Has({player::*},loop-value) is true
# # #         if Own(loop-value,"貪食","INVENTORY") is true:
# # #             set saturation of loop-player to 0
# # #             execute console command "/effect give %loop-player% minecraft:haste 1 1 true"
# # #             execute console command "/effect give %loop-player% minecraft:hunger 1 1 true"
# # #             if food level of loop-player is 0:
# # #                 execute console command "/playsound minecraft:ambient.cave master %loop-player% %Loc(loop-player)% 0.01 2"
# # #                 execute console command "/particle minecraft:damage_indicator %Loc(loop-player)% 0.6 0.6 0.6 0 1" if chance of 3%
# # #                 execute console command "/playsound minecraft:entity.player.burp master @a %Loc(loop-player)% 0.1 0" if chance of 3%
# # #                 execute console command "/effect give %loop-player% minecraft:darkness 2 1 true" if chance of 3%
# # #                 set walk speed of loop-player to random number between 0.15 and 0.25
# # #             else if food level of loop-player <= 3:
# # #                 set food level of loop-player to 0
# # #                 execute console command "/effect give %loop-player% slowness 3 1 true"
# # #                 execute console command "/playsound minecraft:entity.wolf.growl master @a %Loc(loop-player)% 0.3 0"
# # #                 execute console command "/playsound minecraft:entity.piglin.celebrate master @a %Loc(loop-player)% 0.4 0"






# # on break:

# # #     if Own(player,"貪食") is true:
# # #         set food level of player to food level of player + 0.5
# # #         execute console command "/playsound minecraft:entity.generic.eat master @a %Loc(player)% 0.4 0.8"





# #     # set {queue} to a new queue of all players

# #     # set {player 1} to a random element out of {queue} 
# #     # set {player 2} to a random element out of {queue}
# #     # # players 1 and 2 are guaranteed to be distinct


# # command /test:
# #     trigger:
# #         for each {_player} in players:
# #             send "Hello %{_player}%!" to {_player}








# # replace "%%player%%" in {_message} with "%player%"

#     set {_source} to a custom damage source:
#         set the damage type to arrow
#         set the causing entity to {_player}
#         set the direct entity to {_arrow}
#         set the damage location to location(0, 0, 10)
#     damage all players by 5 using {_source}








# on right click with stick:

#     # 視点の先にいるのが防具立てかどうかチェックする
#     target entity of player is an armor stand

#     # どっちかの位置を保存しとく
#     set {_loc} to location of player

#     # 位置をいれかえる処理
#     teleport player at (target entity of player)
#     teleport (target entity of player) at {_loc}



# on input key press of (forward movement key, backward movement key, right movement key and left movement key):
# 	send "You are pressing: %event-inputkeys%" to player





# パッシブスキル

# Every 10 seconds:
#     loop players:
#         clear all potion effects of loop-player if Own(loop-player,"背信","INVENTORY") is true

# on break:
#     true is Own(player,"爆破")
#     cancel event
#     Ready(player, 1 seconds) is true
#     set {爆破::%player%} to location of block
#     execute console command "/playsound minecraft:entity.phantom.hurt master @a %Loc(block)% 0.3 1.7"
#     execute console command "/particle dust{color:[0.67,0.0,0.0],scale:2} %Loc(block)% 0.3 0.3 0.3 1 13 force @a"



# import:
#     org.bukkit.event.player.PlayerMoveEvent

# on drop:
#     size of {停止::*} > 0
#     cancel event if {停止::*} don't contain player
# on pickup:
#     size of {停止::*} > 0
#     cancel event if {停止::*} don't contain player
# on right click:
#     size of {停止::*} > 0
#     cancel event if {停止::*} don't contain player
# on PlayerMoveEvent:
#     size of {停止::*} > 0
#     cancel event if {停止::*} don't contain event.getPlayer()

# on game event:
#     size of {耳::*} > 0
#     stop if {game} isn't set
#     # size of {停止::*} isn't more than 0
#     spawn 1 of block display at entity
#     set {_a} to last spawned block display
#     set display block data of {_a} to redstone wire
#     set display translation of {_a} to vector(-0.5,0.1,-0.5)
#     set display glow color override of {_a} to bukkitColor(1,255,1,100)
#     set glowing of {_a} to true
#     hide {_a} from all players
#     set pitch of {_a} to 0
#     loop {耳::*}:
#         reveal {_a} from loop-value
#     wait 19 tick
#     stop if {game} isn't set
#     kill {_a}
# on sneak toggle:
#     player is not sneaking
#     Own(player,"耳") is true
#     Ready(player, 5 seconds) is true
#     execute console command "/playsound minecraft:block.respawn_anchor.charge master %player% %Loc(player)% 0.2 0"
#     wait a tick
#     add player to {耳::*}
#     while player is sneaking:
#         # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
#         wait 1 tick
#         while size of {停止::*} > 0:
#             wait a tick
#         if any:
#             {game} isn't set
#             {spec::*} contain player
#             Own(player,"耳") isn't true
#         then:
#             stop loop
#         Ready(player, 5 seconds, "RESET")
#         # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
#         execute console command "/effect give %player% blindness 2 1 true"
#     execute console command "/playsound minecraft:ui.toast.out master %player% %Loc(player)% 0.6 1"
#     execute console command "/playsound minecraft:ui.toast.out master %player% %Loc(player)% 0.6 1"
#     remove player from {耳::*}

# on damage of wither skeleton:
#     cancel event if attacker's name isn't "&4%victim%"
# on pickup of paper:
#     {play::*} contain player
#     item's name is "&4"
#     cancel event
#     stop if Own(player,"禁忌","INVENTORY") is true
#     stop if Own(player,"背信","INVENTORY") is true
#     spawn 1 of wither skeleton at location 2 meter horizontal behind player
#     set {_e} to last spawned wither skeleton
#     set {_e}'s freeze time to 999 days
#     set {_e}'s scale attribute to 1.2
#     set {_e}'s name to "&4%player%"
#     hide {_e} from all players
#     delete dropped item
#     set tool of {_e} to air
#     add nbt from "{Silent:1b,Invulnerable:1b}" to nbt of {_e}
#     apply potion of strength tier 4 without particles to {_e} for 999 days
#     apply potion of slowness tier 1 without particles to {_e} for 999 days
#     set helmet of {_e} to player head with nbt from "{""minecraft:profile"":{id:[I;548505118,-1124709528,-2143382277,-1731794478],name:"""",properties:[{name:""textures"",value:""eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMzY3OTg2NjY2ODRkMjZlOGI5NTM4ZjY0MDRkYjczZDEwYWEwNzYzZWZiYWIyM2JhZDkyYTFkMGRmY2Q1MTg3MCJ9fX0=""}]}}"
#     while {_e} isn't dead:
#         # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
#         wait 1 tick
#         while size of {停止::*} > 0:
#             wait a tick
#         if any:
#             {game} isn't set
#             {spec::*} contain player
#             Own(player,"背信","INVENTORY") is true
#         then:
#             stop loop
#         Ready(player, 100 seconds, "RESET")
#         # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
#         if distance between {_e} and player > 30:
#             teleport {_e} at location 5 meter horizontal in front of player
#             play sound "AMBIENT_CAVE" seed 5 with volume 0.5 with pitch 1.5 on player for player
#             play sound "AMBIENT_CAVE" seed 7 with volume 0.4 with pitch 1.1 on player for player
#             execute console command "/effect give %player% blindness 1 1 true"
#         else if distance between {_e} and player < 10:
#             execute console command "/effect give %player% darkness 2 1 true"
#             reveal {_e} from player
#         else:
#             hide {_e} from player
#         play sound "MUSIC_DISC_MELLOHI" with volume 0.4 with pitch 0 on player for player
#         set target of {_e} to player if target of {_e} isn't player
#     execute console command "/stopsound %player% master"
#     teleport {_e} at location(0,-999,0)
#     kill {_e}
        
    

# #         # play sound "MUSIC_GAME" seed 26 with volume 0.4 with pitch 2 on player
        
# #         # execute console command "/playsound minecraft:ambient.warped_forest.mood master @a %Loc(player)% 0.6 2"
# #         # execute console command "/playsound minecraft:ambient.warped_forest.mood master @a %Loc(player)% 0.5 1"


# # # import:
# # #     
# # #     
# # #     org.bukkit.GameEvent
# # #     org.bukkit.entity.Player

# on sneak toggle:
#     player is on ground
#     player isn't sneaking
#     Own(player,"双対") is true
#     set {_tool} to player's tool
#     execute console command "/playsound minecraft:entity.camel.dash_ready master @a %Loc(player)% 0.4 0"
#     wait a tick
#     while player is sneaking:
#         # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
#         wait 1 tick
#         while size of {停止::*} > 0:
#             wait a tick
#         if any:
#             {game} isn't set
#             player isn't on ground
#             player's tool isn't {_tool}
#             player's gamemode is spectator
#         then:
#             clear {双対::%player%}
#             stop
#         # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
#         execute console command "/effect give %player% minecraft:slowness 1 1 true"
#         clear {双対::%player%}
#         clear {_t::*}
#         loop all entities in radius 100 around player:
#             loop-entity's gamemode isn't spectator
#             loop-entity isn't player
#             execute console command "/particle minecraft:bubble_pop %Loc(loop-entity,0.5)% 0.1 0.1 0.1 0 3 force %player%"
#             add loop-entity to {_t::*}
#         set {_max} to 0
#         set {_dir} to vector from yaw player's yaw and pitch player's pitch
#         for each {_t} in {_t::*}:
#             continue if Own({_t},"背信","INVENTORY") is true
#             set {_rel} to normalized (vector from player's head to {_t})
#             if {_dir} dot {_rel} > {_max}:
#                 set {_max} to {_dir} dot {_rel}
#                 set {_e} to {_t}
#         set {双対::%player%} to {_e}
#         execute console command "/particle minecraft:trial_spawner_detection_ominous %Loc({_e})% 0.12 0.05 0.12 0 3 force %player%"



# on sneak toggle:
#     player isn't sneaking
#     Own(player,"大盾") is true
#     set {_tool} to player's tool
#     Ready(player, 10 seconds) is true
#     execute console command "/playsound minecraft:item.wolf_armor.break master @a %Loc(player)% 0.3 0"
#     execute console command "/playsound minecraft:entity.skeleton.converted_to_stray master @a %Loc(player)% 0.4 0"
#     set {_loc} to location 1 meter in front of head of player
#     loop blocks in radius 3 around player:
#         loop-block isn't air or water
#         add loop-block to {_deco::*}
#         add loop-block to {_break::*} if y-loc of loop-block > y-loc of player - 0.7
#     add bone block to {_deco::*}
#     loop 20 times:
#         spawn armor stand at {_loc}
#         set {_e::%loop-counter%} to last spawned armor stand
#         add nbt compound from "{Invisible:1b}" to nbt compound of {_e::%loop-counter%}
#         set {_e::%loop-counter%}'s scale attribute to (random number between 0.5 and 1.5)
#         set helmet of {_e::%loop-counter%} to (random element out of {_deco::*})
#     loop {_break::*}:
#         break block at loop-value
#     wait a tick
#     while player is sneaking:
#         # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
#         wait 1 tick
#         while size of {停止::*} > 0:
#             wait a tick
#         if any:
#             {game} isn't set
#             player's tool isn't {_tool}
#             player's gamemode is spectator
#         then:
#             stop loop
#         Ready(player, 10 seconds,"RESET")
#         # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
#         execute console command "/effect give %player% minecraft:slowness 1 1 true"
#         set {_loc} to location 2 meter in front of head of player
#         set {_loc} to location -1 meter above {_loc}
#         loop 20 times:
#             make 1 of block particle using (type of helmet of {_e::%loop-counter-2%}) at {_e::%loop-counter-2%}
#             push {_e::%loop-counter-2%} (vector between {_e::%loop-counter-2%} and {_loc})*0.6
#             push {_e::%loop-counter-2%} to the right at speed 0.6 if chance of 20%
#             push {_e::%loop-counter-2%} to the right at speed 0.6 if chance of 20%
#             push {_e::%loop-counter-2%} to the left at speed 0.6 if chance of 20%
#             push {_e::%loop-counter-2%} to the left at speed 0.6 if chance of 20%
#             push {_e::%loop-counter-2%} downwards at speed 0.6 if chance of 20%
#             push {_e::%loop-counter-2%} upwards at speed 0.6 if chance of 20%
#             teleport {_e::%loop-counter-2%} at {_loc} if chance of 20%
#     loop 20 times:
#         kill {_e::%loop-counter%}







# # # on combust:
# # #     size of {停止::*} !> 0
# # #     stop if entity is ignited
# # #     Has({運命::*},entity) is true
# # #     loop {運命::*}:
# # #         ignite loop-value for 8 second
# # # #     execute console command "/item replace entity @e[type=minecraft:armor_stand,name=""ITEM""] weapon.mainhand with filled_map[map_color=1044000]"
# # # #     set {慈愛} to tool of {_ITEM} with item flags all item flags named "&0"
# # # #     execute console command "/kill @e[type=minecraft:armor_stand,name=""ITEM""]"

# # # on eat:
# # #     kill player if {予言_%player%} is "eat"
# # # on pickup:
# # #     kill player if {予言_%player%} is "pickup"


#             # spawn undroppable falling block of redstone wire at {_l}
#             # これ、ベクトルでランダムにとばせる

# # # # #/playsound minecraft:block.respawn_anchor.deplete ma　時間まきもどし
# # # on damage by player:
# # #     projectile isn't set
# # #     if Own(attacker,"蟲") is true:
# # #         loop {蟲::*}:
# # #             set target of loop-value to victim
# # #         execute console command "/playsound minecraft:block.cobweb.break master @a %Loc(victim)% 0.6 0"
# # #         execute console command "/particle minecraft:block{block_state:{Name:""dirt"",Properties:{}}} %Loc(victim)% 0.2 0.4 0.2 0.15 20"
# # # #     if Own(attacker,"貪食") is true:
# # # #         IsAvailable(40 seconds,attacker) is true
# # # #         set {_damage} to 10 - food level of attacker
# # # #         set food level of attacker to 10
# # # #         set damage to {_damage}
# # # #         set walk speed of attacker to 0.01
# # # #         set {_loc} to location of attacker
# # # #         set pitch of {_loc} to pitch of {_loc} +1
# # # #         teleport attacker at {_loc}
# # # #         execute console command "/effect give %attacker% minecraft:speed 1 1 true"
# # # #         execute console command "/effect give %attacker% minecraft:weakness 3 1 true"
# # # #         execute console command "/particle crit %Loc(victim)% 0 0 0 1 %20 + {_damage}*4% force @a"
# # # #         execute console command "/playsound minecraft:entity.vex.hurt master @a %Loc(victim)% 0.5 0"
# # # #         execute console command "/playsound minecraft:entity.piglin.death master @a %Loc(victim)% 0.4 0"
# # # #         execute console command "/playsound minecraft:entity.evoker_fangs.attack master @a %Loc(victim)% 0.5 0"
# # # #         execute console command "/playsound minecraft:entity.zombie.break_wooden_door master @a %Loc(victim)% 0.3 0"
# # # #         execute console command "/particle dust{color:[0.99,0.0,0.0],scale:2} %Loc(victim)% 0.3 0.3 0.3 1 %{_damage}*4% force @a"
# # # #         execute console command "/particle minecraft:block{block_state:{Name:""red_glazed_terracotta"",Properties:{}}} %Loc(victim)% 0.7 0.7 0.7 0.1 %{_damage}*16%"
# # # #         loop 20 times:
# # # #             wait 1 tick
# # # #             while size of {停止::*} > 0:
# # # #                 wait a tick
# # # #             stop if {allowed} isN't set
# # # #             set food level of attacker to food level of attacker +0.5
# # # #         set walk speed of attacker to 0.2

# # # on target:
# # #     if entity is (bee or spider or cavespider or silverfish):
# # #         cancel event if Own(target of entity,"蟲","INVENTORY") is true
# # #     if entity is zombie:
# # #         cancel event if Own(target of entity,"屍術","INVENTORY") is true
# # # on despawn:
# # #     cancel event


# # # #　アクティブスキル

# # #     if Own(player,"慈愛") is true:
# # #         IsAvailable(20 seconds,player) is true
# # #         set {_n} to 00
# # #         execute console command "/playsound minecraft:block.beacon.deactivate master %player% %Loc(player)% 0.3 0"
# # #         set {_ui} to chest inventory with 6 row named "だれを仲間に加える？または外す？"
# # #         loop players:
# # #             Own(loop-value,"慈愛","INVENTORY") is false
# # #             Own(loop-value,"背信","INVENTORY") is false
# # #             set {_head} to loop-player's skull
# # #             set slot {_n} of {_ui} to {_head} named (loop-player's name) if Has({慈愛::*},loop-player) is false
# # #             set slot {_n} of {_ui} to {慈愛} named (loop-player's name)  if Has({慈愛::*},loop-player) isn't false
# # #             add 1 to {_n}
# # #         open {_ui} to player


# # #     if Own(player,"磁石") is true:
# # #         loop entities:
# # #             loop-entity isn't player
# # #             loop-entity's gamemode isn't spectator
# # #             Own(loop-entity,"背信","INVENTORY") is false
# # #             distance between player and loop-entity < 100
# # #             add loop-entity to {_t::*}
# # #         set {_t} to Look(player,{_t::*})
# # #         {_t} is set
# # #         IsAvailable(50 seconds,player) is true
# # #         execute console command "/particle minecraft:glow %Loc({_t})% 0 0 0 10 50 force @a"
# # #         execute console command "/playsound minecraft:block.conduit.activate master @a %Loc({_t})% 0.4 2"
# # #         loop 4*20 times:
# # #             wait 2 tick
# # #             while size of {停止::*} > 0:
# # #                 wait a tick
# # #             stop if {_t} is dead
# # #             stop if {allowed} isN't set
# # #             stop if gamemode of {_t} is spectator
# # #             execute console command "/particle minecraft:glow %Loc({_t})% 3 3 3 0 1 force @a"
# # #             execute console command "/particle minecraft:totem_of_undying %Loc({_t})% 3 3 3 0.3 1 force @a"
# # #             execute console command "/playsound minecraft:block.powder_snow.step master @a %Loc({_t})% 0.3 2"
# # #             loop entities in radius 6 around {_t}:
# # #                 loop-entity isn't {_t}
# # #                 loop-entity's gamemode isn't spectator
# # #                 Own(loop-entity,"背信","INVENTORY") is false
# # #                 set velocity of loop-entity to (velocity of loop-entity)*0.1
# # #                 push loop-entity (direction from loop-entity to {_t}) at speed 0.44



# # #     if Own(player,"侵蝕") is true:
# # #         IsAvailable(60 seconds,player) is true
# # #         set {_loc} to location 0.5 meter in front of player's head
# # #         execute console command "/particle minecraft:explosion %Loc({_loc})% 0 0 0 0.5 1 force @a"
# # #         execute console command "/playsound minecraft:entity.wither.shoot master @a %Loc({_loc})% 0.4 2"
# # #         execute console command "/playsound minecraft:block.dispenser.launch master @a %Loc({_loc})% 0.4 1.4"
# # #         make player shoot an arrow at speed 0.6
# # #         set {_e} to last shot arrow
# # #         set {侵蝕_%player%} to {_e}
# # #         set glowing of {_e} to true
# # #         loop 20*20 times:
# # #             wait 1 tick
# # #             while size of {停止::*} > 0:
# # #                 wait a tick
# # #             stop if {allowed} isN't set
# # #             stop loop if {_e} is dead
# # #             stop loop if {_e} is on ground
# # #             set velocity of {_e} to vector(0,0,0)
# # #             push {_e} in direction of player at speed 0.75
# # #             execute console command "/playsound minecraft:item.totem.use master @a %Loc({_e})% 0.1 2"
# # #             execute console command "/particle minecraft:dust{color:[0.0,0.0,0.0],scale:4} %Loc({_e})% 0.2 0.2 0.2 0 1 force @a"
# # #             execute console command "/particle minecraft:crit %Loc({_e})% 0 0 0 0.05 1 force @a"
# # #             execute console command "/particle minecraft:flash %Loc({_e})% 0 0 0 1 1 force @a"
# # #         kill {_e}
# # # on projectile hit:
# # #     wait 2 tick
# # #     loop players:
# # #         projectile is {侵蝕_%loop-player%}
# # #         apply potion of poison tier 30 to victim for 3 second if victim is alive
# # #         execute console command "/playsound minecraft:entity.ender_dragon.hurt master @a %Loc(victim)% 0.5 1"
# # #         clear {侵蝕_%loop-player%}
# # #         set {_block} to location of projectile
# # #         execute console command "/playsound minecraft:entity.warden.attack_impact master @a %Loc({_block})% 0.4 0.6"
# # #         execute console command "/particle minecraft:glow_squid_ink%Loc({_block})% 1 1 1 0 40 force @a"
# # #         loop blocks in radius 3 around {_block}:
# # #             loop-block isn't air
# # #             set the loop-block to sculk
# # #             add loop-block to {_侵蝕::*}
# # #         loop 2*15 times:
# # #             mod(loop-counter-2,15) is 1
# # #             set {_侵蝕2::*} to {_侵蝕::*}
# # #             loop {_侵蝕2::*}:
# # #                 wait 1 tick if chance of 3%
# # #                 wait 1 tick if chance of 3%
# # #                 while size of {停止::*} > 0:
# # #                     wait a tick
# # #                 stop if {allowed} isN't set
# # #                 if block at loop-value-3 is sculk shrieker or sculk or spawner or sculk catalyst or sculk vein:
# # #                     chance of 60%
# # #                     loop blocks in radius 2 around location of loop-value-3:
# # #                         loop-value-4 isn't air or sculk shrieker or sculk or spawner or sculk catalyst or sculk vein
# # #                         set the loop-value-4 to sculk shrieker or sculk or spawner or sculk catalyst or sculk vein or sculk or spawner or sculk vein or sculk or spawner or sculk vein
# # #                         add loop-value-4 to {_侵蝕::*}
# # #                 set the block at loop-value-3 to air
# # #                 subtract loop-value-3 from {_侵蝕::*}
# # #         stop




# # # on inventory click:
# # #     name of player's inventory is "だれを仲間に加える？または外す？"
# # #     event.getRawSlot() is between 0 and 53
# # #     item is player head or filled map
# # #     close player's inventory
# # #     cancel event
# # #     add player to {慈愛::*}
# # #     loop {player::*}:
# # #         item's name is loop-value's name
# # #         add loop-value to {慈愛::*} if item is player head
# # #         subtract loop-value from {慈愛::*} if item is filled map
# # #     loop {player::*}:
# # #         Own(loop-value,"慈愛","INVENTORY") is true
# # #         execute console command "/playsound minecraft:entity.allay.ambient_with_item master %loop-value% %Loc(player)% 0.4 0.7" if item is player's skull
# # #         execute console command "/playsound minecraft:entity.vex.charge master %loop-value% %Loc(player)% 0.4 1.4" if item is filled map
# # #     execute console command "/playsound minecraft:entity.witch.throw master %player% %Loc(player)% 0.4 2"
# # #     set {慈愛::*} to Single({慈愛::*})



# # # #　ダメージ関連
# # # on damage of player:
# # #     if {game} isN't set:
# # #         cancel event
# # #         stop
# # #     if gamemode of victim is spectator: # 死者
# # #         cancel event
# # #         stop
# # #     if attacker is (bee or spider or cavespider or silverfish):
# # #         Own(victim,"蟲","INVENTORY") is true
# # #         cancel event
# # #         stop
# # #     if damage cause is starvation:
# # #         Own(victim,"貪食","INVENTORY") is true
# # #         cancel event
# # #         stop

# # #     if damage cause is fall:
# # #         if Own(victim,"軽量","INVENTORY") is true: # 落下
# # #             execute console command "/playsound minecraft:entity.player.big_fall master @a %Loc(victim)% 0.3 2"
# # #             set damage to 0
# # #             cancel event
# # #         else:
# # #             set damage to damage/3
# # #             if fall distance of victim <= 10:
# # #                 set damage to 0
# # #                 cancel event 
# # #     if Has({慈愛::*},attacker) and Has({慈愛::*},victim) is true:
# # #         loop {player::*}:
# # #             Own(loop-value,"慈愛","INVENTORY") is true
# #             cancel event
# #             stop
# #     if size of {停止::*} > 0: # 停止
# #         add final damage to {停止_%victim%} if Has({停止::*},attacker) is true
# #         cancel event
# #         stop
# #     set {_damage} to final damage
# #     set {_health} to victim's health




# #     if {_health} <= {_damage}:
# #         set damage to 0
# #         set {_loc} to location of victim
# #         if victim is burning:
# #             drop wither skeleton skull named "&r焼けた死骸" at {_loc}
# #         else if victim's health > 5:
# #             drop skeleton skull named "&r無残な死骸" at {_loc}
# #         else:
# #             drop victim's skull named "&r誰かの死骸" at {_loc}
# #         Reset(victim,"spectator")
# #         wait a tick
# #         stop if {allowed} isN't set
# #         execute console command "/effect give %victim% minecraft:night_vision infinite 255 true"
# #         execute console command "/playsound minecraft:block.gravel.break master @a %Loc({_loc})% 0.6 1.2"
# #         execute console command "/playsound minecraft:entity.ender_dragon.hurt master @a %Loc({_loc})% 0.3 0.9"
# #         execute console command "/particle minecraft:block{block_state:{Name:""redstone_block"",Properties:{}}} %Loc({_loc})% 0.5 0.5 0.5 0.1 50"
# #         loop items in victim's inventory:
# #             wait 1 tick
# #             while size of {停止::*} > 0:
# #                 wait a tick
# #             stop if {allowed} isN't set
# #             loop-item isn't {LIMITED} だめ
# #             drop loop-item at {_loc}
# #             subtract loop-item from victim's inventory
# #             execute console command "/playsound minecraft:entity.item.pickup master @a %Loc({_loc})% 0.3 2"



# # #ーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーー

# # #三段ジャンプ
# # on jump:
# #     mod({mode},3) is 1
# #     player is sprinting
# #     #player's tool is air
# #     if slot 17 of player's inventory is 3 of end crystal named "&0":
# #         execute console command "/playsound minecraft:entity.ender_dragon.flap master @a %Loc(player)% 0.3 1.9"
# #         execute console command "/particle minecraft:cloud %Loc(player)% 0.1 0.1 0.1 0.1 10 force @a"
# #         set slot 17 of player's inventory to iron bars named "&0"
# #         push player upwards at speed 0.9
# #     else if slot 17 of player's inventory is 2 of end crystal named "&0":
# #         execute console command "/playsound minecraft:entity.ender_dragon.flap master @a %Loc(player)% 0.2 1.3"
# #         execute console command "/particle minecraft:cloud %Loc(player)% 0.05 0.05 0.05 0.05 3 force @a"
# #         set slot 17 of player's inventory to 3 of end crystal named "&0"
# #         push player upwards at speed 0.6
# #         loop 20 times:
# #             wait a tick
# #             stop if {game} isn't set
# #             stop if slot 17 of player's inventory isn't 3 of end crystal named "&0"
# #         set slot 17 of player's inventory to iron bars named "&0"
# #     else if slot 17 of player's inventory is 1 of end crystal named "&0":
# #         execute console command "/playsound minecraft:entity.ender_dragon.flap master @a %Loc(player)% 0.2 0.8"
# #         execute console command "/particle minecraft:cloud %Loc(player)% 0 0 0 0.01 1 force @a"
# #         set slot 17 of player's inventory to 2 of end crystal named "&0"
# #         push player upwards at speed 0.1
# #         loop 20 times:
# #             wait a tick
# #             stop if {game} isn't set
# #             stop if slot 17 of player's inventory isn't 2 of end crystal named "&0"
# #         set slot 17 of player's inventory to iron bars named "&0"
# #     else:
# #         set slot 17 of player's inventory to 1 of end crystal named "&0" 
# #         loop 20 times:
# #             wait a tick
# #             stop if {game} isn't set
# #             stop if slot 17 of player's inventory isn't 1 of end crystal named "&0" 
# #         set slot 17 of player's inventory to iron bars named "&0"

# # #エアジャンプ
# # on jump:
# #     wait a tick
# #     mod({mode},3) is 1
# #     #player's tool is air
# #     slot 16 of player's inventory isn't end crystal named "&0"
# #     set slot 16 of player's inventory to end crystal named "&0"
# #     set flight state of player to true
# #     loop 200 times:
# #         wait a tick
# #         stop if {game} isn't set
# #         stop loop if player is on ground
# #         stop if slot 16 of player's inventory isn't 1 of end crystal named "&0" 
# #     set slot 16 of player's inventory to iron bars named "&0"
# #     set flight state of player to false
# # on flight toggle:
# #     wait a tick
# #     mod({mode},3) is 1
# #     #player's tool is air
# #     slot 16 of player's inventory is end crystal named "&0"
# #     set slot 16 of player's inventory to iron bars named "&0"
# #     execute console command "/playsound minecraft:item.firecharge.use master @a %Loc(player)% 0.3 1.7"
# #     execute console command "/particle minecraft:explosion %Loc(player)% 0 0 0 1 1 force @a"
# #     push player horizontal forward at speed 0.5
# #     set y of velocity of player to 0.6
# #     set flight state of player to false



# #         #apply potion of levitation tier 10 to player for 10 tick

# # #ーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーー



# #ーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーー
# # リセット用
# #command /reset <player>:
# #    trigger:
# #        clear {target}
# #        clear {player_height}
# #/playsound minecraft:entity.turtle.egg_crack
# #        execute console command "/team remove CAT"
#     #    execute console command "/team add CAT"
#     #    execute console command "/team modify CAT collisionRule never"
#     #execute console command "/attribute %{target}% minecraft:scale base set %Clamp({player_height},0.9)%"
#     #clamp(5, 0, 10) = 5
#     #set tag "ct" of (nbt compound of {_a}) to {_a::2} parsed as number これエラーでるぞSKbeeのNBT講座みてこい
# #Every 1 second:
#     #apply potion of invisibility tier 100 without particles to {_e} for 999 days
#     #execute console command "/team join CAT @e[type=minecraft:wolf]"
#     #make {_e} invulnerable
#     #make {_e} silent
#     #while entity is alive:
#     #    teleport {_e} at entity if distance between {target} and entity >  8
# #on target:
# #    entity is an enderman
# #    cancel event if target of entity is {target}
# #
# #give player diamond sword with nbt from "{""minecraft:food"":{nutrition:10,saturation:2.0f}}"
# #set {_n} to nbt from "{custom_data:{points:10}}"
# #set {_i} to netherite axe with nbt {_n}
# #give player diamond pickaxe with nbt from "{""minecraft:damage"":500}"
# #give player 30 apples with nbt from "{""minecraft:max_stack_size"":10}"
# #give player diamond sword with nbt from "{""minecraft:custom_data"":{points:10}}"
# #give player diamond sword with custom nbt from "{points:10}"

# #/playsound minecraft:entity.glow_squid. ユートピアとかプライマルフィアとかなんでも使えそう
# #        execute console command "/effect give %player% minecraft:night_vision 10 10 true"　時間とばしでつかえる




# #import: #なぜそうなるのか？を聞いてはいけないゾーン(ごまふのゴリ押し)
# #    java.lang.System
# #    java.lang.Object
# #    java.lang.Enum
# #import:	
# #    ch.njol.skript.Skript
# #    org.bukkit.inventory.ItemFlag
# #expression (shiny|glowing|glow|glinted) %itemstack%:
# #    get:
# #        expr-1.addItemFlags(ItemFlag.HIDE_ENCHANTS)
# #        if expr-1 is not fishing rod:	
# #            expr-1.addUnsafeEnchantment(LURE, 1)
# #        if expr-1 is fishing rod:
# #            expr-1.addUnsafeEnchantment(CHANNELING, 1)
# #        return expr-1


# #command /test:
# #    trigger:
# #        sender is op
# #import:
# #    org.bukkit.event.server.TabCompleteEvent
# #on TabCompleteEvent:
# #    set {_buffer::*} to ...event.getBuffer().split(" ")
# #    if {_buffer::1} contains "/test":
# #        set {_list} to event.getCompletions()
# #        if size of {_buffer::*} = 1:
# #            {_list}.add("123")
# #        else if size of {_buffer::*} = 2:
# #            {_list}.add("321")
# #        event.setCompletions({_list})


#     execute console command "/playsound minecraft:entity.illusioner.cast_spell master @a %Loc(block)% 0.3 2"
# #on load:
# #    set {-time::s} to "second"
# #    set {-time::m} to "minute"
# #    set {-time::h} to "hour"
# #    set {-time::d} to "day"
# #    set {-time::w} to "week"
# #    set {-time::mo} to "month"
# #    set {-time::y} to "year"
# #function stringToTimespan(input: string) :: timespan:
# #    replace all " " in {_input} with ""
# #    loop regex {_input} split at "(?<=\d[a-z])(?=\d)":
# #        set {_t::*} to regex loop-value split at "(?<=\d)(?=[a-z])"
# # #        set {_t::2} to " %{-time::%{_t::2}%} ? {_t::2}% "
# # #        add (join {_t::*} with "") to {_result::*}
# # #    set {_result} to (join {_result::*} with "")
# # #    return {_result} parsed as timespan


# # #import:
# # #    java.io.File
# # #    org.bukkit.Bukkit
# # #    org.bukkit.configuration.file.YamlConfiguration
# # #function FileExists(path: String) :: boolean:
# # #    set {_file} to new File({_path})
# # #    return {_file}.exists()
# # #
# # #function SetYaml(path: String, key: String, value: Object):
# # #    set {_file} to new File({_path})
# # #    set {_yaml} to YamlConfiguration.loadConfiguration({_file})
# # #    {_yaml}.set({_key}, {_value})
# # #    {_yaml}.save({_file})
# # #
# # #function SetYamlList(path: String, key: String, value: Objects):
# # #    set {_file} to new File({_path})
# # #    set {_yaml} to YamlConfiguration.loadConfiguration({_file})
# # #    {_yaml}.set({_key}, {_value})
# # #    {_yaml}.save({_file})
# # #
# # #function ReadYaml(path: String, key: String) :: String:
# # #    set {_file} to new File({_path})
# # #    set {_yaml} to YamlConfiguration.loadConfiguration({_file})
# # #    return {_yaml}.getString({_key})
# # #
# # #function ReadYamlList(path: String, key: String) :: Objects:
# # #    set {_file} to new File({_path})
# # #    set {_yaml} to YamlConfiguration.loadConfiguration({_file})
# # #    return {_yaml}.getList({_key})














# # 首絞め
# on sneak toggle:
#     wait a tick
#     player is sneaking
#     loop living entities sorted by distance from player:
#         distance between player and loop-entity is less than 2
#         gamemode of loop-entity isn't spectator or creative
#         loop-entity isn't player
#         set {_t} to loop-entity
#         stop loop
#     {_t} is set
#     while player is sneaking:
#         # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
#         wait 1 tick
#         while size of {停止::*} > 0:
#             wait a tick
#         if any:
#             {_t} is dead
#             {game} isn't set
#             gamemode of {_t} is spectator
#             gamemode of player is spectator
#             (vector in direction of player) dot (vector in direction of {_t}) < 0
#             (vector in direction of player) dot (vector between player and {_t}) < 0
#         then:
#             stop loop
#         # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
#         teleport {_t} 0.6 meter horizontal in front of player
#         execute console command "/playsound minecraft:item.lead.tied master @a %Loc(player)% 1.5 0.5" if loop-counter is 1
#         apply potion of weakness tier 255 without particles whilst hiding icon to player for 1 seconds replacing existing effect
#         execute console command "/playsound minecraft:block.cherry_leaves.step master @a %Loc(player)% 0.3 0" if mod(loop-counter,6) is 1












# on sneak toggle:
#     player is sprinting
#     player is on ground
#     player isn't sneaking
#     push player horizontal forward at speed 1
# # standing_pose
# # croaking_pose
# # digging_pose
# # dying_pose
# # emerging_pose
# # fall_flying_pose
# # inhaling_pose
# # long_jumping_pose,
# # roaring_pose
# # shooting_pose
# # sitting_pose
# # sleeping_pose
# # sliding_pose
# # sneaking_pose
# # sniffing_pose
# # spin_attack_pose
# # swimming_pose
# # using_tongue_pose
# 一瞬で解除されてしまう、ポーズの変更に寄らず。reflectしかなさそう









# ここらへんいるよおおおおおおおおおおおおおおおおおおおおおおおおおおおおおおおおおおおおお






# import:
#     java.util.List
#     org.bukkit.Sound
#     java.util.Arrays
#     net.md_5.bungee.api.chat.HoverEvent
#     net.md_5.bungee.api.chat.ClickEvent
#     net.md_5.bungee.api.chat.BaseComponent
#     net.md_5.bungee.api.chat.TextComponent
#     net.md_5.bungee.api.chat.ComponentBuilder
#     io.papermc.paper.event.player.PlayerFlowerPotManipulateEvent
#     net.md_5.bungee.api.chat.HoverEvent$Action as HoverEventAction
#     net.md_5.bungee.api.chat.ClickEvent$Action as ClickEventAction


# # ライブラリ参照
# # function Loprip_NewComponentBuilder() :: Objects:
# # 	do 1 time [set {_newComponent} to new ComponentBuilder("")]->[return {_newComponent}]
# # function Loprip_addComponent(com: Objects, text: text) :: Objects:
# # 	set {_page} to size of {_com::*}
# # 	set {_com::%{_page}%} to {_com::%{_page}%}.append("&r%{_text}%").reset()
# # 	return {_com::*}
# # function Loprip_AddHoverShowText(com: Objects, text: text) :: Objects:
# # 	set {_page} to size of {_com::*}
# # 	set {_com::%{_page}%} to {_com::%{_page}%}.event(new HoverEvent(HoverEventAction.SHOW_TEXT, new ComponentBuilder("&r%{_text}%").create()))
# # 	return {_com::*}
# # function Loprip_AddClickCommand(com: Objects, cmd: text) :: Objects:
# # 	set {_page} to size of {_com::*}
# # 	set {_com::%{_page}%} to {_com::%{_page}%}.event(new ClickEvent(ClickEventAction.RUN_COMMAND, {_cmd}))
# # 	return {_com::*}
# # function Loprip_AddClickChangePage(com: Objects, topage: text) :: Objects:
# # 	set {_page} to size of {_com::*}
# # 	set {_com::%{_page}%} to {_com::%{_page}%}.event(new ClickEvent(ClickEventAction.CHANGE_PAGE, {_topage}))
# # 	return {_com::*}
# # function Loprip_AddClickOpenURL(com: Objects, url: text) :: Objects:
# # 	set {_page} to size of {_com::*}
# # 	set {_com::%{_page}%} to {_com::%{_page}%}.event(new ClickEvent(ClickEventAction.OPEN_URL, {_url}))
# # 	return {_com::*}
# # function Loprip_WriteToBook(com: Objects) :: item:
# # 	set {_book} to written book
# # 	set {_meta} to {_book}.getItemMeta()
# # 	loop {_com::*}:
# # 		set {_pages::%loop-index%} to loop-value.create()
# # 	{_meta}.setTitle("")
# # 	{_meta}.setAuthor("")
# # 	{_meta}.spigot().setPages({_pages::*})
# # 	{_book}.setItemMeta({_meta})
# # 	return {_book}
# # function Loprip_openBook(p: player, book: item):	
# # 	set {_tools} to {_p}'s tool 
# # 	set {_p}'s tool to {_book}
# # 	set {_open} to {_p}'s tool
# # 	{_p}.openBook({_open})
# # 	set {_p}'s tool to {_tools}
# # command /BookExample:
# # 	trigger:
# # 		# 1st Page
# # 		add Loprip_NewComponentBuilder() to {_pages::*}
# # 		Loprip_addComponent({_pages::*}, "&1[Page]%nl%%nl%")
# # 		Loprip_AddHoverShowText({_pages::*}, "1/3")
# # 		Loprip_addComponent({_pages::*}, "&1[Yes]")
# # 		Loprip_AddHoverShowText({_pages::*}, "first%nl%[yes]")
# # 		Loprip_AddClickCommand({_pages::*}, "/say hihi")
# # 		Loprip_addComponent({_pages::*}, "&4[no]")
# # 		Loprip_AddClickCommand({_pages::*}, "")
# # 		Loprip_addComponent({_pages::*}, "&4[ChangePage]")
# # 		Loprip_AddHoverShowText({_pages::*}, "&2[leftClick]%nl%to page 2")
# # 		Loprip_AddClickChangePage({_pages::*}, "2")
# # 		# Second page
# # 		add Loprip_NewComponentBuilder() to {_pages::*}
# # 		Loprip_addComponent({_pages::*}, "&1[Page]%nl%%nl%")
# # 		Loprip_AddHoverShowText({_pages::*}, "2/3")
# # 		Loprip_addComponent({_pages::*}, "&1[Yes]")
# # 		Loprip_AddHoverShowText({_pages::*}, "second%nl%[yes]")
# # 		Loprip_AddClickCommand({_pages::*}, "/say hihi")
# # 		Loprip_addComponent({_pages::*}, "&4[no]")
# # 		Loprip_AddClickCommand({_pages::*}, "")
# # 		Loprip_addComponent({_pages::*}, "%nl%%nl%&4[ChangePage]")
# # 		Loprip_AddHoverShowText({_pages::*}, "&2[leftClick]%nl%to page 3")
# # 		Loprip_AddClickChangePage({_pages::*}, "3")
# # 		# Third page 
# # 		add Loprip_NewComponentBuilder() to {_pages::*}
# # 		Loprip_addComponent({_pages::*}, "&1[Page]%nl%%nl%")
# # 		Loprip_AddHoverShowText({_pages::*}, "3/3")
# # 		Loprip_addComponent({_pages::*}, "&1[Yes]")
# # 		Loprip_AddHoverShowText({_pages::*}, "third%nl%[yes]")
# # 		Loprip_AddClickCommand({_pages::*}, "/say hihi")
# # 		Loprip_addComponent({_pages::*}, "&4[no]")
# # 		Loprip_AddClickCommand({_pages::*}, "")
# # 		Loprip_addComponent({_pages::*}, "&1[URL]")
# # 		Loprip_AddHoverShowText({_pages::*}, "&2[leftClick]%nl%www.google.com")
# # 		Loprip_AddClickOpenURL({_pages::*}, "https://www.google.com/")
# # 		set {_book} to Loprip_WriteToBook({_pages::*})
# # 		open book {_book} to player
# # function fallingOutlineExplosion(location: location, radius: number, velocity: number):
# #     create a fake explosion at {_location}
# #     loop blocks in radius {_radius} around {_location}:
# #         if distance between loop-block and {_location} > {_radius} - random number between 1 and 3:
# #             if difference between y-coordinate of loop-block and y-coordinate of {_location} < random number between 0 and 2:
# #                 spawn falling block of loop-block at loop-block
# #                 set loop-block to air
# #                 push last spawned falling block up with force 1
# #                 push last spawned falling block direction from {_location} to last spawned falling block with force {_velocity}










# condition %player% can see %entity%:
#     check:
#         return false if distance between expr-1 and expr-2 > 32
#         set {_rel} to normalized (vector from expr-1's head to expr-2)
#         set {_dir} to normalized (vector from expr-1 to location 1 forward expr-1)
#         return true if acos({_rel} dot {_dir}) < 65 else false






# ```python
# import:
#     com.sk89q.worldedit.bukkit.BukkitWorld
#     com.sk89q.worldedit.extent.clipboard.Clipboard
#     com.sk89q.worldedit.extent.clipboard.io.ClipboardFormats
#     com.sk89q.worldedit.math.BlockVector3
#     com.sk89q.worldedit.regions.CuboidRegion
#     java.io.File
#     java.nio.file.Files
#     java.nio.file.Paths

# effect paste schematic %string% at %location%:
#     trigger:
#         set {_path} to concat({@root}, expr-1, ".schem")
#         set {_file} to new File({_path})
#         set {_location} to BlockVector3.at(expr-2.getBlockX(), expr-2.getBlockY(), expr-2.getBlockZ())
#         set {_world} to new BukkitWorld(expr-2.getWorld())
#         ClipboardFormats.findByFile({_file}).load({_file}).paste({_world}, {_location}, false, true, false, null)

# effect create schematic %string% from %location% to %location% with origin %location%:
#     trigger:
#         set {_path} to concat({@root}, expr-1, ".schem")
#         set {_file} to new File({_path})
#         set {_pos1} to BlockVector3.at(expr-2.getBlockX(), expr-2.getBlockY(), expr-2.getBlockZ())
#         set {_pos2} to BlockVector3.at(expr-3.getBlockX(), expr-3.getBlockY(), expr-3.getBlockZ())
#         set {_origin} to BlockVector3.at(expr-4.getBlockX(), expr-4.getBlockY(), expr-4.getBlockZ())
#         set {_world} to new BukkitWorld(expr-2.getWorld())
#         set {_region} to new CuboidRegion({_world}, {_pos1}, {_pos2})
#         set {_clipboard} to Clipboard.create({_region})
#         {_clipboard}.setOrigin({_origin})
#         {_clipboard}.save({_file}, ClipboardFormats.findByAlias("FAWE"))


# on rightclick with stick:
#     send "save" to ops
#     create schematic "makimodoshi" from location(-200,-63,-200) to location(200,319,200) with origin location(0,100,0)
#     send "..." to ops
#     wait 5 second
#     send "..." to ops
#     paste schematic "makimodoshi" at location(0,100,0)
#     send "paste" to ops




# on right click with stick:
    
#     send "save" to ops
#     set {_map} to a new cuboid region from location(-200,-63,-200) to location(200,319,200)
#     save {_map} as a schematic named "makimodoshi":
#         copy entities: false
#         copy biomes: true
#         ignore air: true
#         #overwrite: true
#     wait 5 second
#     send "paste" to ops
#     #
#     paste schematic named "makimodoshi" at location(-300,-64,-300):
#         paste entities: true
#         paste biomes: true
#         #rotation: 45
#         ignore air: true
#     #```





# ```マップ一覧```
# ごまふコレクション :crown:
# -# セクター23 居住区

# ジンジャーエール
# -# タイニータウン、ネイチャースフィア、グラウンドスフィア

# Curtain Call
# -# ハイジャック

# タクティカルタコさん
# -# 炭鉱丘陵、スカイアリーナ

# Raven Calamity
# -# 冬山

# ユミトリ
# -# 白い廃城

# Slime Basket
# -# バスケットコート

# 弓漢
# -# 伝説の地、アサシンタウン、リオデジャネーヨ

# Minecraft Simulator
# -# 小さな国の物語

# AntiAthletics
# -# クロックタワー

# B6S & とりのなかま
# -# ベニクラゲセンター、ベニクラゲバンク









# シンボル一覧:
# 【牙】巨大な鰐になって地中をうごめく。
# 【耳】あらゆる音の位置が正確にわかる。
# 【背信】シンボルによる影響を無視する。
# 【不死】死亡してもその地点で復活する。
# 【彗星】爆撃地点をきめて隕石をおとす。
# 【大盾】前方にブロックの装甲をつくる。
# 【軽量】前方にむかってジャンプをする。落下のダメージを受けなくなる。
# 【稲妻】前方にむかって破壊光線を放つ。電圧のダメージを受けなくなる。
# 【禁忌】読むとソレに追われる紙をだす。その呪われる紙を拾わなくなる。
# 【消滅】しばらく周囲の全てを飲みこむ。発動中は周囲の様子がみえない。
# 【迷彩】しばらく透明になり姿をかくす。ダメージを被るとステルス解除。
# 【停止】しばらく時の流れを静止させる。止まった時で自分だけうごける。




#     add "経過|右クリ>>しばらく認識されず無敵化|所有　>>次のダメージを自動で躱す" to {_s::*}
#     add "爆破|破壊　>>ブロックを爆弾へと変える|右クリ>>遠隔でその爆弾を点火する" to {_s::*}
#     add "双対|シフト>>目先にいる物体を捕捉する|右クリ>>補足した物体と位置を交換" to {_s::*}

# シンボル・ハントという作品を考えているので、長文のリアクションをくれ
# これは群像劇で、シンボルという特異な力をもった主人公達が200名登場する
# 勝つべくして勝つ者はいるし、平和主義者もいるが、神や奇跡は味方をしない

# ある日、"ナッシング・バット・モノポリー"という主催者不明のゲームが開幕する
# それはチーミング、裏切り、金的、多勢に無勢、理不尽、洗脳、全てアリのルールで
# 頭の良い者や、運の良い者を除けば、勝利条件すら明かされず、序盤で過半数が死ぬ

# プレイヤー1 "ヒューム":
#   みため: 中央に大きな空洞のある顔面、色白の手、理知的だが冷笑的で孤独
#   せりふ: 「アウシュビッツやナガサキのやつらは、なぜ神に祈らなかったんだ？」
#   まほう: 背信のシンボル(自身に向けられたあらゆるシンボルの直接的作用を無視する)
#   きしつ: ボルトライフル銃が得意、過酷な状況でもパニクらない、他人を信頼できない

# プレイヤー2 "アンデルセン":
#   みため: 白鳥をモチーフにした仮面、ナイロンの防塵手袋、ナルシストだが繊細
#   せりふ: 「コケにしやがって……。俺はお前らより、何倍も優れた存在だというのに」
#   まほう: 予言のシンボル(無作為な者の死因が啓示され、対象はその通りに動くと死ぬ)
#   きしつ: 何事も卒なくこなせる、他人を怖がらない、油断することがある

# プレイヤー3 "バッハ":
#   みため: ロールシャッハテスト柄の布製仮面、ニットのアームウォーマー、実直で頑固
#   せりふ: 「いるんだよなぁ。楽観を嫌うがあまり、現実を極端な露悪とみたがるヤツ」
#   まほう: 非力のシンボル(いかなる状況でも、あらゆる武器が所持できなくなる)
#   きしつ: 非暴力への強迫観念、価値観を押し付ける、仲間が死にやすい

# プレイヤー4 "アレックス":
#   みため: 黒髪の成人男性、中肉中背、倫理的かつ道徳的で常識的
#   せりふ: 「えっ待って待って、え？いや、あ、え……あっ……まって、どういう……」
#   まほう: 耳のシンボル(どれほど小さな音でも、その音源や音質まで正確に把握できる)
#   きしつ: 戦闘に慣れていない、交渉力に欠ける、安心できる仲間が欲しい、死が怖い


# キャラクターたちは色んな手袋をしている(ネイルやデカールも自由)
# ・鎖 (涼しいが罪人の証)
# ・包帯 (出血や骨折に強い)
# ・軍手 (高温と高熱に強い)
# ・革手袋 (引き裂きに強い)
# ・静電手袋 (高電圧に強い)
# ・ケブラー手袋 (分厚くて防火)
# ・ニトリル手袋 (油や薬剤に強い)
# ・ポリエチレン手袋 (半透明なだけ)
# ・フィンガーループ手袋 (日焼け防止)
# ・スタッズグローブ (金具などの装飾)
# ・シューティンググローブ (滑り止め)
# ・レースグローブ (エレガントな花柄)
# ・ムスクテール (留め具と切り込み)
# ・アームウォーマー(ニットで防寒)
# ・アームカバー(サテンで指先露出)
# ・コルセットグローブ(長くてゴス)
# ・ガントレット (頑丈だが重量)
# ・篠籠手 (やや頑丈だが軽量)
# ・ミトン (高温低温に強い)
# ・腕貫 (通気性に優れる)
# キャラクターたちは色んなマスクをしている(
# ー

# ーそれじゃ網羅できねーだろ？

# とりあえずざっくり一緒に考えよう

# VIPのかぶる半分だけのやつ
# 中東っぽいスカーフ
# 目出し帽
# ペストマスク
# ガスマスク
# ヘルメット潜水服
# 吊られる人がつけられるやつ
# 能面
# 動物を模したやつ
# payday……まって

# す、キリがない！笑
# 手袋は「手を覆う」という機能がハッキリしてるから21種類でまとまったけど、頭部は:
# 	•	防護（ヘルメット、ガスマスク）
# 	•	防寒/防暑（ニット帽、麦わら）
# 	•	宗教/文化（ターバン、ベール）
# 	•	装飾（ティアラ、花冠）
# 	•	匿名性（覆面、フード）
# 	•	職業（シェフハット、ナースキャップ）
# 	•	刑罰/拘束（さらし首の袋、拘束具）
# …って用途が広すぎるんですよね

# Mobs Attempt Parkour、point blankやTaCZなどのマイクラ銃mod
# Garry’s ModのDarken’s Sci-Fi Weapon
# Hunt Showdown、GTFO、TeardownのMOD
# ー


# 	予言
# 封印
# 磁化
# 侵蝕
# 貪食
# 屍術
# 貫通
# 彗星
# 追跡
# 相棒
# 小人
# 河豚
# 運命
# 蟲
# 嵐
# 雨
# 夢
# 慈愛
# 侵蝕

#   追放のシンボル。再発動するまで指定したシンボルの発動を封じる。
#   夢のシンボル。ランダムなシンボルを一つ入手して、以降も使える。
#   巻戻のシンボル。全員の記憶はキープし、数分前へ時間を巻き戻す。
#   重力のシンボル。一時的に周囲の重力を強めたり、弱めたりできる。
#   麻薬のシンボル。一時的に周囲に麻薬を散蒔き、判断力を鈍らせる。
#   黄昏のシンボル。一時的に自身以外の全員が他人を識別不能になる。
#   村雨のシンボル。一時的に建物にも生物にも腐食性の雨を降らせる。
#   忘却のシンボル。自身以外の全生存者の体力や装備などを交換する。
#   月のシンボル。マップの全域にて、昼夜を強制的にサイクルさせる。
#   烙印のシンボル。生存者一人を指名手配し、それを殺した人に賞金。
#   蟲のシンボル。ゴキブリやネズミ、ハチなどの害虫を大量召喚する。
#   妖刀のシンボル。ランダムな呪いや、効果の付いた長剣を生成する。
#   河豚のシンボル。口腔から一斉に大量のフグを吐き出して攻撃する。
#   ロバのシンボル。ロバを召喚して、前方に投げ飛ばして、攻撃する。
#   消滅のシンボル。一時的に、周囲の全てを消し去りながら飛行する。
#   貪食のシンボル。常に空腹だが、生身の動物や無機物を摂取できる。
#   突撃のシンボル。強烈な音と光を放ち、周囲の生物をスタンさせる。
#   短剣のシンボル。鉛のダガーを生成し、指定した方向へと射出する。
#   獣のシンボル。一時的に近接戦に特化して、活性化後は弱体化する。
#   神のシンボル。一時的にクリエイティブモード化して、無敵になる。
#   相棒のシンボル。とても脆いが敏捷な骨馬を召喚し、乗りこなせる。
#   滑走のシンボル。陸上や水上を、高い加速性能で曲線的に移動する。
#   自由のシンボル。自身に翼を生やして、空中を自由自在に飛行する。
#   小人のシンボル。一時的に身体サイズが縮小し、隙間に侵入できる。
#   錨のシンボル。錨を放つことで、発動者または実体を引き寄せれる。
#   影のシンボル。暗所と同化して透明になり、移動速度が急上昇する。
#   光のシンボル。前方に瞬間移動し、高所や障害物の先にも移動する。
#   魚のシンボル。エラ呼吸ができるようになり、激流の川でも泳げる。
#   不死のシンボル。焼死でなきゃ直ちに体組織が再構築して復活する。
#   傭兵のシンボル。生物を殺すたびに、強靭なアーマーを獲得できる。
#   透明のシンボル。一時的に光学的な迷彩を身に纏って、自身を隠す。
#   傷のシンボル。触れてる生物に、自身の被ダメージが全て転移する。
#   枯渇のシンボル。周囲にいる生物の体力と満腹度を徐々に奪い取る。
#   泥棒のシンボル。指定した生物の所持品のうち何か一つを奪い取る。
#   鏡のシンボル。指定した生存者を、自身と全く同じ状態異常にする。
#   灰のシンボル。触れた死体や物品を、直ちに灰に変えて隠滅できる。
#   囮のシンボル。死んだ際に大爆発をし、周囲の生物を道連れにする。
#   非力のシンボル。自身が銃火器を扱えなくなり、近接攻撃も衰える。
#   ボブのシンボル。形而上学的存在から全く役立たない雑談をされる。
#   真実のシンボル。指定した生存者のシンボル又はスートを確認する。
#   履歴のシンボル。過去に発動された全シンボルを時系列で確認する。
#   暗視のシンボル。視力が急激に向上し、透明化した生物でも見破る。
#   目のシンボル。固体や生物に目を植え付け、遠距離から視察できる。
#   耳のシンボル。極端に静かなものでも、その音源を正確に知覚する。




# - 漁夫のシンボル # 最寄りのアイテムへと向かう実体を召喚。
# - 帰還のシンボル # トーテムを設置し、後にワープし戻れる。
# - 焼夷のシンボル # 有機物に放火したり、火炎瓶を投擲する。
# - 増殖のシンボル # 指定した物品を大量に複製する。汎用的。
# - 法螺のシンボル # 偽のシステムメッセージを全体送信する。
# - 意思のシンボル # 看板や置き手紙を残せる。死亡時も発動。
# - 幽居のシンボル # 非線形空間の民家を設置。入室した生存者は出れない。
# - 耕作のシンボル # いつでもどこでと効率よく作物を収穫し、食料を得る。
# - 虚像のシンボル # ドッペルゲンガーを召喚し、自由に位置を交換できる。
# - 要塞のシンボル # 豊富な建材を入手し、どこにでもバリケードを築ける。
# - 旋律のシンボル # ジュークボックスを設置する。周囲に色々な効果あり。
# - 医師のシンボル # 生物の体力を確認でき、瀕死でない生物を治癒できる。
# - 蜘蛛のシンボル # 固体に張り付く、よじ登る、壁走りなどの動作が可能。
# - 群集のシンボル # 粘土人形を召喚し指揮する。単体は弱く、大勢は凶悪。
# - 磁化のシンボル # 指定した実体に強い磁性を与え、危険な目に遭わせる。
# - 儀式のシンボル # 四匹の小動物を捧げると、生存者一人を遠隔で殺せる。
# - 代償のシンボル # 悪魔との取引は有利になるが、次の試合で障害を負う。
# - 結晶のシンボル # 生物が触れると鈍重になり凍死してく水晶を設置する。
# - 決闘のシンボル # 指定の生存者と異空間へ入場。片方死ぬまで出れない。
# - 運命のシンボル # 生物を指定してリンク。リンクされた生物は体力同期。
# - 窒息のシンボル # 消火ガスを投擲。爆発物や銃や呼吸などに支障を出す。
# - 沈黙のシンボル # 一時的にシンボルが使用不可になるエリアを生成する。
# - 聖域のシンボル # 一時的に物理攻撃全てが無効になるエリアを生成する。
# - 慈悲のシンボル # 指定した生存者を仲間に強制変更し、物理攻撃が無効。
# - 深淵のシンボル # 一度見ると目が離せなくなる彫刻品を、一時的に召喚。
# - 予言のシンボル # 生存者一人の死因が啓示され、状況次第で即死させる。
# - 恐怖のシンボル # 一時的に全ての生存者、動物、罠の位置が知覚できる。
# - 追跡のシンボル # 一時的に全ての足跡、血痕、死体の位置が知覚できる。
# - 屍術のシンボル # 死者を蘇生したり、下僕のゾンビを召喚したりできる。
# - 罠師のシンボル # 地雷、ワイヤー、セントリーガンなどを生成して設置。
# - 皮剥のシンボル # 自身がかつて殺したあらゆる生物の容姿に変装できる。
# - 拘束のシンボル # 最寄りの生物を拘束し、近くにいる間行動不能にする。
# - 侵蝕のシンボル # 一度放つと徐々にマップ全域を崩壊させるバグを放つ。
# - 脱出のシンボル # 空高く飛翔し、その後は滑空しながら徐々に落下する。
# - 終末のシンボル # 位置を晒しカンウトダウン。生存すれば単独強制勝利。
# - 氷結のシンボル # 周囲の水を氷に変え、凍てつく北風で生物を攻撃する。
# - 妖精のシンボル # 他の生存者との遭遇率が比較的低いルートに導かれる。

# 毒入りの食べ物生成する能力を送れ

#   参加者はいずれかのトランプに割り当てられ、他スートを殲滅すれば勝ち。
#   割り当ては被らず、一匹狼のジョーカーを含めて最大53人プレイ(13×4+1)。
#   トランプアイテムは入手したりもできるが、割り当てられたチームは固定。
#   他プレイヤーが敵か仲間かを推測する方法は、基本的に下記の四つ。
#   1.殺して直接確認。元も子もないが早い。アイテムは偽造できるため警戒。
#   2.会話による確認。状況判断が命。お互い開示せず終盤までの結託もアリ。
#   3.真実のシンボル。一番確実だが、このシンボル単独では戦闘力に欠ける。
#   4.コミットメント。殆ど脅迫だが、上手く使いこなせば仲間を炙り出せる。
# 中盤の立ち回り: |
#   信用しすぎはリスクだが、疑いすぎると孤立して、却って危ないため注意。
#   マップは広く、天候や昼夜も変わる。大抵、皆は市民や動物に紛れている。
#   ここで優先すべきは、勢力関係と、単独でヤバいシンボルが居るかの把握。
#   スートと同様、相手の能力も洞察するしかない。基本的に下記の四つ。
#   1.不自然な行動の確認。積極的な接近、やたら高所を取る、銃を捨てる等。
#   2.殺傷能力による余裕。リスキーな言動の背景には、たいてい自信が絡む。
#   3.退避や防衛は可能か。いわゆる"搦手"や"詰み"は、予想しとくしかない。
#   4.カウンターは可能か。敵を仕留めるには"素早い不意打ち"が最も効果的。
# 終盤の立ち回り: |
#   積極的なプレイヤーは、数々の戦利品からシンボルを回収しまくっている。
#   この際は、敵の誰かを懐柔する・交渉して延命させてもらうのも一つの手。
#   欺瞞、いじめ、裏切り、イカサマ、集団リンチ、なんでも起きるため注意。
#   ここまで理不尽に耐え抜いて、突如ゲームが終了したら……
#   おめでとう、君の勝ちだ。

#  アイテム (食料、武器、シンボル、トランプなどプレイヤーが持ち運びできる物品)

# 定義群と用語集:
#   主目的: 発動するための動機が何かによって対人戦闘/防御耐久/移動回避/物資取得/情報取得/心理干渉/特殊環境に分類される。
#   サイン: 即時/準備は、発動から活性するまでのタイミングがすぐなのかどうか。手動/自動は、主体的な操作による発動か、外部の入力待ちか。
#   ゾーン: 近接/遠隔は、発動者と対象との距離が10メートル以内にあるかどうか。単体/範囲/全域は、対象となる母集団の要素数がどれくらいか。
#   ラスト: 一瞬/持続は、活性から沈滞するまでの時間が10秒以内であるかどうか。固定/変動/永久/後遺は、活性が可変的か、次の試合に関わるか。
#   リスク: 除外/含有は、対象となる母集団で発動者だけが例外的に除外されるか。自傷/自損/無尽/獲得は、発動時に絶対、消費されるものがなにか。
#   クロス: 独立/依存は、そのシンボルの効果などが他シンボルと密接に関わるか。並進/妨害/触媒は、他シンボルと競合した際の優先順位などを表す。
# シンボルの一覧:
#   背信のシンボル (防御耐久、即時自動、遠隔全域、持続永久、除外無尽、依存妨害) 自身に向けられた、いかなるシンボルの直接作用を無効化する。
#   停止のシンボル (対人戦闘、即時手動、近接範囲、持続固定、除外無尽、独立妨害) 周囲の時間を止め、その中を自由に動き回ったりできる。
#   重力のシンボル (対人戦闘、即時手動、近接範囲、持続固定、除外無尽、独立並進) 周囲の重力を自由に強めたり、或いは弱めたりする。
#   村雨のシンボル (対人戦闘、準備手動、遠隔範囲、持続固定、含有無尽、独立並進) 建物が錆び、生物が痛む腐食性の雨を降らす。




# # 石のシンボル
# # ・地面からスパイクを送り、それに触れた相手を石化させる。石化すると動けなくなり防御力が上がる。
# # ・

# # 沼のシンボル
# # ・地面に広い沼を発生させ、そこに入った自分以外の者を動きづらくする。
# # ・

# # 衝撃のシンボル
# # ・前方に衝撃波を放つ。側にいた者は重症を追い、近くにいた者は吹っ飛ばされる
# # ・
# 魂だけになってモブに乗り移れる

# # 切断のシンボル
# # ・刃物を持っていた場合、高速で前方に移動し、通過した生物に致命傷を負わせる
# # ・

# # 正常のシンボル
# # ・指定した対象のシンボルを封じ使用不可能にする。自身が死ぬと対象の封印は解ける。
# # ・

# # 愛着のシンボル
# # ・いつでもどこでも自分専用の銃を取り出したり消したりできる。その銃は捨てると消える。弾薬は要らない。
# # ・かつてカウボーイとしてその名を広めた男に発現した能力。彼女の妻を撃ち殺してしまったその銃を、彼は捨てる事が出来なくなった。

# # 静寂のシンボル
# # ・自分や仲間の足音を消したり、対象の耳を聞こえなくしたり、対象を喋れなくさせたり出来る。遠のけば効果は消える。
# # ・神経質な青年に発現した能力。力を悪用していくうちに、神経質の度合いはどんどん増していった。

# # 弾丸のシンボル
# # ・いくつか弾丸を空中に発生させ、曲がった軌道に沿って敵に弱めの弾丸を命中させる。しっかりロックオン出来ればほぼオートエイム。
# # ・歴戦のガンマンに発現した能力。戦いをこよなく愛した男はやがて、弾を外す事すらも無くなっていた。

# # 死のシンボル
# # ・触れると即死する煙を撒き散らす。自分は死なないが、その代わりに体力が減る。
# # ・道徳を重んじる教師に発現した能力。能力のせいで、生徒たちと関われなくなってしまい、力を嫌うようになっていった。

# # 粉塵のシンボル
# # ・スプレーを振りかける。スプレーで壁などに落書きしたり、メッセージを残せる。スプレーには催涙作用がある。
# # ・マフィアも恐れない若手ヤンキーに発現した能力。数々の敵を作ってしまったが、本人は楽しんでいる。

# # 天罰のシンボル
# # ・対象のキル数に応じて、空高くからニワトリ/鉄床/雷/隕石を振り落とす。
# # ・裁判官に発現した能力。法で裁ききれなかった受刑者たちを遺族のために全て葬り去ったが、もし今の自分に能力を使えば隕石が落ちてくるのは明白だった。

# # 罪悪のシンボル
# # ・歩いたところの植物が枯れる。
# # ・ある意味深な男に発現した能力。詳しくは触れられず、何か大きな罪を犯し、それを深く受け入れ懺悔し続ける男に永遠に課せられた罰。

# # 孤独のシンボル
# # ・自身もしくは他人を虚無空間へと転送する。いつ現世に戻ってくるかは分からない。虚無空間では腹も減らないしシンボルも使えないし死ねない。
# # ・

# # 接続のシンボル
# # ・二つ以上の生物、オブジェクト、アイテムなどの位置関係を鎖で固定する。生物に対しては、そのまま引きちぎる事も可能。
# # ・悪意あるマフィアのボスに発現した能力。この世の全ては何かとの関係で成り立っており、そこには常に因果関係が存在すると信じている。

# # 貝のシンボル
# # ・貝をアイテムに扮装させて、他者が拾った時に貝の口を閉じさせて、素早さを下げる。貝は熱に弱い。
# # ・

# # 脱出のシンボル
# # ・全ての装備を捨て、空高くに上昇し、そのまま滑空する。

# # 斥候のシンボル
# # ・ひもを出してフックショットのように移動したり、逆に相手を引き寄せたり出来る。

# # 暗視のシンボル
# # ・シンボル使用中は周囲はほぼ見えないが、敵が居そうな大まかな範囲が見える。また、ゴールの花を持っている敵は、大きな反応がみえる。シンボルを使用していない時は、常に画面が明るく見える。

# # 黄金のシンボル
# # ・触れたアイテムを金に変えて役に立たないものへと変えれる。他にもドアなどの開閉物を固定したり、オブジェクトをちょっと装飾するのに使える。

# # 鍛冶のシンボル
# # ・ランダムな防具を生成する。

# # 浄化のシンボル
# # ・水質を汚染したり、食べ物を腐らせたりできる。また、歩いたところの植物が枯れる。

# # 人形のシンボル
# # ・様々な類の人形を複数設置する。人形の近くで、人間が回復をしていたり、装備の整理をしていたり、長時間別の方向を見ているなどの隙を見せた場合、その人形がその人間を襲い始める。

# # 崩壊のシンボル
# # ・全てを貫通するエネルギー弾を放ち、任意のタイミングで崩壊因子を放つ。崩壊因子に触れた生物は徐々に削られていき、その場所を起点としてマップがどんどん崩落していく。

# # 燈のシンボル
# # ・松明、キャンプファイヤー、ランタンなどを即席で出現させれる。明かりや暖をとるのに使える上、弱い火炎瓶として投げる事も可能。

# # 造形のシンボル
# # ・壁や橋、梯子や柱を工作したり、それらに穴をあけたり出来る。

# # 真実のシンボル
# # ・対象に暗殺者をつける。暗殺者は、水面や鏡などの反射で確認でき、また対象がそれらに映り込んでいる時にバックスタブを試行する。

# # 束縛のシンボル
# # ・過去に自身を攻撃した生物を距離問わず拘束する。拘束した生物は持ち運べて、地面を掘らせて瞬時に自身の元へ呼び寄せれる。また、その場に留まらせる事も出来る。

# # 飛行船のシンボル
# # ・自身の命とひきかえに、何人も乗せれる巨大な飛行船を召喚し操縦する。飛行船は高い体力を持っており、破壊されると焼け落ちて地面に墜落する。

# # 音色のシンボル
# # ・ジュークボックスを設置する。ゲーム内に登場するサウンドをお楽しみいただけるし、銃声などを偽装する事もできる。

# # 幸運のシンボル
# # ・一定確率でどんな擦り傷も致命傷に変わるような攻撃をする。確率を外すと、自分が致命傷を負う。

# # 案山子のシンボル
# # ・夜の間だけ行動し、自分よりも先頭を走る人間を襲う案山子をスポーンする。案山子は破壊されてもすぐに修復し、特に一人を執拗に追いかけ回す。案山子に触れるとほぼ即死。

# # 魔法のシンボル
# # ・自身の手にした武器をランダムにエンチャントする。

# # 啓蒙のシンボル
# # ・触れた瀕死の生物を、強制的に仲間にする。仲間同士はフレンドリーファイアが発生しない。

# # 向日葵のシンボル
# # ・ヒマワリをたくさん生やす。しゃがんでいると発見されづらくなる。

# # 修復のシンボル
# # ・生物や装備の回復/修理する。また、稀に破壊不能な装備にしたり、別の装備に変異させる事がある。生物であれば、ステータスをランダムにいじる事がある。やや五分五分だか、基本的には改悪する事が多い。

# # ===========================
# # [16:14]
# # 錆のシンボル
# # ・短い間だが、全てのダメージを大幅に軽減する。

# # 牙のシンボル
# # ・壁を口に変えて、射線を通したり壁抜けしたり出来る。任意のタイミングで口を閉じれて、その際に間に居た生物にダメージを与える

# # 解放のシンボル
# # ・指定した他人をしばらく制御不能のクリーチャーに変貌させる

# # 王のシンボル
# # ・指定した生物やアイテムを、自在に吹き飛ばせる。叩きつけたりも可能


# # 運命のシンボル
# # ・指定した対象らをリストに追加し、運命を繋げる。運命が繋がった者たちは、燃焼、怪我、回復、窒息や死などあらゆる事象を共有し、同じ運命を辿る。

# # 忠誠のシンボル
# # ・ある程度操作できる剣を召喚し、振り回す。剣は弾丸や矢なども叩き落としてくれる。自分が死んだ際に、剣はしばらく暴走を始める。

# # 幸福のシンボル
# # ・広範囲に麻薬を散布し、自分含む全員に幻覚や眩暈などを引き起こす。

# # 砦のシンボル
# # ・しばらくの間は死亡しても、その後その場に復活できる。

# # 降伏のシンボル
# # ・自身の装備や状況を晒し、白旗を振り回したり設置したりする。運が良ければ許してくれるかもしれない。

# # 鴉のシンボル
# # ・ステージ内に位置する複数の鴉の群れを操作でき、プレイヤーを襲わせたり、諜報を行なったりできる。

# # 助言のシンボル
# # ・何者かが自動で語りかけてくる。自分を狙う敵のシンボルの詳細を伝えてくれる。

# # 突風のシンボル
# # ・リアルタイムで竜巻を操縦する。竜巻はものを吸い上げ上に飛ばす。十分な時間があれば、巨大な竜巻を起こす事も可能。

# # ===========================
# # [16:15]
# # 終末のシンボル
# # ・三日後に太陽を落とす。自分が死ぬと、太陽は元の位置に戻る。

# # 霧のシンボル
# # ・辺り一帯に霧を生む。霧の中では方向感覚が歪み、霧が晴れるまでは確率的にしか脱出できない。また、VCにはノイズが入り意思疎通が不能に。自分は視界が悪くなるだけ。

# # 消去のシンボル
# # ・しばらく自身の存在を認識させなくする。無敵だが、攻撃も出来ない。不意打ちを自動で回避してくれる。シンボル解除時に近くに居る人にノイズが走る。

# # 水のシンボル
# # ・水分補給が出来る。威力は弱いが貫通する水のブレスを放てる。

# # 道化のシンボル
# # ・ランダムな性能の武器を創造する。

# # 情熱のシンボル
# # ・魔弾を放ち、着弾地点で周囲のあらゆる生物やアイテムを引き寄せ、その後爆発する。

# # 平和のシンボル
# # ・誰もダメージを受けないエリアを作る。解除するタイミングは調整できる。

# # 移動のシンボル
# # ・ワープ地点を複数設定でき、誰もがワープ地点を使える。

# # 犠牲のシンボル
# # ・誰かを一人だけ指定し、対象が死亡するような状態に陥った時、自分が身代わりとなって対象を延命する。

# # 呪のシンボル
# # ・複数人の生物を指定でき、対象が日光に晒されると燃焼を始める。

# # 泡のシンボル
# # ・ネバネバする青泡をたくさん噴射し、壁にしたり、ドアを固定したり、相手を動きづらくしたりする。

# # 迫撃のシンボル
# # ・長いチャージの後に、威力の高く速い弾を放つ。また、曲射がとてもしやすい。

# # 反撃のシンボル
# # ・ガード状態で受けたダメージを吸収/蓄積し、その分の火力のエネルギー弾を放つ。近距離攻撃で最も高い威力となる。

# # 賽のシンボル
# # ・やや大きめなサイズのサイコロを投げる。当たっても痛くはない。それだけ。

# # 悪魔のシンボル
# # ・悪魔との取引により、次の試合で様々な不利益を被る事を代償として、体力の大幅上昇/高級な装備/優秀な馬/微弱な再生能力/火炎への耐性のいずれかの利益を得る。

# # 儀式のシンボル
# # ・生贄となる生物を三匹殺し、何かしらの装備を一つ捧げれば、その装備の最後の持ち主が無条件で死ぬ。

# # 強欲のシンボル
# # ・近くに居る人のお金を徐々に強奪する。オンとオフを切り替えれる。

# # ===========================
# # [16:15]
# # 短剣のシンボル
# # ・ダガーを生成し、投げたり近接攻撃したりできる。

# # 磁石のシンボル
# # ・指定したアイテムや生物が、周囲のアイテムや生物を引き付けるようになる。特に武器などを引き付けると連続ダメージの原因になる。弾丸なども引き付ける。

# # 吸血のシンボル
# # ・敵の体力を奪う。

# # 暗殺のシンボル
# # ・接近した生物の内部から刃物や鉄器を生成し、内臓などを傷つけ致命傷を負わせ、最大体力を減らす。生成したものは武器として拾える。

# # 雨のシンボル
# # ・めちゃくちゃ広範囲で、普通の雨を呼ぶ。雨の中に居る間、自分はほぼ透明。

# # 望遠鏡のシンボル
# # ・スコープのように遠くをズームして見れる。

# # 解離のシンボル
# # ・操作できるキャラが五人居て、好きな時にそれらに乗り移れる。自分が操作していない他の四人は、人気を避けてでたらめに行動する。5機あるようなもの。

# # 予感のシンボル
# # ・最寄りのシンボル持ち人間が居る方向または距離のどちらかが分かる。

# # 防衛のシンボル
# # ・地面や周囲の壁の素材を引き剥がして、十分なサイズのシールドを合成し片手で扱う。

# # 欠陥のシンボル
# # ・最後に触れた生物の心臓を、好きなタイミングで引き抜く。但し発動してから心臓が手元に届くまでには少し時間が掛かるので、戦闘向きじゃない。

# # 嘔吐のシンボル
# # ・大量の矢を口から放つ。ほぼダメージは無い。

# # 潜伏のシンボル
# # ・オブジェクトの中に潜伏できる。長い間潜伏していると、窒息ダメージを喰らい始める。

# # ===========================
# # [16:15]
# # 禁忌のシンボル
# # ・触れた人間の特定の行為を制限する。移動や、シンボル以外での攻撃を禁じたり、食料や水分の確保、ボイスチャット、装備の取得などを禁止できる。

# # 懐古のシンボル
# # ・自分を見ている者は、常にPS1のレンダリングみたいな質の粗い画面になる。

# # 自爆のシンボル
# # ・チャージした後に、自分のいるとこで核爆発を起こす。広範囲の近さにいた生物は致命傷を喰らうか死に至り、全員がまばゆい光を感じる。

# # 背信のシンボル
# # ・頭にシーツを被る。その間に限り、シンボルの直接的/間接的な効果を受け付けない。

# # 支配のシンボル
# # ・仮面のような虫を操縦し、触れた人間をしばらく乗っ取りコントロールする。この時、自身は無防備にはならず、好きなタイミングでどちらのキャラを操作するか切り替える事ができる。

# # 暗躍のシンボル
# # ・ゴールの花のある場所がスタート地点になっており、馬には乗れない。

# # 絵画のシンボル
# # ・自身またはアイテムの一つを、絵画の中に忍ばせる事ができる。絵画を生成し壁にかける事も可。

# # 遊泳のシンボル
# # ・周囲に浮遊する水を流しながら自由に空中を泳ぐ。

# # 狂信のシンボル
# # ・複数の触手を召喚し、敵を攻撃してくれる。射程や数の制限こそあるものの、自由に配置したり、直接攻撃に使ったりできる。

# # 蝙蝠のシンボル
# # ・たくさんの蝙蝠を前方に飛ばしたり、蝙蝠に紛れて潜行したりできる。

# # 溶解のシンボル
# # ・壁や床、弾丸などを溶かしてすり抜けられる。また、地面を液状化させる事も可能。触れた生物を腐食させて持続ダメージで殺害する。




# # ==========--こっから重複する恐れ




# # 影のシンボル
# # ・ドッペルゲンガーを召喚/本体入れ替え。　

# # 手のシンボル
# # ・相手が手にしているアイテムを奪える。

# # 透明のシンボル
# # ・血痕や姿を透明にする。近くで見るとバレる。

# # 目のシンボル
# # ・周囲の何者かの視点が見える。

# # 闇のシンボル
# # ・暗いところで透明化し、素早くなる。

# # 恐怖のシンボル
# # ・近くにいる生物や武器が透けて見える。音が可視化される。

# # 水のシンボル
# # ・雨や湿地など水に触れると素早くなる。

# # 石のシンボル
# # ・地面からスパイクを送り、それに触れた相手を石化させる。石化すると動けなくなり防御力が上がる。


# # 賞金首のシンボル
# # ・指定した人間に懸賞金をかける。その人間を殺すと多くのお金がもらえるため、皆に狙われる事になる。

# # 沼のシンボル
# # ・地面に広い沼を発生させ、そこに入った自分以外の者を動きづらくする。

# # 衝撃のシンボル
# # ・前方に衝撃波を放つ。側にいた者は重症を追い、近くにいた者は吹っ飛ばされる

# # 灰のシンボル
# # ・触れた死体や装備を灰に変え証拠を隠滅する。灰はとても見えづらく、時間の経過で完全に散り気付けなくなる。

# # 切断のシンボル
# # ・刃物を持っていた場合、高速で前方に移動し、通過した生物に致命傷を負わせる

# # 月のシンボル
# # ・強制的に夜に変更できる。この能力者をさっさと殺さないとゲームが進行しない可能性がある。


# # 正常のシンボル
# # ・指定した対象のシンボルを封じ使用不可能にする。自身が死ぬと対象の封印は解ける。

# # 痕跡のシンボル
# # ・常に人間や馬の足跡が見える。

# # 獣のシンボル
# # ・しばらくの間攻撃力と防御力が上がり、その場に留まっていられなくなる。その後しばらく非力な状態が続く。再度シンボルを使えば攻撃的にかなれる。

# # 愛着のシンボル
# # ・いつでもどこでも自分専用の銃を取り出したり消したりできる。その銃は捨てると消える。弾薬は要らない。

# # ===========================
# # 静寂のシンボル
# # ・自分や仲間の足音を消したり、対象の耳を聞こえなくしたり、対象を喋れなくさせたり出来る。遠のけば効果は消える。



# # 増殖のシンボル
# # ・指定のアイテムが増殖を始める。付近にいた生物は飲み込まれ、抜け出せなければやがて窒息死する。増殖の最終段階ではそのアイテムの塊は大きな丘のようになっており、体積に対する増殖スピードが比較的遅くなるため上を通れるようになる。

# # 幽居のシンボル
# # ・家を一軒だけ出現させる。その家に入った他者は、シンボルが再使用されるまで二度とその家から出られなくなる。食べ物や水分には困らない。

# # 閃光のシンボル
# # ・大きなフラッシュを炊く。フラッシュを見ていた者は、しばらく視界が妨害される。

# # 落下のシンボル
# # ・高い所から落ちても一切ダメージを受けない。常に発動。落下地点近くの生物に落下ダメージをなすり付ける事もできる。

# # 死のシンボル
# # ・触れると即死する煙を撒き散らす。自分は死なないが、その代わりに体力が減る。

# # 炎のシンボル
# # ・巨大な炎の球を生み出し、片手投げする。炎の球は重力の影響を受け、落下地点で火炎を生む。

# # 冬のシンボル
# # ・自分の辺りの温度を急激に下げ、劣悪な凍傷を誘発させる。松明や暖の近くにいれば問題無い。水面を氷に変え歩けたりする。

# # 粉塵のシンボル
# # ・スプレーを振りかける。スプレーで壁などに落書きしたり、メッセージを残せる。スプレーには催涙作用がある。

# # 天罰のシンボル
# # ・対象のキル数に応じて、空高くからニワトリ/鉄床/雷/隕石を振り落とす。

# # 魂のシンボル
# # ・全員の見た目や位置や装備をシャッフルする。シンボルやVCの声等は変わらない。

# # 追跡のシンボル
# # ・指定した人間の位置や視点、装備、健康状態が常に分かる。その人間が死ぬまでシンボルの再使用は認められない。


# # 重力のシンボル
# # ・広めな周囲の重力の上下を反転させたり、強めたりして自身以外に影響を及ぼす。

# # 孤独のシンボル
# # ・自身もしくは他人を虚無空間へと転送する。いつ現世に戻ってくるかは分からない。虚無空間では腹も減らないしシンボルも使えないし死ねない。

# # 翼のシンボル
# # ・自由に空を飛行できる。落下ダメージは喰らうので減速の調整をしないといけない。

# # ===========================
# # 屍のシンボル
# # ・死体を漁って様々なパーツを集め、それらのパーツを組み合わせてネクロマンシークリーチャーを生む。それらは悶え苦しみながら目につく他者を襲う。

# # 接続のシンボル
# # ・二つ以上の生物、オブジェクト、アイテムなどの位置関係を鎖で固定する。生物に対しては、そのまま引きちぎる事も可能。

# # 貝のシンボル
# # ・貝をアイテムに扮装させて、他者が拾った時に貝の口を閉じさせて、素早さを下げる。貝は熱に弱い。

# # 意思のシンボル
# # ・自由なメッセージを書いた看板や置き手紙を残す事ができる。

# # 脱出のシンボル
# # ・全ての装備を捨て、空高くに上昇し、そのまま滑空する。

# # 斥候のシンボル
# # ・ひもを出してフックショットのように移動したり、逆に相手を引き寄せたり出来る。

# # 黄金のシンボル
# # ・触れたアイテムを金に変えて役に立たないものへと変えれる。他にもドアなどの開閉物を固定したり、オブジェクトをちょっと装飾するのに使える。

# # 鍛冶のシンボル
# # ・ランダムな防具を生成する。

# # 混沌のシンボル
# # ・ゲーム内のシステムメッセージのいくつかを好きに発信できる。

# # 持続のシンボル
# # ・低い壁や床の上などにアサルトライフルを取り付け、前方の敵を自動で攻撃してくれる。

# # 罠師のシンボル
# # ・トラバサミ、毒などの仕込みを無制限かつ手際良く行える。

# # 浄化のシンボル
# # ・水質を汚染したり、食べ物を腐らせたりできる。また、歩いたところの植物が枯れる。

# # 人形のシンボル
# # ・様々な類の人形を複数設置する。人形の近くで、人間が回復をしていたり、装備の整理をしていたり、長時間別の方向を見ているなどの隙を見せた場合、その人形がその人間を襲い始める。

# # ===========================
# # 耳のシンボル
# # ・各地に耳を設置する事ができ、そこでの会話を盗聴できる。また、逆にこちらから話しかける事も可能。

# # 行進のシンボル
# # ・壁や天井なども歩けるようになる。


# # 崩壊のシンボル
# # ・全てを貫通するエネルギー弾を放ち、任意のタイミングで崩壊因子を放つ。崩壊因子に触れた生物は徐々に削られていき、その場所を起点としてマップがどんどん崩落していく。

# # 貪食のシンボル
# # ・飢餓のシンボルを受け付けず、食料でない武器やアイテムなども食べれるようになり、短時間で食事を終える。

# # 燈のシンボル
# # ・松明、キャンプファイヤー、ランタンなどを即席で出現させれる。明かりや暖をとるのに使える上、弱い火炎瓶として投げる事も可能。

# # 造形のシンボル
# # ・壁や橋、梯子や柱を工作したり、それらに穴をあけたり出来る。

# # 真実のシンボル
# # ・対象に暗殺者をつける。暗殺者は、水面や鏡などの反射で確認でき、また対象がそれらに映り込んでいる時にバックスタブを試行する。

# # 束縛のシンボル
# # ・過去に自身を攻撃した生物を距離問わず拘束する。拘束した生物は持ち運べて、地面を掘らせて瞬時に自身の元へ呼び寄せれる。また、その場に留まらせる事も出来る。

# # 飛行船のシンボル
# # ・自身の命とひきかえに、何人も乗せれる巨大な飛行船を召喚し操縦する。飛行船は高い体力を持っており、破壊されると焼け落ちて地面に墜落する。

# # 音色のシンボル
# # ・ジュークボックスを設置する。ゲーム内に登場するサウンドをお楽しみいただけるし、銃声などを偽装する事もできる。

# # 幸運のシンボル
# # ・一定確率でどんな擦り傷も致命傷に変わるような攻撃をする。確率を外すと、自分が致命傷を負う。

# # 案山子のシンボル
# # ・夜の間だけ行動し、自分よりも先頭を走る人間を襲う案山子をスポーンする。案山子は破壊されてもすぐに修復し、特に一人を執拗に追いかけ回す。案山子に触れるとほぼ即死。

# # 魔法のシンボル
# # ・自身の手にした武器をランダムにエンチャントする。

# # 啓蒙のシンボル
# # ・触れた瀕死の生物を、強制的に仲間にする。仲間同士はフレンドリーファイアが発生しない。

# # 向日葵のシンボル
# # ・ヒマワリをたくさん生やす。しゃがんでいると発見されづらくなる。

# # 修復のシンボル
# # ・生物や装備の回復/修理する。また、稀に破壊不能な装備にしたり、別の装備に変異させる事がある。生物であれば、ステータスをランダムにいじる事がある。やや五分五分だか、基本的には改悪する事が多い。

# # ===========================
# # 錆のシンボル
# # ・短い間だが、全てのダメージを大幅に軽減する。

# # 解放のシンボル
# # ・指定した他人をしばらく制御不能のクリーチャーに変貌させる

# # 王のシンボル
# # ・指定した生物やアイテムを、自在に吹き飛ばせる。叩きつけたりも可能

# # 未来のシンボル
# # ・広範囲に渡る誰か一人の死因を決定する。対象がその通りの行動をすれば、対象は避けられない未来により死亡する。


# # 運命のシンボル
# # ・指定した対象らをリストに追加し、運命を繋げる。運命が繋がった者たちは、燃焼、怪我、回復、窒息や死などあらゆる事象を共有し、同じ運命を辿る。

# # 忠誠のシンボル
# # ・ある程度操作できる剣を召喚し、振り回す。剣は弾丸や矢なども叩き落としてくれる。自分が死んだ際に、剣はしばらく暴走を始める。

# # 幸福のシンボル
# # ・広範囲に麻薬を散布し、自分含む全員に幻覚や眩暈などを引き起こす。

# # 砦のシンボル
# # ・しばらくの間は死亡しても、その後その場に復活できる。

# # 降伏のシンボル
# # ・自身の装備や状況を晒し、白旗を振り回したり設置したりする。運が良ければ許してくれるかもしれない。

# # 鴉のシンボル
# # ・ステージ内に位置する複数の鴉の群れを操作でき、プレイヤーを襲わせたり、諜報を行なったりできる。

# # 助言のシンボル
# # ・何者かが自動で語りかけてくる。自分を狙う敵のシンボルの詳細を伝えてくれる。

# # 突風のシンボル
# # ・リアルタイムで竜巻を操縦する。竜巻はものを吸い上げ上に飛ばす。十分な時間があれば、巨大な竜巻を起こす事も可能。

# # ===========================
# # 終末のシンボル
# # ・三日後に太陽を落とす。自分が死ぬと、太陽は元の位置に戻る。

# # 消去のシンボル
# # ・しばらく自身の存在を認識させなくする。無敵だが、攻撃も出来ない。不意打ちを自動で回避してくれる。シンボル解除時に近くに居る人にノイズが走る。

# # 水のシンボル
# # ・水分補給が出来る。威力は弱いが貫通する水のブレスを放てる。

# # 道化のシンボル
# # ・ランダムな性能の武器を創造する。

# # 情熱のシンボル
# # ・魔弾を放ち、着弾地点で周囲のあらゆる生物やアイテムを引き寄せ、その後爆発する。

# # 平和のシンボル
# # ・誰もダメージを受けないエリアを作る。解除するタイミングは調整できる。

# # 移動のシンボル
# # ・ワープ地点を複数設定でき、誰もがワープ地点を使える。

# # 犠牲のシンボル
# # ・誰かを一人だけ指定し、対象が死亡するような状態に陥った時、自分が身代わりとなって対象を延命する。

# # 呪のシンボル
# # ・複数人の生物を指定でき、対象が日光に晒されると燃焼を始める。

# # 泡のシンボル
# # ・ネバネバする青泡をたくさん噴射し、壁にしたり、ドアを固定したり、相手を動きづらくしたりする。

# # 迫撃のシンボル
# # ・長いチャージの後に、威力の高く速い弾を放つ。また、曲射がとてもしやすい。

# # 反撃のシンボル
# # ・ガード状態で受けたダメージを吸収/蓄積し、その分の火力のエネルギー弾を放つ。近距離攻撃で最も高い威力となる。

# # 賽のシンボル
# # ・やや大きめなサイズのサイコロを投げる。当たっても痛くはない。それだけ。

# # 悪魔のシンボル
# # ・悪魔との取引により、次の試合で様々な不利益を被る事を代償として、体力の大幅上昇/高級な装備/優秀な馬/微弱な再生能力/火炎への耐性のいずれかの利益を得る。

# # 儀式のシンボル
# # ・生贄となる生物を三匹殺し、何かしらの装備を一つ捧げれば、その装備の最後の持ち主が無条件で死ぬ。

# # 強欲のシンボル
# # ・近くに居る人のお金を徐々に強奪する。オンとオフを切り替えれる。

# # ===========================

# # 磁石のシンボル
# # ・指定したアイテムや生物が、周囲のアイテムや生物を引き付けるようになる。特に武器などを引き付けると連続ダメージの原因になる。弾丸なども引き付ける。

# # 吸血のシンボル
# # ・敵の体力を奪う。

# # 暗殺のシンボル
# # ・接近した生物の内部から刃物や鉄器を生成し、内臓などを傷つけ致命傷を負わせ、最大体力を減らす。生成したものは武器として拾える。

# # 望遠鏡のシンボル
# # ・スコープのように遠くをズームして見れる。

# # 解離のシンボル
# # ・操作できるキャラが五人居て、好きな時にそれらに乗り移れる。自分が操作していない他の四人は、人気を避けてでたらめに行動する。5機あるようなもの。

# # 予感のシンボル
# # ・最寄りのシンボル持ち人間が居る方向または距離のどちらかが分かる。

# # 防衛のシンボル
# # ・地面や周囲の壁の素材を引き剥がして、十分なサイズのシールドを合成し片手で扱う。

# # 欠陥のシンボル
# # ・最後に触れた生物の心臓を、好きなタイミングで引き抜く。但し発動してから心臓が手元に届くまでには少し時間が掛かるので、戦闘向きじゃない。

# # 嘔吐のシンボル
# # ・大量の矢を口から放つ。ほぼダメージは無い。

# # 潜伏のシンボル
# # ・オブジェクトの中に潜伏できる。長い間潜伏していると、窒息ダメージを喰らい始める。

# # ===========================
# # 禁忌のシンボル
# # ・触れた人間の特定の行為を制限する。移動や、シンボル以外での攻撃を禁じたり、食料や水分の確保、ボイスチャット、装備の取得などを禁止できる。

# # 懐古のシンボル
# # ・自分を見ている者は、常にPS1のレンダリングみたいな質の粗い画面になる。

# # 自爆のシンボル
# # ・チャージした後に、自分のいるとこで核爆発を起こす。広範囲の近さにいた生物は致命傷を喰らうか死に至り、全員がまばゆい光を感じる。

# # 背信のシンボル
# # ・頭にシーツを被る。その間に限り、シンボルの直接的/間接的な効果を受け付けない。

# # 支配のシンボル
# # ・仮面のような虫を操縦し、触れた人間をしばらく乗っ取りコントロールする。この時、自身は無防備にはならず、好きなタイミングでどちらのキャラを操作するか切り替える事ができる。

# # 暗躍のシンボル
# # ・ゴールの花のある場所がスタート地点になっており、馬には乗れない。

# # 絵画のシンボル
# # ・自身またはアイテムの一つを、絵画の中に忍ばせる事ができる。絵画を生成し壁にかける事も可。

# # 遊泳のシンボル
# # ・周囲に浮遊する水を流しながら自由に空中を泳ぐ。

# # 狂信のシンボル
# # ・複数の触手を召喚し、敵を攻撃してくれる。射程や数の制限こそあるものの、自由に配置したり、直接攻撃に使ったりできる。

# # 蝙蝠のシンボル
# # ・たくさんの蝙蝠を前方に飛ばしたり、蝙蝠に紛れて潜行したりできる。

# # 溶解のシンボル
# # ・壁や床、弾丸などを溶かしてすり抜けられる。また、地面を液状化させる事も可能。触れた生物を腐食させて持続ダメージで殺害する。





# #
# #人狼投票　　丸鋸ぴょんぴょん　ソードダンス　ブロックシールド　ランダム矢　巨大化　全員の見た目入れ替え　ドッペルゲンガー　小さな住人たち　Abyssal Countdown、フラッシュバンみたいなやつ
# # #毒霧　ダメージ分散わかるよな　パリィ　クールダウンを強制的にあたえるスキルブレイク　時間スキップてきな無敵時間　新しい生き物、、バッドニュース　ホバーバイク　ホームランバット　壁にはりつくピッケル、壁走り、持ち運び可能な作業台、鉱石の採掘強化、矢の雨、厄災のシンボル
# ゆきだるま　うぃざすけを落とす　指定した人にデモ版　全員が矢に追われる　ホーンテッドアーマー召喚　ドアのやつ召喚、傭兵のシンボル、囮のシンボルさ、犠牲のシンボルでもよくね？説、ジャンプパッドまたはダッシュパッド
# # #モンスターペアレンツ　ふとしたことで牛乳が手に入る　相手のインベントリを鉄格子で埋める　クリーパーの鳴き声だけ、たまにクリーパー　相手の真上に１ブロック化真下の１ブロック削除の二択　そらを泳ぐ　過去の経路にランダムとび、アルケミストな醸造台、強運のシンボルと死体漁り、トランスポーターanniのポータル生成、炎もさ長い方優先か持続時間は加算か
# # #自分が手に入れたいずれかのブロックの上にいるとダメージ　ランダムなｘｙｚの+-10飛ぶ　自分とランダムな人の足元のブロック交換　解放　こうきの最大体力を20にする　# #ワールドにいるランダムなモブの体力量になる　周囲の空気以外のすべてのブロックを粉雪にする　グリムスカイ　ゆきくんの冬　自分と同じ見た目をしたデコイをしょうかんする、まっすぐすすむ　ユトイのレーザー　ブラックボール　だみーぶろっく、壊すとデバフブロック
# # #とりのなかまSANDの一方通行ミラー　サンクション　制裁　人生のせんたくし、ゴリラ育成　ギャルゲー　別の世界から構造物を持ってくる　誰もいない異世界にとぶ　スポンジ人間　シールド付与　バリア、警報と排除システム
# # #視界が雲とかになる代わり人の位置とか見える蜘蛛　自分も含めた誰かの持ってる食料が全部毒になる、シュルカーの弾「魔弾」、スペクトラルアロー
# # #賭けに勝ったら有利になる物がもらえる　死者と生者を入れ替える能力 洗脳　本で殴った人をのっとるヒロインジャック１分　制御しきれないジャンプ力、経験値のオーブ　リトルフラワー　ワールドボーダー透明化　ウォーロード持続力、破壊と仮ブロック設置　かラスのシンボル
# # どっちも嫌な気分になる　空腹なケーキ([sliced=1]がつかいだけ)　スタッフロールながす、スライムで束縛と鈍麻、強靭な斧、隠密、焼夷と蝋燭パイロと火耐性、竜巻、エレベーター、逆境で足が早くなる、相手の攻撃力ゼロ、
# # #みに村人アイテム、ZOMBIEのオートファジー、スナイパーか望遠鏡、
# #　kick系　教室に強盗が入ってきたときに一人で倒せる能力　演劇がはじまる　無敵
# #　ごまふ情報局に代わる能力　半径５Mのところに金床をおとす(かなどこのGUI注意)
# # #能力を得ると自動発動ランダムな時間で爆発する自分がその間に人を殺すと延命、そのあいだ強いみたいなバーサーかー
# # #自分がごはんたべれなくかわりに誰か復活　「ミッション」をこなせなかった人はランダムデバフ（死・鈍足・ダメージなど）　誰かが能力発動したら自分もその能力が勝手に発動する能力　鉄ドアを虚報　本を捨てたら、チョコになる　自由帳にかいてたタブーインデックスのスタンド　気が狂ったスロット　虹のふもと
# # 花に吸い寄せられる　みんなの時間をバラバラにする　ドアを開けたらストーカに殺される能力
# # #シャークネード　能力発動して座標移動すればするほど攻撃力ます　乖離のシンボル　最後の晩餐　スキルポイント振り分け　レベルが上がると強化　雪合戦のレベルアップのきるえふぇくとでる
# # #自分の移動と逆方向にワールドボーダー移動、せまってくる　能力を発動した回数が最も少ない人が向いてる方向を変えられなくなる　ずっとタイトル、サイドバー、ぼすばー、アクションバーに「💛」表示する
# # #スペクテイターの人が爆発する能力(すぺく利用系)　透明化したクリーパーを召喚する　時間経過で強くなるPETを召喚
# # #1分間復活する人もいるのかもしれない　誰かのアイテムランと自分のアイテムランリンク　能力が重複してる人に通知が来る(50%の確率で嘘)つまりなにもわからない
# # #したい消し(先にしたいをつくれ)したいからアイテム奪いたい　最後に能力を使ってから一番時間が経ってる人を空腹にする　どんどん食べられてるケーキ設置　防具縦のポーズをランダムに変える能力
# #　こけた　相手をこけさす（伏せ状態）　ピストンの先　オフハンドとアイテムを交換　画面ちかちかポリゴンショック　スかるくセンサーのwifi　block displayのくそながい硝子ヘリコプター
# # #ターミナルchat　chatでうったテキストがテキストディスプレイででかく表示してくれるネオンも可
# # #落ちてるアイテム見たら画面点滅する　エンティ(これはなに)　リードの取っ手とか釣竿のフックとか額縁の裏側　自分の周りにヘッドが回るベイブレードを召喚する　ビーコンの光におそわれる　スキンを若干ピンク色にかえる
# #ベッドにはいるとファントムの上にのって世界旅行する　拾うまで強制的に視点がむけ続けられる本　ボートをキルする　ボートから降りれない　猫ミーム　一生チャットでちぴちゃぱの歌詞が流れる
# # #全ての行動に権限を要求される　つられた村人がプレイヤーを場外まで弾き飛ばす　掘りますか　▲はい　いいえ　すぺくにテレポート　急に団体戦にする　ブロックが置けなくなる　ディスペンサーから吐き出されるのは常に自分
# # #/gamerule logAdminCommands  を勝手に trueにする　インベントリ強制おーぷん　拡散ポテトマイン　弓で打たれたら凍る　なぜか背後にテレポートする　3回つかうといやなめにあう　死んだ人からアイテムを一つとれる
# # #cdかんすう検知で能力の使用回数を制限　水だと思ったらマグマだった　増殖のシンボル　幽居のシンボル　ワールドの時間と天候をかえれる　コピー安堵ペースト　時間巻き戻し　１５秒きまずいガチ恋距離　10%で　ゴマ府情報局がチャットに現れる
# # # "ラストスタンド|たまに致命傷を無かったことにする|右クリックをする 　"ブラッキーウェーブ|広域にいる生物のある血管を詰まらせる|右クリックをする 
# # # "ユートピア|自分が神になれる半径を作り出す|右クリックをする 　"アサシンステップ|体力変動または時間経過まで防具ごと透明化|右クリックをする 
# # # "指先ほどの炎|生き物などを着火する|右クリックをする|生物を攻撃する　"ティンカーベルの子|物を作るのに作業台が要らない|右クリックをする 
# # # "インスタントエネルギー|保存則を破り生き物などを吹っ飛ばす|中距離内で狙って右クリックをする|その後すぐ左クリックをする 
# # # "貪食|空腹過ぎるので何か食べよう|ブロックを壊す|満腹でないとき生物を攻撃する 　"小さな住人たち|弱くて脆い何かに守ってもらう|右クリック 
# # # "ピンキーパイク|相手の頭蓋骨を若干ピンク色にする|中距離内で狙って右クリックをする　"ドン・ペトロ|牙に触れたものを石化する|右クリック 
# # # "ガガアカシアウィズティアラ|人が所有するカオスを１つ知る|右クリック|その後メニューをクリック 
# # # """地底ツアーはいかが？"" - 1992|今いる場所の上下を削除する|右クリック 
# # # "ザ・グラビティ|重力を逆転させたり強めたりする|上側を向いて右クリック|下側を向いて右クリック|左クリック 　"レインダイバー|空中を水中のように遊泳する|右クリック  #15
# # # "死んだはずのケミィ|でたらめな材質を生成し空き手に持つ|空き手があるとき右クリック 　"&4差し出せ。|いずれかの人間に儀式を行う|動物を殺す|右クリック 
# # # "ぽいぽい！白痴★スター|触手の国から兵士を呼ぶ|右クリック|所有 　"Artemis Leap|落下の衝撃なしに跳躍をする|右クリック|所有 
# # # "ザ・ドリーマー|わぬらん！なにがなにやらよ。|右クリック　 "フグ吐き|口内に大量のフグを生成し吐く|右クリック 
# # # "犬々行進曲(わんわんこうしんきょく) .♉・U|どんな""犬""にでもなれる！|右クリック 　"恐怖するといふ能力|生き物などが壁越しにも見える|右クリック 
# # # "ソードマスター|あらゆる剣を意図して生成できる|空き手があるとき空中で右クリック|空き手があるときスニークして右クリック|空き手があるとき右クリック|オフハンドにあるとき剣を壊す 
# # # "概念削除装置|あらゆる概念を最初から存在しなかったことにします|右クリック  "finally, some wALLs|壊せない透明な壁を手に入れる|投げ捨てる 
# # # "炭鉱掘りの逆夢|人のインベントリを妨害する|右クリック 　"デッドヒート|相手と自分の移動速度に異なる係数を乗算|右クリック 
# # # "java.lang.OutOfMemoryError: unable to create native thread: possibly out of memory or process/resource limits reached|人間として認識させる|右クリック 

# # #みに村人アイテム　　座標に隕石おとす　　痛みなく死ねる力　　つかった瞬間とんでもない再生し始めるけど一定以上回復しないと死ぬ、ZOMBIEのオートファジー
# # #不死のゆみおとこ能力　　非暴力のシンボル　　/kick系　　ダメージ転移　　モンスターストーリー　　教室に強盗が入ってきたときに一人で倒せる能力　　演劇がはじまる
# # #自分の体力をほかの人と同じにできる能力　　無敵　　もしかしたら今この場所に飛行機が落ちてくる予感がする　　誰にも見られてないときに透明になる能力
# # #ごまふ情報局に代わる能力　　半径５Mのところに金床をおとす(かなどこのGUI注意)　　命と引き換えにかまど　　透明になってるやつを一生光らせる能力
# # #能力を得ると自動発動ランダムな時間で爆発する自分がその間に人を殺すと延命、そのあいだ強いみたいなバーサーカー
# # #わたし　あなた　ランダムでどっちかが決まって　お前とか俺って言った人が地上でおよぐ　　お嬢様言葉強制　　ごびにゃん強制　　自分がごはんたべれなくかわりに誰か復活
# # #猫又殺して誰か生かす　　「ミッション」をこなせなかった人はランダムデバフ（死・鈍足・ダメージなど）　　誰かが能力発動したら自分もその能力が勝手に発動する能力
# # #鉄ドアをつくれるし、あけれる　　アクセラレーション　　歌を歌わないと死んでしまう病を作る能力　　Discordのニックネームを毎日かえつづけないと、試合中の歩く速度が０
# # #VRかえ　　虚報　　本を捨てたら、チョコになる　　自由帳にかいてたタブーインデックスのスタンド　　ひろったら動けなくなると、地雷　　気が狂ったスロット
# # #着実に距離をつめてくるカカシにおそわせる　　働きバチ　花に吸い寄せられる　　みんなの時間をバラバラにする　　女王バチ　メフィスト　　上を向いている人を自分のところに集める
# # #ドアを開けたらストーカに殺される能力　　シャークネード　　能力発動して座標移動すればするほど攻撃力ます　　乖離のシンボル　　最後の晩餐
# # #俺だけレベルアップ　スキルポイント振り分け　レベルが上がると強化　雪合戦のレベルアップのきるえふぇくとでる　　電波人間やりたい　　自分の移動と逆方向にワールドボーダー移動、せまってくる
# # #能力を発動した回数が最も少ない人が向いてる方向を変えられなくなる　　ずっとタイトル、サイドバー、ぼすばー、アクションバーに「💛」表示する　　TABみれる(先にみれなくしろ)
# # #スペクテイターの人が爆発する能力(すぺく利用系)　　透明化したクリーパーを召喚する　　時間経過で強くなるPETを召喚　　使用者の方を注視させる
# # #能力使った回数が奇数の人を1分間アドベンチャーモードにする
# # #マネードレイン、お金をロストせず試合から離脱
# # #1分間復活する人もいるのかもしれない  醸造  誰かのアイテムランと自分のアイテムランリンク　　能力が重複してる人に通知が来る(50%の確率で嘘)つまりなにもわからない
# # #死体消し(ってか追い剝ぎ　　最後に能力を使ってから一番時間が経ってる人を空腹にする  どんどん食べられてるケーキ設置  防具立てポーズをランダムに変える　　
# # #落下ダメージ食らったら誰かも食らう能力　　こけた　相手をこけさす（伏せ状態）　　ピストンの先　　スかるくセンサーのwifi　　block displayのくそながい硝子ヘリコプター
# # #ターミナルchat　　chatでうったテキストがテキストディスプレイででかく表示してくれるネオンも可　　落ちてるアイテム見たら画面点滅する　　リードの取っ手とか釣竿のフックとか額縁の裏側
# # #自分の周りにヘッドが回るベイブレードを召喚する　　ビーコンの光におそわれる
# # #すべてのエンティティの見た目いれかえ　　ベッドにはいるとファントムの上にのって世界旅行する　　拾うまで強制的に視点がむけ続けられる本　　ボートをキルする
# # #ボートから降りれない　　猫ミーム　一生チャットでちぴちゃぱの歌詞が流れる　　全ての行動に権限を要求される　　つられた村人がプレイヤーを場外まで弾き飛ばす　　掘りますか　▲はい　いいえ
# # #急に団体戦にする　　ブロックが置けなくなる(アドベンチャー化切り替え)　　投票系　　インベントリ強制おーぷん　　GATEてきな毒入りの食べ物生成(てか毒入れる)　　偽物能力
# # #拡散ポテトマイン　　弓で打たれたら凍る　　なぜか背後にテレポートする　　3回つかうといやなめにあう　　死んだ人からアイテムを一つとれる　　cdかんすう検知で能力の使用回数を制限
# # #水だと思ったらマグマだった　　増殖のシンボル　　幽居のシンボル　　ワールドの時間と天候をかえれる　　コピー安堵ペースト　　時間巻き戻し　　１５秒きまずいガチ恋距離　　ゴマ府情報局がチャットに現れる
# # #   バトロワモード　相棒デュオ　２軍隊衝突　人狼だけ能力　生まれつき形質　ジャンプ弱い　ペットの猫がいる　妊婦　能力いっぱい
# # #しあいの報奨金倍率とか、ランダムに333倍マッチてきなノリつくって、全体の総額(プレイ人数分)を安定させる

# プロトタイプ版で実際にあった試合:
# - 序盤で装備を破棄し、能力を一切使わずに他の全員を殺害したプレイヤー
# - 二大勢力が結成され、激しい抗争をしたが、実は殆どクラブマークで味方
# - 双対のシンボルで、空を飛んでた飛行機と位置交換して逆転したプレイヤー
# - 重力のシンボルと彗星のシンボルが手を組み、即着弾する迫撃砲で蹂躙
# - 民間人を片っ端から殺して自殺する、イカれた行動原理のプレイヤー
# - シンボルで荒稼ぎをし、銀行や証券などを単独でダウンさせたプレイヤー
# - 不死のシンボル同士の果てしない消耗戦が続き、ガソスタの爆発で相打ち
# - 終盤まで無双してプレイヤーが、あっけなくオオカミのNPCに喰い殺される
# - VCでの罵詈雑言だけは禁止にしよう、という人権宣言が自発的に締結される
# - 弱い装備のプレイヤーらが、敵同士な事を承知した上で徒党を組んで大逆転
# - NANDゲート的な発動条件のシンボルを組み合わせ、電卓を作ったプレイヤー
# - 頻繁に裏切るプレイヤーは村八分にされ、序盤で死にやすい自浄作用
# - 電卓作ったプレイヤーがサーバーダウンさせる方法を編み出した(修正済み)
# 発見: |
#   直感的には、ボブのシンボルは最弱で、停止のシンボルのが勝率が高い
#   しかし三ヶ月間データを集計すると、その差はわずか最大0.1%しか無かった
#   むしろプレイヤー間での方が、勝率の違いが最大21%と顕著だったのである
#   つまり、上手いプレイヤーは何を持たせても上手く立ち回るという事が判明
#   これを知った製作者は、「現実でも同じ事が起きてるのでは？」と考えた
#   短期的な試合結果だけ見れば、確かに運や情報に左右される部分も大きい
#   ではなぜ、環境に不平不満を垂らすだけのプレイヤーの“勝率が低い”のか？
#   製作者はこの現象に名前を付けた、“敗者のシンボル”と。


# リファレンス:
# - $r # マウスの右クリック
# - $l # マウスの左クリック
# - $o # シンボルを所有最中
# - $a # 常時($oと独立する)
# - $d # $oでかつ攻撃をする
# - $v # $oでかつ攻撃される
# - $s # シフトキーの入力中



# マップ一覧

# ごまふコレクション 👑
# セクター23 居住区

# ジンジャーエール
# タイニータウン、ネイチャースフィア、グラウンドスフィア

# Curtain Call
# ハイジャック

# タクティカルタコさん
# 炭鉱丘陵、スカイアリーナ

# Raven Calamity
# 冬山

# ユミトリ
# 白い廃城

# Slime Basket
# バスケットコート

# 弓漢
# 伝説の地、アサシンタウン、リオデジャネーヨ

# Minecraft Simulator
# 小さな国の物語

# AntiAthletics
# クロックタワー

# B6S & とりのなかま
# ベニクラゲセンター、ベニクラゲバンク
# ごまふ
# スレ主
#  — 2025/04/14 18:43
# 開発ノート

# ワンパン弓軽量モード
# プロップハントは、スモール、ブロックまね、影潜伏、エーテルだいぶ
# ボンバーマン


# #ーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーー
# #
# #  00  11                  1            1                  11  00  |
# #  1100  0000 1000          1          1          0001 0000  0011  |  Paper      1.20.4-R0.1-SNAPSHOT
# #    0000000       1          0      0          1      00000000    |  Denizen    1.3.0-SNAPSHOT
# #    1000 0    11    110      1      1      011    11    0 0001    |  ViaVersion 5.4.1
# #   1100 0    1001      100     1  1     001      1001    0 0011   |
# #    10000   100001  111   101  1  1  101   111  100001   00001    |
# #     0000 0  10010 1        0   00   0        1 01001  0 0000     |
# #      000     11000 1          0110          1 00011     000      |
# #      000000     0 1 111    00 1  1 00   111 1 0     000000       |
# #       00000            111  00111100  111            00000       |
# #       00   0        000      011110      000        0   00       |
# #         0000  000000       0 0 11 0 0       000000  0000         |
# #             1 000     00    11 11 11    00     000 1             |
# #               00           01  11  10           00               |
# #              100  1000100 001  11   100 0100001  001             |
# #                100   101                  101   001              |  STEEL BLOCK RUN - powered by gomaf.
# #                 0     1                    1     0               |
# #
# #ーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーー


# # アイテム管理
# function Food() ::item:
#     loop all items:
#         add loop-value to {_food::*} if loop-value is edible 
#     subtract enchanted golden apple from {_food::*}
#     subtract poisonous potato from {_food::*}
#     subtract mushroom stew from {_food::*}
#     subtract golden apple from {_food::*}
#     subtract pufferfish from {_food::*}
#     subtract cake from {_food::*}
#     subtract spider eye from {_food::*}
#     subtract rabbit stew from {_food::*}
#     subtract honey bottle from {_food::*}
#     subtract beetroot soup from {_food::*}
#     subtract suspicious stew from {_food::*}
#     return (random element out of {_food::*})
# function Misc() ::item:
#     add wooden axe to {_misc::*}
#     add wooden sword to {_misc::*}
#     add wooden shovel to {_misc::*}
#     add wooden pickaxe to {_misc::*}
#     add golden axe to {_misc::*}
#     add golden sword to {_misc::*}
#     add golden shovel to {_misc::*}
#     add golden pickaxe to {_misc::*}
#     add stone axe to {_misc::*}
#     add stone sword to {_misc::*}
#     add stone shovel to {_misc::*}
#     add stone pickaxe to {_misc::*}
#     add chainmail boots to {_misc::*}
#     add chainmail helmet to {_misc::*}
#     add chainmail leggings to {_misc::*}
#     add chainmail chestplate to {_misc::*}
#     add leather boots to {_misc::*}
#     add leather helmet to {_misc::*}
#     add leather leggings to {_misc::*}
#     add leather chestplate to {_misc::*}
#     add golden boots to {_misc::*}
#     add golden helmet to {_misc::*}
#     add golden leggings to {_misc::*}
#     add golden chestplate to {_misc::*}
#     add powder snow bucket to {_misc::*}
#     add flint and steel to {_misc::*}
#     add water bucket to {_misc::*}
#     add fishing rod to {_misc::*}
#     add wind charge to {_misc::*}
#     add ender pearl to {_misc::*}
#     add milk bucket to {_misc::*}
#     add lava bucket to {_misc::*}
#     add spyglass to {_misc::*}
#     add shield to {_misc::*}
#     add lead to {_misc::*}
#     set {_egg} to 32 of egg
#     set {_snowball} to 32 of snowball
#     set max stack size component of {_egg} to 32
#     set max stack size component of {_snowball} to 32
#     add {_snowball} to {_misc::*}
#     add {_egg} to {_misc::*}
#     return (random element out of {_misc::*})

#             set {winner} to "&8&lジョーカー🃏" if {winner} is "🃏"
#             send coloured "<#cd853f> - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -" to all players
#             send coloured "<#cd853f>" to all players
#             send coloured "<#cd853f>  &7&l勝利チーム： &f&l%{winner}%" to all players
#             send coloured "<#cd853f>" to all players
#             send coloured "<#cd853f>" to all players
#             loop {♠::*}:
#                 send coloured "<#cd853f>  &fスペード♠： %loop-value% &8(%{skill_%loop-value's name%}%)" to all players if {winner} is "&fスペード♠"
#                 send coloured "<#cd853f>  &7スペード♠： %loop-value% &8(%{skill_%loop-value's name%}%)" to all players if {winner} isn't "&fスペード♠"
#             loop {♥::*}:
#                 send coloured "<#cd853f>  &fハート♥： %loop-value% &8(%{skill_%loop-value's name%}%)" to all players if {winner} is "&4ハート♥"
#                 send coloured "<#cd853f>  &7ハート♥： %loop-value% &8(%{skill_%loop-value's name%}%)" to all players if {winner} isn't "&4ハート♥"
#             loop {♦::*}:
#                 send coloured "<#cd853f>  &fダイヤ♦： %loop-value% &8(%{skill_%loop-value's name%}%)" to all players if {winner} is "&4ダイヤ♦"
#                 send coloured "<#cd853f>  &7ダイヤ♦： %loop-value% &8(%{skill_%loop-value's name%}%)" to all players if {winner} isn't "&4ダイヤ♦"
#             loop {♣::*}:
#                 send coloured "<#cd853f>  &fクラブ♣： %loop-value% &8(%{skill_%loop-value's name%}%)" to all players if {winner} is "&fクラブ♣"
#                 send coloured "<#cd853f>  &7クラブ♣： %loop-value% &8(%{skill_%loop-value's name%}%)" to all players if {winner} isn't "&fクラブ♣"
#             loop {🃏::*}:
#                 send coloured "<#cd853f>  &fジョーカー🃏： %loop-value% &8(%{skill_%loop-value's name%}%)" to all players if {winner} is "&8ジョーカー🃏"
#                 send coloured "<#cd853f>  &7ジョーカー🃏： %loop-value% &8(%{skill_%loop-value's name%}%)" to all players if {winner} isn't "&8ジョーカー🃏"
#             send coloured "<#cd853f>" to all players
#             send coloured "<#cd853f> - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -" to all players
#             loop players:
#                 reset loop-player
#                 clear {skill_%loop-player's name%}
#                 teleport loop-player at location(0,100,0,"world")
#             execute console command "/effect give @a minecraft:blindness 1 255 true"
#             send title {winner} with subtitle "&7チームが勝利しました" to all players for 4 second
#             set {_map} to a new cuboid region from location(-300,-64,-300) to location(300,319,300)
#             use we to set blocks in {_map} to air
#             clear {selected_map::*}
#             clear {play::*}, {spec::*}
#             clear {♠::*}, {♥::*}, {♦::*}, {♣::*}, {🃏::*}
#         else if arg-1 is 1: 
#             {game} isn't set
#             set {game} to arg-2
#             execute console command "/team add player"
#             execute console command "/team modify player color dark_red"
#             execute console command "/team modify player collisionRule always"
#             execute console command "/team modify player nametagVisibility never"
#             execute console command "/team modify player seeFriendlyInvisibles false"
#             execute console command "/worldborder warning distance 1000"
#             wait a tick
#             ShuffledMap()
#             set {winner} to "n"
#             execute console command "/bossbar add timer ""------------------------"""
#             paste schematic named "%{selected_map::1}%" at location(-70,100,-70):
#                 paste entities: true
#                 paste biomes: true
#                 ignore air: true
#             set {_test} to true if size of all players is 1
#             send coloured "<#cd853f> - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -" to all players
#             send coloured "<#cd853f>" to all players
#             send coloured "<#cd853f>  &7マップ： &f%{selected_map::3}% &8(%{selected_map::2}%)" to all players
#             send coloured "<#cd853f>" to all players
#             loop players:
#                 send coloured "<#cd853f>  &7参加者%loop-counter%： &f%loop-value%" to all players
#             send coloured "<#cd853f>" to all players
#             if arg-2 is "DM": #Deathmatch
#                 add {skill::*} to {_skill::*}
#                 remove {banned::*} from {_skill::*}
#                 loop 9 times:
#                     add paper named "&7トランプの&f♠%loop-number +1%" to {_cards::*}
#                     add paper named "&7トランプの&4♥%loop-number +1%" to {_cards::*}
#                     add paper named "&7トランプの&4♦%loop-number +1%" to {_cards::*}
#                     add paper named "&7トランプの&f♣%loop-number +1%" to {_cards::*}
#                 add paper named "&7トランプの&8🃏" to {_cards::*}
#                 add paper named "&7トランプの&f♠J" to {_cards::*}
#                 add paper named "&7トランプの&4♥J" to {_cards::*}
#                 add paper named "&7トランプの&4♦J" to {_cards::*}
#                 add paper named "&7トランプの&f♣J" to {_cards::*}
#                 add paper named "&7トランプの&f♠Q" to {_cards::*}
#                 add paper named "&7トランプの&4♥Q" to {_cards::*}
#                 add paper named "&7トランプの&4♦Q" to {_cards::*}
#                 add paper named "&7トランプの&f♣Q" to {_cards::*}
#                 add paper named "&7トランプの&f♠K" to {_cards::*}
#                 add paper named "&7トランプの&4♥K" to {_cards::*}
#                 add paper named "&7トランプの&4♦K" to {_cards::*}
#                 add paper named "&7トランプの&f♣K" to {_cards::*}
#                 add paper named "&7トランプの&f♠A" to {_cards::*}
#                 add paper named "&7トランプの&4♥A" to {_cards::*}
#                 add paper named "&7トランプの&4♦A" to {_cards::*}
#                 add paper named "&7トランプの&f♣A" to {_cards::*}
#                 loop players:
#                     reset loop-player to "play"
#                     set {_card} to random element out of {_cards::*}
#                     set {_skill} to random element out of {_skill::*}
#                     send subtitle "&8&o違うマークの陣営を全滅させましょう" to loop-player for 4 second
#                     set slot 0 of loop-player's inventory to ({_skill})
#                     set slot 1 of loop-player's inventory to (1 of bow or crossbow)
#                     set slot 2 of loop-player's inventory to (random integer between 20 and 30 of Food())
#                     set slot 3 of loop-player's inventory to (1 of potion of strong instant health)
#                     set slot 4 of loop-player's inventory to (1 of potion of strong instant health)
#                     set slot 5 of loop-player's inventory to (Misc())
#                     set slot 6 of loop-player's inventory to (Misc())
#                     set slot 7 of loop-player's inventory to (random integer between 20 and 30 of arrow)
#                     set slot 8 of loop-player's inventory to {_card}
#                     add loop-player to {♠::*} if {_card}'s name contains "♠"
#                     add loop-player to {♥::*} if {_card}'s name contains "♥"
#                     add loop-player to {♦::*} if {_card}'s name contains "♦"
#                     add loop-player to {♣::*} if {_card}'s name contains "♣"
#                     add loop-player to {🃏::*} if {_card}'s name contains "🃏"
#                     execute console command "/team join player %loop-player%"
#                     set {skill_%loop-player's name%} to uncolored name of {_skill}
# #                    send coloured "<##cd853f>　　&7あなたの能力： &f%name of {_skill}%" to loop-player
# #                    loop (lore of {_skill}):
# #                        send coloured "<##cd853f>　　&7　　　　　　　　　&8%loop-value-2%" to loop-player
#                     subtract {_card} from {_cards::*}
#                 send coloured "<#cd853f>" to all players
#                 loop {🃏::*}:
#                     send title "&7&lあなたは&8&lジョーカー🃏&7&lです" to loop-value
#                     send coloured "<#cd853f>  &7&lあなたは&8&lジョーカー🃏&7&l陣営です" to loop-value
#                 loop {♠::*}:
#                     send title "&7&lあなたは&f&lスペード♠&7&lです" to loop-value
#                     send coloured "<#cd853f>  &7&lあなたは&f&lスペード♠&7&l陣営です" to loop-value
#                 loop {♥::*}:
#                     send title "&7&lあなたは&4&lハート♥&7&lです" to loop-value
#                     send coloured "<#cd853f>  &7&lあなたは&4&lハート♥&7&l陣営です" to loop-value
#                 loop {♦::*}:
#                     send title "&7&lあなたは&4&lダイヤ♦&7&lです" to loop-value
#                     send coloured "<#cd853f>  &7&lあなたは&4&lダイヤ♦&7&l陣営です" to loop-value
#                 loop {♣::*}:
#                     send title "&7&lあなたは&f&lクラブ♣&7&lです" to loop-value
#                     send coloured "<#cd853f>  &7&lあなたは&f&lクラブ♣&7&l陣営です" to loop-value
#                 send coloured "<#cd853f>" to all players
#                 send coloured "<#cd853f> - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -" to all players


# #     add "重力|右クリ>>上向きで重力弱める|右クリ>>下向きで重力強める" to {_s::*}
# # #    add "慈愛|右クリ>>誰かを仲間に加える|常時　>>仲間同士は殴れなくなる" to {_s::*}
# #     add "予言|右クリ>>誰かの未来を告げる|常時　>>予言の内容は必ず当たる" to {_s::*}
# #     add "封印|右クリ>>目の前の人間を封印|常時　>>シンボルの発動を防げる" to {_s::*}
# # #    add "磁化|右クリ>>目の前の物体を磁化|常時　>>磁石は周囲に引力を生む" to {_s::*}
# # #    add "侵蝕|右クリ>>侵蝕弾を射出し操作|常時　>>その弾に触れた物は腐る" to {_s::*}
# # #    add "貪食|与ダメ>>満腹するまで食べる|破壊　>>ブロックごと食べる|所持　>>極度の飢餓状態" to {_s::*}
# #     add "屍術|右クリ>>死体を生き返らせる|常時　>>ゾンビから敵視されない" to {_s::*}
# #     add "彗星|右クリ>>隕石を誘導して空爆" to {_s::*}
# #     add "追跡|右クリ>>生物の足跡を見れる" to {_s::*}
#     add "透明|右クリ>>迷彩モードを切替|被ダメ>>迷彩モード強制解除" to {_s::*}
# #     add "消滅|右クリ>>暫く周囲を消し去る" to {_s::*}
# #     add "相棒|右クリ>>呪いの馬を召喚する" to {_s::*}
# #     add "不死|所持　>>焼死以外は復活する" to {_s::*}
# #     add "河豚|右クリ>>大量のフグを吐き出す" to {_s::*}
# #     add "運命|右クリ>>目前の生物が運命を共有|常時　>>共有された生物は同じ末路を辿る" to {_s::*}
# #     add "蟲|右クリ>>大量の害虫を湧かす|与ダメ>>害虫らに敵を襲撃させる|所持　>>害虫から敵視されない" to {_s::*}
# #     add "嵐|右クリ>>目の前の物体に暴風|常時　>>視点の先に物体を動かす" to {_s::*}
# #     add "雨|右クリ>>酸性雨を発生させる" to {_s::*}
# #     add "耳|シフト>>聴覚を研ぎ澄ませる" to {_s::*}
# #     add "夢|右クリ>>ランダムな能力取得" to {_s::*}



# #ーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーー
# # アイテム一覧
# on load:
#     execute console command "/kill @e[type=minecraft:armor_stand,name=""Item""]"
#     spawn armor stand at location(0.5,110.5,0.5,"world2",0,0)
#     set {_Item} to last spawned armor stand
#     set name of {_Item} to "Item"
#     execute console command "/item replace entity @e[type=minecraft:armor_stand,name=""Item""] weapon.mainhand with iron_bars[hide_tooltip= {}]"
#     set {インベントリ妨害} to (tool of {_Item}) with item flags all item flags named "&0" #
# # 素材
#     execute console command "/item replace entity @e[type=minecraft:armor_stand,name=""Item""] weapon.mainhand with iron_nugget[rarity= ""common"",max_stack_size=10]"
#     set {Item_鉄銭} to (tool of {_Item}) with item flags all item flags named "&r鉄銭" #
#     execute console command "/item replace entity @e[type=minecraft:armor_stand,name=""Item""] weapon.mainhand with string[rarity= ""common"",max_stack_size=10]"
#     set {Item_糸くず} to (tool of {_Item}) with item flags all item flags named "&r糸くず" #
#     execute console command "/item replace entity @e[type=minecraft:armor_stand,name=""Item""] weapon.mainhand with netherite_scrap[rarity= ""common"",max_stack_size=10]"
#     set {Item_金属部品I} to (tool of {_Item}) with item flags all item flags named "&r金属部品I" #
#     execute console command "/item replace entity @e[type=minecraft:armor_stand,name=""Item""] weapon.mainhand with disc_fragment_5[rarity= ""uncommon"",max_stack_size=10]"
#     set {Item_金属部品II} to (tool of {_Item}) with item flags all item flags named "&r金属部品II" #
#     execute console command "/item replace entity @e[type=minecraft:armor_stand,name=""Item""] weapon.mainhand with heavy_core[rarity= ""rare"",max_stack_size=10]"
#     set {Item_金属部品III} to (tool of {_Item}) with item flags all item flags named "&r金属部品III" #
#     execute console command "/item replace entity @e[type=minecraft:armor_stand,name=""Item""] weapon.mainhand with glow_ink_sac[rarity= ""common"",max_stack_size=10]"
#     set {Item_化学薬品I} to (tool of {_Item}) with item flags all item flags named "&r化学薬品I" #
#     execute console command "/item replace entity @e[type=minecraft:armor_stand,name=""Item""] weapon.mainhand with magma_cream[rarity= ""uncommon"",max_stack_size=10]"
#     set {Item_化学薬品II} to (tool of {_Item}) with item flags all item flags named "&r化学薬品II" #
#     execute console command "/item replace entity @e[type=minecraft:armor_stand,name=""Item""] weapon.mainhand with experience_bottle[rarity= ""rare"",max_stack_size=10,enchantment_glint_override=false]"
#     set {Item_化学薬品III} to (tool of {_Item}) with item flags all item flags named "&r化学薬品III" #
#     execute console command "/item replace entity @e[type=minecraft:armor_stand,name=""Item""] weapon.mainhand with spruce_planks[rarity= ""common"",max_stack_size=10]"
#     set {Item_松材} to (tool of {_Item}) with item flags all item flags named "&r松材" #軽量木製ツールや、丸盾の材料
#     execute console command "/item replace entity @e[type=minecraft:armor_stand,name=""Item""] weapon.mainhand with stripped_oak_log[rarity= ""common"",max_stack_size=10]"
#     set {Item_樫材} to (tool of {_Item}) with item flags all item flags named "&r樫材" #重量木製ツールや、大盾の材料
#     execute console command "/item replace entity @e[type=minecraft:armor_stand,name=""Item""] weapon.mainhand with bone[rarity= ""common"",max_stack_size=10]"
#     set {Item_人骨} to (tool of {_Item}) with item flags all item flags named "&r人骨" #同コスト軽量骨製ツールや、一部エンティティ鎮圧の材料
#     execute console command "/item replace entity @e[type=minecraft:armor_stand,name=""Item""] weapon.mainhand with skeleton_skull[rarity= ""common"",max_stack_size=10]"
#     set {Item_髑髏} to (tool of {_Item}) with item flags all item flags named "&r髑髏" #同コスト軽量骨製ツールや、一部エンティティ鎮圧の材料
#     execute console command "/item replace entity @e[type=minecraft:armor_stand,name=""Item""] weapon.mainhand with netherite_ingot[rarity= ""uncommon"",max_stack_size=10]"
#     set {Item_鉛} to (tool of {_Item}) with item flags all item flags named "&r鉛" #同コスト重量鉛製ツールや、放射線ガスマスク、
#     execute console command "/item replace entity @e[type=minecraft:armor_stand,name=""Item""] weapon.mainhand with iron_ingot[rarity= ""uncommon"",max_stack_size=10]"
#     set {Item_錫} to (tool of {_Item}) with item flags all item flags named "&r錫" #同コスト重量鉛製ツールや、回路基板やパーツ、
#     execute console command "/item replace entity @e[type=minecraft:armor_stand,name=""Item""] weapon.mainhand with book[rarity= ""uncommon"",max_stack_size=10]"
#     set {Item_古びた図書} to (tool of {_Item}) with item flags all item flags named "&r古びた図書" #
#     execute console command "/item replace entity @e[type=minecraft:armor_stand,name=""Item""] weapon.mainhand with trial_key[rarity= ""uncommon"",max_stack_size=10]"
#     set {Item_古びた発條} to (tool of {_Item}) with item flags all item flags named "&r古びた発條" #
#     execute console command "/item replace entity @e[type=minecraft:armor_stand,name=""Item""] weapon.mainhand with leather_horse_armor[rarity= ""uncommon"",max_stack_size=10,attribute_modifiers={show_in_tooltip:0b,modifiers:[]}]"
#     set {Item_小さなおもちゃ} to (tool of {_Item}) with item flags all item flags named "&r小さなおもちゃ" #
#     execute console command "/item replace entity @e[type=minecraft:armor_stand,name=""Item""] weapon.mainhand with silence_armor_trim_smithing_template[rarity= ""rare"",max_stack_size=10]"
#     set {Item_朽ちた精密機器} to (tool of {_Item}) with item flags all item flags named "&r朽ちた精密機器" #


  
# サイトと呼称される財団の施設は隠された施設、つまり存在自体は公に知られているものの政府やフロント企業の物であるように偽装されているような施設です。大多数のエリアは徹底的なフェイルセーフ方策、例えば施設内核弾頭などを持っています。
# 施設内区域





# ゲーム概要: |
#   「もしも能力バトルが現実にあったら」を体現した、バトルロワイヤル！
#   タイトルは『ANOMATROL』で、既に三ヶ月間のβテストに成功済み！
# 序盤の立ち回り: |
#   まずはランダムな食料・銃器・近接武器・シンボル・トランプが配られる。
#   参加者はいずれかのトランプに割り当てられ、他スートを殲滅すれば勝ち。
#   割り当ては被らず、一匹狼のジョーカーを含めて最大53人プレイ(13×4+1)。
#   トランプアイテムは入手したりもできるが、割り当てられたチームは固定。
#   他プレイヤーが敵か仲間かを推測する方法は、基本的に下記の四つ。
#   1.殺して直接確認。元も子もないが早い。アイテムは偽造できるため警戒。
#   2.会話による確認。状況判断が命。お互い開示せず終盤までの結託もアリ。
#   3.真実のシンボル。一番確実だが、このシンボル単独では戦闘力に欠ける。
#   4.コミットメント。殆ど脅迫だが、上手く使いこなせば仲間を炙り出せる。
# 中盤の立ち回り: |
#   信用しすぎはリスクだが、疑いすぎると孤立して、却って危ないため注意。
#   マップは広く、天候や昼夜も変わる。大抵、皆は市民や動物に紛れている。
#   ここで優先すべきは、勢力関係と、単独でヤバいシンボルが居るかの把握。
#   スートと同様、相手の能力も洞察するしかない。基本的に下記の四つ。
#   1.不自然な行動の確認。積極的な接近、やたら高所を取る、銃を捨てる等。
#   2.殺傷能力による余裕。リスキーな言動の背景には、たいてい自信が絡む。
#   3.退避や防衛は可能か。いわゆる"搦手"や"詰み"は、予想しとくしかない。
#   4.カウンターは可能か。敵を仕留めるには"素早い不意打ち"が最も効果的。
# 終盤の立ち回り: |
#   積極的なプレイヤーは、数々の戦利品からシンボルを回収しまくっている。
#   この際は、敵の誰かを懐柔する・交渉して延命させてもらうのも一つの手。
#   欺瞞、いじめ、裏切り、イカサマ、集団リンチ、なんでも起きるため注意。
#   ここまで理不尽に耐え抜いて、突如ゲームが終了したら……
#   おめでとう、君の勝ちだ。

# on break:
#     cancel event
#     spawn block display of chain at block:
#         set display view range of entity to 999
#         set display scale of entity to vector({gdx},{gdy},{gdz})
#         rotate entity around x axis by {grx} degrees
#         rotate entity around y axis by {gry} degrees
#         rotate entity around z axis by {grz} degrees
#     set {_e} to last spawned display entity
#     while {_e} is set:   
#         wait a tick
#         if player is sprinting:
#             kill {_e}
#             stop
#         if player is sneaking:
#             player is on ground
#             send "かくていした" to ops
#             stop
# command /g-dx <number>:
#     trigger:
#         set {gdx} to arg
# command /g-dy <number>:
#     trigger:
#         set {gdy} to arg
# command /g-dz <number>:
#     trigger:
#         set {gdz} to arg

# command /g-rx <number>:
#     trigger:
#         set {grx} to arg
# command /g-ry <number>:
#     trigger:
#         set {gry} to arg
# command /g-rz <number>:
#     trigger:
#         set {grz} to arg



# # ウォールダッシュ
# on player press of jump key:
#     player isn't on ground
#     {play::*} contain player
#     loop 60 times:
#         # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
#         wait 1 tick
#         while size of {停止::*} > 0:
#             wait a tick
#         if any:
#             {game} isn't set
#             player is on ground
#             {spec::*} contain player
#             gamemode of player is spectator
#             player isn't pressing jumping key
#         then:
#             stop loop
#         if all:
#             block 0.8 meter horizontal to the left of player is passable
#             block 0.8 meter horizontal to the right of player is passable
#             block 0.8 meter horizontal to the left of player's head is passable
#             block 0.8 meter horizontal to the right of player's head is passable
#         then:
#             stop loop
#         # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
#         execute console command "/playsound minecraft:block.stone.break master @a %Loc(player)% 0.3 2"
#         set player's generic gravity attribute to -0.001
#     set player's generic gravity attribute to 0.08
